### ISSUE TITLE
STRIP - Adding another ON mode ON - 5V, OFF - 0V

### ISSUE THREAD

**Issue by vcvrackideas** [stoermelder/vcvrack-packone#10]
So it's like using OR NOR functions - if Gate is on STRIP becomes ON and when Gate is off STRIP becomes off.

**Comment by stoermelder** [comment]
Added in 70e2e0923c9ba57c601b5b2d4ebc5ab043de8cb9, 0V=LOW, >=1V=HIGH.

**Comment by stoermelder** [comment]
Fixed voltage in c09c9baa407ba96831d9db660ca05372271e8eda.
