### ISSUE TITLE
umap or other mod

### ISSUE THREAD

**Issue by ghost** [stoermelder/vcvrack-packone#100]
HI is there a way to use these modules to modulate a modules menu parameters like random or presets or scales in the right click menu?

**Comment by stoermelder** [comment]
While this is not possible for arbitrary menu items in Rack v1, my STRIP module provides CV control for randomize, enable and disable.

**Comment by ghost** [comment]
You are kidding!! Cool

**Comment by ghost** [comment]
yes it works. But I need a way to exclude certain parameters from randomization now using the strip module

**Comment by stoermelder** [comment]
Please check the manual, this is already possible.

**Comment by ghost** [comment]
Sweet you though of it all!
