### ISSUE TITLE
SAIL - Relative encoder mode fails to reach extreme ends

### ISSUE THREAD

**Issue by gazzar** [stoermelder/vcvrack-packone#106]
_Originally posted by @gazzar in https://github.com/stoermelder/vcvrack-packone/issues/98#issuecomment-584070937_

I suggested in the above comment that there might be a bug in SAIL but maybe it's an intrinsic limitation I don't understand. Since that comment thread was marked as an enhancement I'm creating a new issue to enable this to be tracked as a bug (or closed if I'm misunderstanding something). Quoting the relevant description there "I did notice a little quirk where the Rack knob or slider being controlled can occasionally fail to reach the extreme ends of its range. Moving the mouse pointer away from and back over the control then allows the control to continue increasing or decreasing to its limit. Since MIDI-STEP is continuing to output pulses, I suspect this is a small bug or possibly a limitation in SAIL."

**Comment by stoermelder** [comment]
Can you confirm this only happens if INC/DEC and IN are used the same time?

**Comment by gazzar** [comment]
Actually I don't have IN connected. I just have INC/DEC connected like this and it still happens

![image](https://user-images.githubusercontent.com/131836/77848285-6acb3680-720f-11ea-9bb0-da399a3308e1.png)

**Comment by stoermelder** [comment]
You are right. I did some strange calculations when entering a new parameter, not sure why I did it and what I was thinking. Can you check the latest build if it works for you?

**Comment by stoermelder** [comment]
Ok, this was a real mess. I remembered why I did it this way but there was no hope for the existing code, I've rewritten the how logic of the module. You can't use IN and INC/DEC the same time anymore but it should work now as expected.

**Comment by gazzar** [comment]
I just tested the nightly build and I'd say it is fixed now :) I think I hammered it fairly hard on various types of controls and I couldn't fault it. Let me know if there is anything else specific you want me to try. Thanks for fixing this; I think it's really nice and feels robust now!
