### ISSUE TITLE
GRIP

### ISSUE THREAD

**Issue by vcvrackideas** [stoermelder/vcvrack-packone#107]
Hi Ben! Hope you're doing well. 
I very like the option in your mapping modules that's called "lock parameters". I decided to try it to lock parameter that I don't want (or any user) to change anymore (to control only by external CV, for example for replicating synth in VCV or so). I was hoping CV PAM module could just work as a locker module for "mapped" knobs but it won't able to do that without cable connection and if we apply the cable parameter control by the cable so any initial values of knobs are resetted. So what do you think on implementing a new module based on midi mapping with CVPAM like UI that would be able just to lock chosen knobs?

**Comment by stoermelder** [comment]
Module added, feel free to test :-)

**Comment by vcvrackideas** [comment]
> Module added, feel free to test :-)

Oh Ben, that was FAST! And yeah, works even more than expected) I mean this tiny panel is a pretty nice for the really big patches that need this module for sure, I like red mapping squares as well. Great job! looking forward for library release

**Comment by stoermelder** [comment]
Thanks Artem :-)
