### ISSUE TITLE
PILE: OUT stays high while RESET is high

### ISSUE THREAD

**Issue by ROGAVKA** [stoermelder/vcvrack-packone#109]
I just noticed that the output of PILE stays high as long as RESET input gate is high.
Is it intended behaviour? It messes my patch a bit with manual resets I do from my controller.

**Comment by stoermelder** [comment]
RESET was actually intended to reset to the port's input voltage. Say, if want to set the current voltage to 5V and increment or decrement from there you trigger RESET with 5V. I guess this behavior makes it kind of hard to reset to 0V...

**Comment by ROGAVKA** [comment]
Are you sure it works as intended then? If i send 5V trigger to RESET then in the end (when trigger comes back to zero) I end up with 0 on OUT. So, to reset a module to 5V one has to send 5V **constant** voltage to RESET... seems kinda counter-intuitive

**Comment by stoermelder** [comment]
Yes, I am sure but I agree with you that it is not very intuitive. I guess I add an alternative mode for the RESET port?

**Comment by ROGAVKA** [comment]
Sounds cool :) Just throwing an idea here, but what about adding also an OFFSET knob, so one can easily dial in specific reset value? It seems that PILE has some free space...

Also not to spawn request issues on the same module, have you considered adding polyphony to PILE? I use 16 instances today with same settings feeding from 16 knobs of my beatstep... And if I need another channel then it's 16 more :)

**Comment by stoermelder** [comment]
I added POLY-PILE an few minutes ago. There would have been be too many corner-cases to handle if adding polyphony to the existing module, so a new module it is.

**Comment by ROGAVKA** [comment]
Wow, that's awesome, thanks a lot!
