### ISSUE TITLE
GLUE

### ISSUE THREAD

**Issue by stoermelder** [stoermelder/vcvrack-packone#111]

**Comment by vcvrackideas** [comment]
Thanks Ben, this is AWESOME. I have some another suggestions though) What do you think on DUPLICATE option near the DELETE function in the right click on the module or on the each already added label? So when Duplicate is pushed Label switch would be automatically on and then user gonna select a new module to copy selected label and then apply to it with the same parameters and color as well, or it maybe called copy paste function, whatever.
Could you add a default wide function in Label appearance menu in the main module? Of course if it's possible. 
Also the switches work now as not expected, so Label is on when = 1 (up), and it's ok but Lock works when = 0 (or down), and it's look like not ok.

**Comment by vcvrackideas** [comment]
> _No description provided._

Thanks for implementing duplicate feature Ben! However it doesn't copy an opacity settings (but not a big deal). Could you also do an automatic highlighting a label text in right click menu on the label itself? it can improve the speed of editing labels (also not a big deal, but just handy, I've seen it in new Submarine TD-410 text tool).
EDIT: sorry Ben didn't noticed it at the first time. Duplicate is duplucating now only color and rotation attributes but not the text. Tested on the blank panel from count modula and on plaits as well

**Comment by stoermelder** [comment]
> Duplicate is duplucating now only color and rotation attributes but not the text.

Do you think this makes sense? It is just one line to be added but wouldn't you edit the text of the duplicated label anyway?

**Comment by vcvrackideas** [comment]
> > Duplicate is duplucating now only color and rotation attributes but not the text.
> 
> Do you think this makes sense? It is just one line to be added but wouldn't you edit the text of the duplicated label anyway?

So now it doesn't make any sense because you've just added a short name of the modules when created, and this is nice and don't need to duplicate text anymore, thanks!
And thanks for the CTRL+A! a huge timesaver
EDIT: btw Ctrl + A is only starting working when I added the first label by the previous standart operation. and then continue to work even I delete all the labels. 
And thanks for the highlighting the text on a label!

**Comment by stoermelder** [comment]
Actually I didn’t add a short name, I added shortening the text to the label width. If the label is big enough the full text is shown as before.

Ctrl+A is only handled if GLUE is unlocked which automatically happens if you add a lab using the switch. The reason for that is you can have multiple GLUE modules and you don’t want them all to add a label on Ctrl+A.

**Comment by Telerex** [comment]
Loving Glue, the implementation is great.
Is there any chance of getting more colours in Glue or at least a black and white mode?

**Comment by stoermelder** [comment]
> Loving Glue, the implementation is great.
> Is there any chance of getting more colours in Glue or at least a black and white mode?

Did you notice there is a input field for a custom color as hexstring?

**Comment by Telerex** [comment]
I thought that was for display purposes only, as I can't seem to enter a string in that part of the apperance section. I know that that this is a pre-release version of Glue and that I should have given you more to fully implement it's features, but didn't want to miss out on such an important thing. Again, great module (as are all your others).

**Comment by stoermelder** [comment]
There was indeed a problem with this input-field which has been fixed about a week ago. Did you try the latest build?

**Comment by Telerex** [comment]
Will do. Thanks.
