### ISSUE TITLE
8Face crashes when paired with midi-map

### ISSUE THREAD

**Issue by Gbary1974** [stoermelder/vcvrack-packone#114]
Had an issue trying to use 8Face to expand the functionality of midi-map. I have used midi map to map a launch control and then saved to step 1 of 8face. I've then remapped the launch control and saved this to step 2 on 8Face. When switching between them it seems I can switch from 1 to 2 fine but switching back causes rack to crash. I've attached a log txt.
[log.txt](https://github.com/stoermelder/vcvrack-packone/files/4486586/log.txt)

**Comment by stoermelder** [comment]
Most probably it is caused by the MIDI driver. I suggest you use one of the MULTI-MAP modules from 23volts which were developed exactly for this use-case.

**Comment by Gbary1974** [comment]
Thanks for responding Ben, yes 23volts has exactly that thanks and works a treat. And don't worry I still have plenty of uses for 8Face.
