### ISSUE TITLE
GLUE - support for labels inside STRIP

### ISSUE THREAD

**Issue by vcvrackideas** [stoermelder/vcvrack-packone#115]
Hope you can fix it...because otherwise nice dreams about good labeled STRIPS might be fall) Sure, I've included GLUE instance inside a strip but nothing happened. Tested two times with different strips but no effect.

**Comment by stoermelder** [comment]
Known issue. May be fixed at a later point as it needs ugly hacking JSON data.

**Comment by stoermelder** [comment]
Now available, will be included in v1.7.
