### ISSUE TITLE
MIDI-STEP - broken poly mode

### ISSUE THREAD

**Issue by submitaudio** [stoermelder/vcvrack-packone#119]
Midi step polymode: (V 162 beef 3a)
Thanks again for your nice updates. I have installed the latest Beta version.
I wanted to use Poly mode in midi step module (16 knobs) but there are only 8x2 conections in the module, how can i get 16x2 (inc/dec/) Or will you place a poly conection?
At this moment i have conected like this:

![image](https://user-images.githubusercontent.com/6167892/80317417-fa123c80-8803-11ea-96a8-2c6f93733b85.png)

**Comment by stoermelder** [comment]
If you switch to poly-mode all 16 channels are send on the first ports of INC and DEC. This way you only need one poly-cable to POLY-PILE. Let me know if it works for you.

**Comment by submitaudio** [comment]
I tried, but no poly cable...

![image](https://user-images.githubusercontent.com/6167892/80322011-25a41f80-8822-11ea-9d45-3260e54c9e94.png)

**Comment by submitaudio** [comment]
Take a look at my new build template (with 10 midi channels and 120 signed knobs and buttons ;)

[Mutable-instruments-template-V2.zip](https://github.com/stoermelder/vcvrack-packone/files/4536650/Mutable-instruments-template-V2.zip)

**Comment by stoermelder** [comment]
> I tried, but no poly cable...
> 
> ![image](https://user-images.githubusercontent.com/6167892/80322011-25a41f80-8822-11ea-9d45-3260e54c9e94.png)

You're right, please try the latest build, it is fixed now.

**Comment by submitaudio** [comment]
Thank you for you hard work! On my (pc) laptop it's working perfect now! 

Yesterday i build a large template file on my laptop (pc) and this morning i want to open the same file on the Mac, but i got a crash on startup. I installed exactly the same nighty build version on both systems... i have zipped the log and template file.

[S67-VCV-log.zip](https://github.com/stoermelder/vcvrack-packone/files/4550544/S67-VCV-log.zip)

And again, i am so happy with this build ;) VCV is almost like hardware for me! when i will release my new album i will place a comment for your hard work!!! Because working with a mouse or touch screen is not my way to create music and also thanks for this nice new Glue module.

**Comment by stoermelder** [comment]
Oh wow, there are a lot of my modules :-)
I had to rewrite how GLUE and GOTO store their settings which caused this problem. Thank you for reporting, it is fixed now in the latest build.

**Comment by submitaudio** [comment]
> Oh wow, where are a lot of my modules :-)
> I had to rewrite how GLUE and GOTO store their settings which caused this problem. Thank you for reporting, it is fixed now in the latest build.

Woow you are faster then light ;) It's working on both systems... And yes i have mapped about 160 knobs and buttons... I am so happy ;) I have build a fixed template and now i can create the real music!
ps. also nice that the Glue module have the function hide ;)
