### ISSUE TITLE
8FACE - ignore empty slots when using "trigger forward" to cycle

### ISSUE THREAD

**Issue by MaZe6K** [stoermelder/vcvrack-packone#120]
Hello!

If possible, I think it would be a good idea to ignore empty slots when using a trigger to cycle through the saved presets in 8FACE, so that when you have only 3 presets saved for example, it skips back to preset 1 when receiving a trigger while on preset 3.

**Comment by stoermelder** [comment]
I implemented it this way so someone can change presets on beat 5 an 7 but nothing happens on the other beats.
How about a „Clean up“ function on the context menu which removes empty slots and moves everything „to the top“?

**Comment by MaZe6K** [comment]
I think I would prefer to have an option to ignore empty slots in the right click menu, or maybe an option to set the sequence length?
I didn't think about using it with empty slots on purpose like you mentioned, it makes sense too, but  might be a little more complicated to manage, since you can not delete slots.
Of course you can also use the reset as a workaround, so it's not crucial to the functionality in any way and only a suggestion.

**Comment by stoermelder** [comment]
You can set the sequence length by long-pressing one of the buttons. Also, you can reset slots by long-pressing in write-mode.

**Comment by MaZe6K** [comment]
oooh... sorry for not reading the manual.
That's amazing! :)
So then this thing is pretty much perfect as it is, sorry for bothering.
