### ISSUE TITLE
ROTOR mod A - output channel offset

### ISSUE THREAD

**Issue by Eurikon** [stoermelder/vcvrack-packone#121]
Hi Ben, 

would it be possible to have a user selectable range for the output channels.
So that it would be possible to set a number of channels between A & B 
ie: 3,4,5,6 or 9,10,11,12,13 
etc.

hope that makes sense.
Cheers,
Latif

**Comment by stoermelder** [comment]
Hi Latif, you mean an offset for the first channel used?

**Comment by Eurikon** [comment]
Hi Ben, 
yes i guess you are right, an offset for the first channel please :)

**Comment by stoermelder** [comment]
At first I thought this should be a good idea but now I’m not to sure anymore. Can you describe your use-case for this?

**Comment by Eurikon** [comment]
![rotor](https://user-images.githubusercontent.com/40998416/80819958-4d0a3c00-8bd6-11ea-8150-216d23ecfacb.png)

For example in this use-case i would like to send the random triggers that Rotor is receiving from the switch module.
To channel 4 - 8 while they are being rotated by Rotor over outputs 4 - 8, through one poly cable.
So that to control the mutes for Mindmeld channel 4 - 8.

**Comment by stoermelder** [comment]
Ah, its about the output (and not the Input), that makes sense.

**Comment by Eurikon** [comment]
Yes, the output :)
So my answer should be: an offset for the first channel of the output.
Maybe a small knob under the big channel knob, or a ring around the channel knob.

Thanks!

**Comment by stoermelder** [comment]
Added in the latest build.

**Comment by Eurikon** [comment]
Hi Ben, i just tried it. 
I am getting a different result with the offset then what i was expecting. 

Instead of moving the group of channels that is set with the output rotary, the offset is adding channels at the end. 
So it appears more like it is offsetting the last channel.

The desired behavior should be:
when channels: 1,2,3,4 are set with the output rotary knob, 
the offset knob should move the 4 channels as a whole. so that by turning the knob to the right i then can move these 4 channels to 5,6,7,8

**Comment by stoermelder** [comment]
Hm, I can't reproduce what you are describing, actually it works that way?
![r](https://user-images.githubusercontent.com/47640667/80891250-178f4c80-8cc3-11ea-8680-32f96ea6441d.gif)

**Comment by Eurikon** [comment]
Ah excuse me, i have not checked the actual output.
I made my assumption based on the led lights that stayed on.

sorry for that!

But then still (based on the led lights) when turning the offset further to the right, it will light up even more leds, which is kind of confusing?

**Comment by Eurikon** [comment]
Oh wait, this is a problem that is inherent to how the code works for those underlying channels.
i remember seeing a situation like this before in some other modules i was testing at the time for Marc & Steve.

It is something that can not be changed right?

(the offset feature is working well btw. just testing it now with actual output connected, thanks for that!)

**Comment by stoermelder** [comment]
No problem. I could change how the led show the channels but the wouldn't represent the acutal cable. It is not possible in Rack to use only channels 5-8 in a cable, you can only set the number of used channels, so it's always channel 1...maximum.

**Comment by Eurikon** [comment]
Right, i remember now. 

It might confuse some other users as well down the road.
But i do remember now why this is.

Thanks Ben!

**Comment by stoermelder** [comment]
Maybe I can do something with colors to indicate that some channels aren't active.

**Comment by Eurikon** [comment]
Perfect! :)
