### ISSUE TITLE
MIDI-CAT total recall on opening the patch.

### ISSUE THREAD

**Issue by nnbveh** [stoermelder/vcvrack-packone#123]
I'm using MIDI-CAT with touchOSC controller app through touchOSC bridge. The combo works perfectly(so far at least), and i'm getting two-way communication.
The problem is, when i start both Rack and touchOSC and open a patch, the values set for all the mapped parameters in vcv rack are not being send to the touchOSC. There's a simple workaround i've found: i just initialize MIDI-CAT from the context menu, and then undo it - voilà! all the knobs and faders in touchOSC now have the same values as my patch...
Since it is technically possible, could it be implemented in the module itself? So when we open a patch which has MIDI-CAT in it mapped already to some parameters it would send all the values to the external midi device(in this case touchOSC).

**Comment by stoermelder** [comment]
I guess this is a problem on touchOSC-side as it works with hardware MIDI controllers exactly this way. 
@vcvrackideas you use touchOSC most of the time, does this work for you?

**Comment by nnbveh** [comment]
I see. i've tried it more and it works if i start touchOSC first, leave the config menu, and THEN open the patch. I guess there's nothing to do here but to remember to open both in the right order. Although it would be great to have an option to be able to send all the values manually...Thanks for the fast response! I'll contact the developer of the app and ask him if there's a way to improve this.

**Comment by vcvrackideas** [comment]
> I'm using MIDI-CAT with touchOSC controller app through touchOSC bridge. The combo works perfectly(so far at least), and i'm getting two-way communication.
> The problem is, when i start both Rack and touchOSC and open a patch, the values set for all the mapped parameters in vcv rack are not being send to the touchOSC. There's a simple workaround i've found: i just initialize MIDI-CAT from the context menu, and then undo it - voilà! all the knobs and faders in touchOSC now have the same values as my patch...
> Since it is technically possible, could it be implemented in the module itself? So when we open a patch which has MIDI-CAT in it mapped already to some parameters it would send all the values to the external midi device(in this case touchOSC).

Just open touchosc layout first, all knobs down, run touchosc bridge if you use it and only then, at last run VCV Rack patch which was been already mapped to this layout. Profit!) This is because MIDI-CAT send midi feedback when it's opening

**Comment by nnbveh** [comment]
> > I'm using MIDI-CAT with touchOSC controller app through touchOSC bridge. The combo works perfectly(so far at least), and i'm getting two-way communication.
> > The problem is, when i start both Rack and touchOSC and open a patch, the values set for all the mapped parameters in vcv rack are not being send to the touchOSC. There's a simple workaround i've found: i just initialize MIDI-CAT from the context menu, and then undo it - voilà! all the knobs and faders in touchOSC now have the same values as my patch...
> > Since it is technically possible, could it be implemented in the module itself? So when we open a patch which has MIDI-CAT in it mapped already to some parameters it would send all the values to the external midi device(in this case touchOSC).
> 
> Just open touchosc layout first, all knobs down, run touchosc bridge if you use it and only then, at last run VCV Rack patch which was been already mapped to this layout. Profit!) This is because MIDI-CAT send midi feedback when it's opening

I've just replied with exactly this...Would be great to be able to send it manually any time though. OH, i saw an option to import a midi map preset, but i don't see a way to export it, how does one save them?

Thanks!

**Comment by stoermelder** [comment]
I just added a context menu option for that. I did not test it but it should work as expected.

> OH, i saw an option to import a midi map preset, but i don't see a way to export it, how does one save them?

You can't. I don't see any use for exporting presets to MIDI-MAP. Why do you want that?

**Comment by nnbveh** [comment]
Cool. Thanks!

> You can't. I don't see any use for exporting presets to MIDI-MAP. Why do you want that?
Dunno, why is there import? I thought it was so we could load pre-mapped configs no? I was basically just wondering why there's this option at all, without having a real need for it yet, sorry)

**Comment by stoermelder** [comment]
Maybe you misread something. The import function is for VCV MIDI-MAP in case you have set up all your mappings in the stock module and you want replace it with my module.  
Presets can be saved and opened in the "Preset" submenu but presets make not really sense for MIDI-CAT as mappings are specific for a set of modules which won't reappear in any other patch.

**Comment by nnbveh** [comment]
Now i get it, thanks. I thought it was some sort of mapping presets specific to this module...
