### ISSUE TITLE
Can Strip exclude paramaters for entire modules?

### ISSUE THREAD

**Issue by ghost** [stoermelder/vcvrack-packone#124]
I would like to save a set of modules as a preset but I want to use the random feature and exclude modifying certain modules (all parameters always). Is there a way to do that?

**Comment by stoermelder** [comment]
Yes, it is described in the manual.
https://github.com/stoermelder/vcvrack-packone/blob/v1/docs/Strip.md#on-off-rand

**Comment by ghost** [comment]
It says parameters can be excluded, but how about the entire module?

**Comment by stoermelder** [comment]
You can’t. You can exclude all parameters or you can just break up the strip which keeps your module from randomizing.  
I don’t think it worth adding anything new for this rare use-case.
