### ISSUE TITLE
STROKE

### ISSUE THREAD

**Issue by vcvrackideas** [stoermelder/vcvrack-packone#125]
Hi Ben! Stroke is awesome and problem solver, thanks so much! 
I found sometimes in gate mode some hotkeys are frozen the gate output. BUT it made some ideas for me and here is my suggestion - what about toggle hotkey mode for gate output? So in that mode we could for example apply ON state for output voltage and then disable it by pressing that hotkey again. Maybe useful for simple toggle automation. 
Also could you add 10volts out mode? Thanks again! I'm so happy with that. VCV Rack becomes closer to any user because of your modules!)

**Comment by stoermelder** [comment]
Thanks, Artem, for your suggestions!

**Comment by vcvrackideas** [comment]
> Thanks, Artem, for your suggestions!

Thanks Ben it works awesome now! Tested with 1-8 keys and mindmeld mixer (GATE high low option) and stroke saves this state after rack reload. Very handy if user don't want to mess with midi controller and want to just setup main template with fast access like in Ableton, so gooood!
