### ISSUE TITLE
Glue/Strip interaction

### ISSUE THREAD

**Issue by ShofB** [stoermelder/vcvrack-packone#128]
I saved a strip collection which included some labels on one module (both of these are GREAT BTW).  When I used Strip to load in the saved preset none of the labels showed.  I did save Glue with the preset.

**Comment by stoermelder** [comment]
Thank you for the request. This feature has been implemented a few days ago and will be available in the next update.
You can use the most recent build if you want it right away.
https://github.com/stoermelder/vcvrack-packone/releases/tag/Nightly

**Comment by stoermelder** [comment]
#115

**Comment by ShofB** [comment]
It still doesn't work for me.  I installed the new version, saved a new preset, loaded it in and the labels did not show.  I am running the latest version of Rack on W10.
________________________________

**Comment by stoermelder** [comment]
Did you include GLUE in the strip? If yes, please provide the vcvss file for further investigation.
