### ISSUE TITLE
MIDI-CAT forgets MIDI Driver assignments when loading a patch

### ISSUE THREAD

**Issue by Chaircrusher** [stoermelder/vcvrack-packone#129]
I use MIDI-CAT to set up performance controls for Rack patches from my midi controllers.

If I save the patch and exit, the next time I run Rack and load the patch, the MIDI device assignment is no longer set.

And actually I just tried exactly that and it DID remember the MIDI device assignment. So I'm not sure what's going on

**Comment by vcvrackideas** [comment]
> I use MIDI-CAT to set up performance controls for Rack patches from my midi controllers.
> 
> If I save the patch and exit, the next time I run Rack and load the patch, the MIDI device assignment is no longer set.
> 
> And actually I just tried exactly that and it DID remember the MIDI device assignment. So I'm not sure what's going on

Hi Kent. Are you using windows? Windows do a strange things with midi drivers at all. For example I use TouchOsc bridge driver. And on PC #1 it can be TouchOSC #2 driver and on another PC TouchOSC #3 driver. And tomorrow it can be TouchOSC #1 or TouchOSC #4 driver. :-) So I can't figure out how to manage this...

**Comment by stoermelder** [comment]
Thanks for reporting, I noticed the same behavior but as I just use Rack‘s MIDI API the issue is not specific to my module, it happens on all MIDI modules.
I think, it has something to do when connecting a MIDI device while Rack is running (forgets assignment) and connecting the device before starting Rack (remembers assignment).

**Comment by stoermelder** [comment]
https://github.com/VCVRack/Rack/issues/1661

**Comment by Chaircrusher** [comment]
Thanks for your quick reply.  Consider this bug report a "Fix this if you can fix this" issue ;-)
It sounds like the real solution would be to have some intelligence in the code for connecting modules with devices that tries to match up devices intelligently based on names.  Probably not high on Andrew's 'to do' list.

**Comment by stoermelder** [comment]
https://github.com/thestk/rtmidi/issues/116
Seems to be caused by RtMidi which is used by Rack for MIDI...
