### ISSUE TITLE
MIDI-CAT option to send note on velocity = 0 as feedback for note off

### ISSUE THREAD

**Issue by curlymorphic** [stoermelder/vcvrack-packone#130]
Excellent module, it has enabled me to build a 16 step drum sequencer, using two Akai apc mini's and the dk drum sequencer module.  

One possible feature request would be the option to send midi note on, with a velocity of zero, instead of note off when sending midi feedback, as this is what some controllers (Akai) require for setting the lights.

I have included a diff to indicate the edit I have made, however, I am aware the change would be a lot more involved, to make optional, and saving settings and other aspects I have not considered.

This is just a suggestion, that may be of use of other users.

```
+++ b/src/MidiCat.cpp
@@ -47,7 +47,7 @@ struct MidiCatOutput : midi::Output {
                else if (vel == 0 && lastGates[note]) {
                        // Note off
                        midi::Message m;
-                       m.setStatus(0x8);
+                       m.setStatus(0x9);
                        m.setNote(note);
                        m.setValue(0);
                        sendMessage(m);
```

**Comment by stoermelder** [comment]
Thanks, I will look into it.

**Comment by hexdump0815** [comment]
as @stoermelder had been pointing out in his response to https://community.vcvrack.com/t/stoermelders-packone-v1-6/9456/75 this issue here seems to cover nearly exactly the same topic - maybe i should have been checking the github issues before posting at the community ... @curlymorphic maybe have a look at my posting and the suggestion i do there as we only have to do this for the toggle off events i think which would make the code change a bit more complex, but maybe you know the code well enough already to write a diff for that suggestion too (sadly i'm no c++ programmer)?

**Comment by curlymorphic** [comment]
@hexdump  I think your suggestions are really good, and I myself would use such a feature, However for me to implement such features would probably require as much effort from @stoermelder to oversee as it would take to implement themself.  I feel the best course of action may be patience. 

I do have a small collection of 8x8 grid-based controllers, so would be very happy to test, or generally help in any way, when the time comes.

**Comment by hexdump0815** [comment]
@stoermelder i looked a bit at the code (which is very nice to read btw.)  and as a result i played around a bit with the above change from @curlymorphic and it makes the toggle button feedback quite useable on akai controllers - might it be an option to at least include an option like "toggle (akai)" next to toggle option for the mode which implements that change? that should be very easy to implement and would make buttons on akai controllers quite a bit more useful until we have something better in place ...

**Comment by stoermelder** [comment]
Thanks. I have to think through what adding this option would mean, I didn't work on this module for quite some time.

**Comment by stoermelder** [comment]
I finally took the time and added this option on the mapping slots (when mapped to a note). Please let me know if it works for you.

**Comment by curlymorphic** [comment]
Thank you, Ben.  I can confirm this is working for me on both APC mini and Launchpad mk3 mini.

Thank you.

**Comment by hexdump0815** [comment]
cool - thx a lot - will test it soon ... btw. looks like there is more interesting controller specific stuff in the pipeline: https://community.vcvrack.com/t/studio-6-1-trigger-sequencer-for-midi-controllers-prerelease/10675 :)

**Comment by stoermelder** [comment]
I’ve seen this one but I’m not so sure about the concept. If I find a week of spare time I will implement a module for Rack like this one for Reaktor and Maschine Jam:
https://youtu.be/WCRWFOSNSvg

**Comment by curlymorphic** [comment]
The Second sequencer in the linked video, NOD-E looks cool concept, and visually appealing and would be an excellent addition to vcv. The first one in the video looks very similar in concept  to the one I am developing,

**Comment by stoermelder** [comment]
Good to know, I have to take a closer look!

**Comment by hexdump0815** [comment]
i finally checked your changes for  'Midi-Cat - added option for "note on, vel 0" on note off' and can confirm that it works perfectly well for me too ... thanks a lot once more ...
