### ISSUE TITLE
Spin - middle click output to switch fine state on SAIL

### ISSUE THREAD

**Issue by vcvrackideas** [stoermelder/vcvrack-packone#132]
I think it would be useful to switch SAIL a bit faster with using middle click power to achieve FINE control (or other function as it would be an output in SPIN module itself). I don't know if middle click allows to use toggle on\off or just a push momentary state so it's just an idea.

**Comment by vcvrackideas** [comment]
By the way I achieve that with remapping software on windows that's called KeyMapper ;-) So now for example side button can drag the rack around xy position while holding and middle click can switch fine or rough control of the Sail, just if you're curious on it

**Comment by stoermelder** [comment]
I think adding a middle click output makes much sense on SPIN. 
I've added support for mouse buttons 4,5,6... to STROKE some time ago but middle click support fits better on SPIN.

**Comment by vcvrackideas** [comment]
> I think adding a middle click output makes much sense on SPIN.
> I've added support for mouse buttons 4,5,6... to STROKE some time ago but middle click support fits better on SPIN.

Thanks Ben! In this commit I see the middle click output and many modes are nice but it's a bit of alarm - the output generates just nothing) I'm on windows 10 if it matters. Also dark panel as default still doesn't work with Sail. Cheers and thanks for implementing! This kind of precision interpretation of midi controller just inside mouse wheel is incredible. Awesome use for laptop for sure.

**Comment by stoermelder** [comment]
Can you try learning in STROKE with you mouse button? I suspect it is not interpreted as „middle button“. Mouse buttons are counted as 0,1,2,3 with 0 = left, 1 = right, 2 = middle and 3 or above are additional buttons if your mouse has them.

**Comment by vcvrackideas** [comment]
> Can you try learning in STROKE with you mouse button? I suspect it is not interpreted as „middle button“. Mouse buttons are counted as 0,1,2,3 with 0 = left, 1 = right, 2 = middle and 3 or above are additional buttons if your mouse has them.

No, only MB4 and MB5 can be learned. I tried to enable or disable Redragon control app for the mouse but no changes. And middle click scrolling is still working inside the Rack.

**Comment by stoermelder** [comment]
Ok, this is strange. SPIN captures the middle click and scrolling should not possible anymore. It’s working here as expected. Not sure what’s going on right now.

**Comment by stoermelder** [comment]
Any chance you have more than one instance in your patch? Mouse clicks will only be captured by one instance...
I think I should make this module work only with one instance.

**Comment by vcvrackideas** [comment]
> Any chance you have more than one instance in your patch? Mouse clicks will only be captured by one instance...
> I think I should make this module work only with one instance.

Yeah sorry there was an instance in my template but...no changes sadly. I even tried to use windows options to deactivates laptop's sensor panel when external usb mouse is connected but no work. Ok maybe I should try reboot then...
EDIT - still no luck...that's really strange

**Comment by stoermelder** [comment]
Strange indeed. Can you try it with an empty patch? If this doesn’t help I have to send you a custom build with some additional debugging output.

**Comment by vcvrackideas** [comment]
> Strange indeed. Can you try it with an empty patch? If this doesn’t help I have to send you a custom build with some additional debugging output.

![spiin](https://user-images.githubusercontent.com/42435368/89763740-cbdb1300-dafb-11ea-985e-7211c94b543f.gif)
As you can see here no luck. So would be glad to test with additional build

**Comment by stoermelder** [comment]
You are not holding any modifiers like Shift, Alt or Crtl? I fixed a small bug on this, I hope this is the problem.

**Comment by vcvrackideas** [comment]
> You are not holding any modifiers like Shift, Alt or Crtl? I fixed a small bug on this, I hope this is the problem.

thanks it's working now! No I didn't hold any modifiers btw. As I can understand there is no way to leave middle click and scrolling on its place together with the spin now? let's say activate middle click only when hovering on parameter? If no there is a way to disable middle click in the spin? I mean there is already in muscle memory of some users (probably including of myself) and I think there is no way to remapping it to another mouse button with 3rd party software as well because there is only a way to use XY scrolling is middle click and scrolling in VCV.

**Comment by stoermelder** [comment]
Yes, I thought about that too and I think it’s too aggressive at the moment. I will change this behavior later.
I will also add options to grab the events only with Shift or Crtl or Alt.
