### ISSUE TITLE
GLUE - label text colour options

### ISSUE THREAD

**Issue by Telerex** [stoermelder/vcvrack-packone#136]
One of the great things I have started doing with Glue is using the hex input to match the colour of the label with the module. Would it be possible to be able to change the colour of the text in the same way, or at least have a white option if that is easier.
On a side note. Is there an upper limit to how many labels Glue can handle? I have already done 145 labels in one patch with no problems, which I think is fantastic. I must hold the record for labels per patch.

Thanks.

**Comment by stoermelder** [comment]
Yes, I can add options for text coloring.
No, there is no upper limit on software side, you can add as many labels as you want. The only limit is your hardware.
