### ISSUE TITLE
CV-MAP - ignore mousewheel scroll

### ISSUE THREAD

**Issue by unlessgames** [stoermelder/vcvrack-packone#137]
I've been using CV-MAP a lot lately and came across one mildly inconvenient thing about it.

It hijacks the scrollwheel when the mouse gets on top of while scrolling around the rack. Not sure how to solve this, maybe only react to scroll events if the mouse has moved since focusing the module? Or an option to disable scroll wheel input and only allow scrolling with the scrollbar?

Thank you for these modules anyway, they're immensely useful!

**Comment by stoermelder** [comment]
To be fair: VCV's MIDI-MAP behaves the same way :-)
I added that scroll events don't get "captured" when the mapping slots are locked by the context menu option. I hope this helps.
This change applies to CV-MAP, CV-PAM and MIDI-CAT as they share the same mapping slots control.

**Comment by unlessgames** [comment]
true, maybe I'll file the same issue for MIDI-MAP :d

this soultion does help, thanks!
