### ISSUE TITLE
Stroke's Zoom out amount slider

### ISSUE THREAD

**Issue by vcvrackideas** [stoermelder/vcvrack-packone#138]
Hi Ben! Zoom out is nice. There is one suggestion I have - could it has a slider control to define amount of zooming out? Sometimes it's not need to make full zoom out for example (especially for big patches on a laptop) just for 50% or so. Cheers!

**Comment by stoermelder** [comment]
Thanks for the suggestion. I added an additional command which centers a module on 1/3 of the screen. I’m not sure how this could be handled with „zoom out“...

**Comment by stoermelder** [comment]
I've added an option for absolute zoom level in the meantime.
