### ISSUE TITLE
Stroke Zoom out \ Zoom to module smooth transition option

### ISSUE THREAD

**Issue by vcvrackideas** [stoermelder/vcvrack-packone#139]
...as in GOTO. Is it possible in theory? I found that using Zoom's slider for a bit slower zoom changings preventing in 90% of cases those vector glitches that may come from fast zoom switching. Again it maybe so complicated for this small module so still just an idea ;-)

**Comment by stoermelder** [comment]
Hi Artem. This one needed some internal rework but finally a view new commands are available.

**Comment by Petervos2018** [comment]
Hi Ben after this update zoom toggle does not work any more, it zooms in but not out.

**Comment by stoermelder** [comment]
Peter, I'm afraid I can't reproduce it. Anything special I need to do?

**Comment by Petervos2018** [comment]
Sorry just downloaded the latest nightly 0e79300 and all is well again, don't know what happened.

Thanks

**Comment by vcvrackideas** [comment]
Thanks Ben! Really nice movements and no GUI glitches. If you can do that also with Zoom toggle (which is my favorite one command) - would be awesome

**Comment by stoermelder** [comment]
Added.
