### ISSUE TITLE
CV-MAP - Parameter changes (unlocked) feedback

### ISSUE THREAD

**Issue by nnbveh** [stoermelder/vcvrack-packone#140]
It would be great if, similarly to the MIDI-CAT module, CV-MAP would send a feedback when a parameter on a controlled module is changed manually...

As a workaround using CV-PAM simultaneously with CV-MAP would do the trick, but it's not as elegant, and i guess there would be some sort of feedback loop in that case, that's why these two are not able to be mapped to the same parameter, or am i wrong?

**Comment by stoermelder** [comment]
This won't happen on CV-MAP as any kind of "feedback" would need output ports which CV-MAP obviously does not have. Also, Rack does allow every parameter mapped by only one module.
I'm not sure how useful such a functionality would be. Can you describe your use-case?

**Comment by stoermelder** [comment]
I'll reopen if you can describe your use-case.
