### ISSUE TITLE
Sockets not rendering properly on some modules when lights off engaged

### ISSUE THREAD

**Issue by ContemporaryInsanity** [stoermelder/vcvrack-packone#143]
MAZE, INFIX & uINFIX render as follows with lights off engaged:

![image](https://user-images.githubusercontent.com/12547379/87068493-8c27bf80-c20d-11ea-822b-4dc6fd9bef3c.png)

**Comment by stoermelder** [comment]
Thanks for reporting. Being the author of the Lights Off module I did know there would be some problems... 🙂
