### ISSUE TITLE
8FACE - Option for affecting slots while in Record state

### ISSUE THREAD

**Issue by vcvrackideas** [stoermelder/vcvrack-packone#144]
Hi Ben! I found it's sometimes useful for 8face and big big arrangement to not exit from record mode but still receiving selection data from SLOT port. So I think that option in right click menu that would allow to affect or not switching scenes via slot CV in recording mode would pretty useful. Cheers!

**Comment by stoermelder** [comment]
Will added in a future "8FACE mk2".

**Comment by stoermelder** [comment]
Added in 8FACE mk2.
