### ISSUE TITLE
TRANSIT - bind parameter hotkey

### ISSUE THREAD

**Issue by vcvrackideas** [stoermelder/vcvrack-packone#148]
Hi Ben! Firstly - thank you so much for this gamechanger beast! Secondly - could you add some shorcut for Bind Parameter command while hovering on the module? Something like...SHIFT+A or for your taste. Cheers!

**Comment by stoermelder** [comment]
Thanks Artem for the suggestion. I added hotkeys and an option which allows binding multiple parameters in a row.
