### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by stoermelder** [stoermelder/vcvrack-packone#15]

**Comment by Eurikon** [comment]
Yes please! 
I already use it here, in my own edited svg, 
but will be great if you make it built-in just as Submarine did? :) 

![stoermelder-dark](https://user-images.githubusercontent.com/40998416/60775494-1ed9de00-a124-11e9-83c4-3c496c8560fe.jpg)

cheers!

**Comment by stoermelder** [comment]
Currently all module panels are cleaned up to follow a common theme across all three plugins. Additionally a dark theme will be added in the next version 1.3.0.

**Comment by stoermelder** [comment]
Completed. Panel design might not be final but works for now.
