### ISSUE TITLE
TRANSIT - interference of same named parameters bug

### ISSUE THREAD

**Issue by vcvrackideas** [stoermelder/vcvrack-packone#150]
Hi Ben! I possibly found a bug. The thing is to try bind for example bind two cutoff knobs of the same module two instances (I tested with squinky labs stairway FC knobs) and try to save snapshots turning both knobs. Maybe it's due to expander use, I don't know yet, but some knob is starting dominating to the other and other may even freeze at the maximum value or of its premapped offset position.

**Comment by vcvrackideas** [comment]
Possibly I found a source of the issue. This is when suddenly click on the bind module instead bind of parameter. And then there is now way to cancel the operation and in the case user would start click on the bind parameter there will be some unbindings inside of the module but the previously mapped parameters will still show blue square but no one slots would not function anymore. So if that true there is one more reason to add a hotkey to bind parameter option :-) Cheers Ben!

**Comment by stoermelder** [comment]
Thanks Artem for reporting. I'm not convinced it is fixed with the latest commit as I noticed strange behavior in some situation, too.

**Comment by vcvrackideas** [comment]
Thanks Ben, works nice at the first glance. Will do a new patch tomorrow with extensive use of similar modules and so gonna test it more extensively. At least the old version patch works without any destruction too.

**Comment by stoermelder** [comment]
Please reply if this problem still persists, I will re-open this issue.

**Comment by Telerex** [comment]
I don't know if it is simply modules of the same name or not. In the example shown Poly Manual CV and Luci Control Freq always return a value of zero volts from any patch I save. On the other hand Unless Modules Towers returns what appear to be random values. Saving the same patch into more than one slot will return the same random values (so maybe they are not so random). This is with Nightly Build v1.8 d084bfa. 
![TYPHON VCV](https://user-images.githubusercontent.com/55559146/97403837-09765d80-18ed-11eb-87b4-a687e9280ea8.JPG)

**Comment by stoermelder** [comment]
Thanks for reporting. Please provide the patch file for further investigation.

**Comment by Telerex** [comment]
[TYPHON.zip](https://github.com/stoermelder/vcvrack-packone/files/5460690/TYPHON.zip)
It's a work in progress, but should still work.

**Comment by stoermelder** [comment]
There is an issue with parameters which are mapped after snapshots have been stored. As this has nothing to do with the initial bug I moved it to a new issue.
