### ISSUE TITLE
Midi-cat and Transit to work together 

### ISSUE THREAD

**Issue by libermanomer** [stoermelder/vcvrack-packone#152]
this is my first github comment.
hey ben,thanks for awesome modules
i’ve tried to use a 8 faders controller mapped to a mixer let’s say,with midi-cat to set the value for transit.
but you can’t use them two together,actually it’s make sense..

but maybe you have an idea how to do so? 

again just to be clear ,i want to move a fader, then click on transit.
![81D46681-18A4-4823-A794-F4C2FBC7FBBF](https://user-images.githubusercontent.com/62829941/88575773-0ac58f00-d04d-11ea-8f34-385b663d55fd.jpeg)

have a good day:-)

**Comment by vcvrackideas** [comment]
Hi. There is no way to do double mapping VCV Rack v1 unfortunately... So I have no idea how to do that. You can use 8face with midi mapping together but transit use a method of midi mapping too...

**Comment by libermanomer** [comment]
@vcvrackideas Thanks Artem,
i haven't thinking this way because i skip 8face video,shame on me!

so basically 8face does exactly what i want, transit it's a 8face with more features like envelope,gate,etc..

**Comment by vcvrackideas** [comment]
> @vcvrackideas Thanks Artem,
> i haven't thinking this way because i skip 8face video,shame on me!
> 
> so basically 8face does exactly what i want, transit it's a 8face with more features like envelope,gate,etc..

You will get audible clicks when using 8face with audio rate modules due to preset nature of it. But Transit is like mapper, like your computerized multi hands) so this is an issue of whole VCV Rack to not have double mapping features

**Comment by stoermelder** [comment]
> @vcvrackideas Thanks Artem,
> i haven't thinking this way because i skip 8face video,shame on me!
> 
> so basically 8face does exactly what i want, transit it's a 8face with more features like envelope,gate,etc..

8FACE does apply presets on modules, TRANSIT does apply parameter values. With presets been specific to each module there is no way to morph between them, while parameters are a standard in Rack and can be interpolated.

As Artem said there is no way in Rack to map one parameter to multiple modules. As soon another module grabs a mapped parameter the first mapping is lost.

That been said I could create a helper module which maps unto one parameter and provides multiple copies of it, for example four copies. It might be a bit of a „mapping-mess“ but it could work as long the different modules which are holding the mapping are not applying new values the same time.

**Comment by vcvrackideas** [comment]
Thanks Ben, the idea of helper module is really awesome, really curious how it would work on practice, so looking forward!

**Comment by libermanomer** [comment]
Ben,This is awesome!😅
![image](https://user-images.githubusercontent.com/62829941/89045355-10c0b600-d354-11ea-8890-b979576a87dd.jpeg)

now it's like a motorized mixer for Rack, when you can recall and write Without even touch the computer once, most important Strip file for now😁

Legend. you got me speechless 😶 thank you!

cheers,Omer

**Comment by stoermelder** [comment]
Thank you! Please notice I will be renaming the module to "X4" as it fits better, I think, but this will be a breaking change.
If you need assistance for repair of you patches or strip-files please let me know.

**Comment by libermanomer** [comment]
> Thank you! Please notice I will be renaming the module to "X4" as it fits better, I think, but this will be a breaking change.
> 
> If you need assistance for repair of you patches or strip-files please let me know.


Hey Ben, I've handled couple updates of nightly (I've reconfigured all nightly modules again) 

sometimes I don't update even you work like crazy fast with new great features every morning. 😬

Can you help me to avoid that?  

 Edit- may this is the cause?  Should I just change the version number each time? 
`      "id": 27,
      "plugin": "Stoermelder-P1",
      "version": "1.7.4ea2e2d",
      "model": "X4",
      "params": [
`

**Comment by stoermelder** [comment]
I'm afraid I can't follow. Do you have a problem with the name change of XX to X4? Or is it some other issue? Most of my updates shouldn't break existing patches. And no, the version number should ne issue.

**Comment by libermanomer** [comment]
I've updated now, that was the first time I didn't get a Rack "couldn't find .... modules " message,
so all work , anyway, thanks.

**Comment by stoermelder** [comment]
Ok. Let me know if you get this message again.
