### ISSUE TITLE
8FACE - copy and paste

### ISSUE THREAD

**Issue by ghost** [stoermelder/vcvrack-packone#154]
HI can we get a way to copy a step and paste to another?
also can we get the directional arrow right and left to work like strip where we just click it to change direction?  

Also can we get a way to when we click a step it goes to the values on the associated modules  so we can assign that to new steps. maybe a ctrl plus click or something?

This is Paramater locking YeS!!!!!! Thanks

**Comment by stoermelder** [comment]
Thanks for your suggestions but please try keeping one request per issue. Otherwise it makes the discussion and development progress hard to track.
Some of these features will be added in a future "8FACE mk2".

**Comment by jaffasplaffa** [comment]
I have been playing with 8Face since yesterday. Best object ever :) 

One of the things I noticed that would be nice to have for it, is copy preset from one slot to another.

I have another suggestion, but I'll create a new issue for that one instead :)

**Comment by stoermelder** [comment]
Added in 8FACE mk2.
