### ISSUE TITLE
Strip: not loading preset when mode is "right-side"

### ISSUE THREAD

**Issue by Eurikon** [stoermelder/vcvrack-packone#16]
windows 10
module version: 1.0.4

When i set the mode button to the "right-side", no preset will be loaded.

**Comment by stoermelder** [comment]
Hi Latif, can provide more information? I've checked it and I see no problem right now. 
Does the preset you are loading have a "right-side"? It may seem that the modules does nothing when loading a preset that was saved in "left-side" or when the right-side was simply empty.

**Comment by Eurikon** [comment]
Ben! totally my bad:) 
I did not fully understand the mode button i guess!
Now i do, thanks for pointing it out, everything works fine as it is. 

----
On a side note: did you see the message about uMap i sent in the forum, 
or should i open an issue for it here on Github?

**Comment by stoermelder** [comment]
Hi Latif, no problem. I'm glad everything is working fine now :-)
Yes, I did receive your message. I will look into it… I'm a bit behind my messages, lots going on in the last days...
