### ISSUE TITLE
8Face feature suggestion - a master controller object that controls all 8 face modules in a patch!

### ISSUE THREAD

**Issue by jaffasplaffa** [stoermelder/vcvrack-packone#160]
Hey!

I would like to suggest a "master" controller module for 8Face. Or maybe this should be a whole new module, to avoid breaking backward compatibility with old 8Face project? 

What I am suggesting is that it would be really nice to have ONE single master controller for all 8Face modules in a patch. As it is now, you have to go to every single 8face module and go to write mode and save each 8Face module individually. If you have many of them, it becomes a big project.

If you have ONE single master module, that has the buttons for storing/loading and remove these buttons from the individual 8Face modules, then simply connect that master module to the individual 8Face modules and then you control all of the modules from the master controller at the same time. 

I think it would make it a lot easier to handle presets in bigger patches, with a lot of 8Face modules.

I want to add that 8Face is already a life saver ;) 

I love the fact that we are able to load presets, it makes it a lot easier to write songs, with different moods and scalings and so on :) 

Best wishes, 
Jakob

**Comment by stoermelder** [comment]
8FACE mk2 supports multiple modules the same time and I think this makes some sort of "master controller" unnecessary.
