### ISSUE TITLE
Stroke - custom cable colors

### ISSUE THREAD

**Issue by libermanomer** [stoermelder/vcvrack-packone#163]
hey Ben,
yesterday i came with a idea that can make cables coloring much easier.

to change cable by keystroke,

1-red
2-yellow 
etc.

cheers,Omer.

**Comment by stoermelder** [comment]
Yes, I implemented it during the stream. It is available in the latest build.

**Comment by libermanomer** [comment]
oh,thanks.
 but i can't make it work for me,
not the next color option also, you have an idea why?

**Comment by stoermelder** [comment]
Do you hover your mouse pointer over a cable plug while pressing the key?

**Comment by libermanomer** [comment]
😆 , got it.
I was pressing a key and then expected to get the desired color, I think it is more convenient.
anyway, that really nice to have this way too, thank you.

**Comment by stoermelder** [comment]
It is not obvious but some things are harder to achieve as they seem. 
While it is quite easy to change the color of an existing cable it is quite hard to influence the color used for the next cable created. This has to do with the color selection Rack uses internally.
Please let me know if you have another suggestion :-)
