### ISSUE TITLE
MIDI-CAT attenuverters

### ISSUE THREAD

**Issue by ContemporaryInsanity** [stoermelder/vcvrack-packone#169]
Could we have built in attenuverters for CCs mapped by MIDI-CAT?  Could be in right click menu...

**Comment by stoermelder** [comment]
Good idea, Ewen! It's almost crazy I never considered this myself...

**Comment by stoermelder** [comment]
Added!

**Comment by ContemporaryInsanity** [comment]
Not working for what I needed.  I have a weird touchpad, x-axis sends notes, y axis is cc BUT over 8 steps from 64 to 127 (so slew welcomed), which I need to convert to 8 steps from 0 to 127, so I really need offset & scale to do this.  Can still do it with extra modules through CV-MAP but...

**Comment by stoermelder** [comment]
I'm not sure what you could with offset and scale which you can't do with minimum and maximum?
Edit: Ok I see what the problem is. You would still need scale > 1 which also could be done by negative minimum.

**Comment by ContemporaryInsanity** [comment]
Yeah, from MIDI-CC I get 5 to 10 volts for my y axis, so I need to subtract five & scale by two, I use it mostly to control aux sends on mindmeld auxspander so the steps aren't really a problem.  Currently use MIDI-CC to bogaudio offset to CV-MAP.

**Comment by stoermelder** [comment]
I extended the range from -100% to 200%. Setting the minimum at -100% should give you trying to achieve.

**Comment by stoermelder** [comment]
I have to think about the labeling of the sliders though. It's now not that easy to understand how it works.

**Comment by ContemporaryInsanity** [comment]
That works perfectly!  Thank you :)

**Comment by stoermelder** [comment]
I added an item on the context menu showing the actual result of the sliders and scaling. Should be pretty easy to setup this way.
