### ISSUE TITLE
AUDIO64 - Add other audio multiples for those of us with >16 <64 channels

### ISSUE THREAD

**Issue by ddwagner** [stoermelder/vcvrack-packone#172]
Thanks for making AUDIO-64. Lifesaver for those of us using ES-3 on audio interfaces where the ADAT channels go past 16. Would be amazing to have somewhat smaller multiples. For instance, UMC1820 audio interface users have adat outputs sitting at 13-20. So an AUDIO-24 or even AUDIO-32 would be big space saver if not too cumbersome. 

Cheers!

**Comment by stoermelder** [comment]
Sorry, I reject this request. 
First, Rack v2 will allow multiple Audio-modules used the same time, so you can put together every number of channels you like. Second, contrary to Eurorack hardware the space in Rack is unlimited.
