### ISSUE TITLE
Midi-Cat - can't do proper mapping to knobs which have negative values as well

### ISSUE THREAD

**Issue by vcvrackideas** [stoermelder/vcvrack-packone#173]
Hi Ben! I love the additions u made in MIDI-cat. However I've got some issues. You can try to map something like FREQ knob on Vult Disjoint filter (it has bipolar positive and negative values according to tooltips). I experimenting with right-click menu new settings, range, and didn't get any luck.

**Comment by stoermelder** [comment]
Thanks for reporting. There is something strange going on. Sometimes it works, sometimes not. I’ll need to check that.

**Comment by stoermelder** [comment]
Thanks again for reporting. It was a stupid bug especially affecting parameters with value -1.
