### ISSUE TITLE
Transit expanders problem

### ISSUE THREAD

**Issue by fradsprds** [stoermelder/vcvrack-packone#174]
Hi I'm using mac Mojave and the expander for transit isn't working.

When I put the expanders next to transit the light of the expander don't turn green and is not usable for save and recall knob position

I made a screenshot
<img width="74" alt="Screenshot 2020-08-30 at 11 25 27" src="https://user-images.githubusercontent.com/44433404/91655774-9189e380-eab3-11ea-9ca3-e7bac9f69881.png">

**Comment by stoermelder** [comment]
Yes, this how it is supposed to be. You need to adjust the number of active snapshots by long-pressing one of the buttons.

> You can adjust the number of active slots by long-pressing a snapshot-button while in read-mode. The LEDs turns off completely for slots that are currently disabled.

https://github.com/stoermelder/vcvrack-packone/blob/v1/docs/Transit.md#sequencing-and-selecting-snapshots

**Comment by fradsprds** [comment]
Now I understand, thank you
