### ISSUE TITLE
Grip - crash on locking the 33th parameter

### ISSUE THREAD

**Issue by typicalanalytical** [stoermelder/vcvrack-packone#176]
Doesn't happen every time, but I am able to reproduce it in at least one patch.  Deleting Grip and re-adding seems to temporarily allow the "gripping" of the pad knob.  Also, the crash only happens on the second SNS module trying to "grip" Pad knob.
  
![2020-09-06 17_08_30-VCV Rack v1 1 6](https://user-images.githubusercontent.com/30984809/92335354-4b5cf300-f064-11ea-82bb-7a37e0416867.png)

**Comment by stoermelder** [comment]
I just built the Southpole module from source as there is no release version yet. I'm afraid I can't reproduce the problem. Can you provide a patch or more instructions?

**Comment by typicalanalytical** [comment]
Click on Grip button and then Pad knob of left SNS.  Then click on Grip button and then Pad knob on right SNS.  Also, sorry I should have included link where I obtained Southpole plugin.  Here it is in case helpful:

https://github.com/gbrandt1/southpole-vcvrack/issues/36#issuecomment-543947766

[VCV Rack crashes when attempting to grip pad on both SNSs.zip](https://github.com/stoermelder/vcvrack-packone/files/5190556/VCV.Rack.crashes.when.attempting.to.grip.pad.on.both.SNSs.zip)

**Comment by stoermelder** [comment]
Ok, thanks for reporting. It has nothing to do with the Southpole modules, it was caused by reaching the limit of 32 parameters which was not handled correctly.
