### ISSUE TITLE
TRANSIT +T Does not recall after patch save/load 

### ISSUE THREAD

**Issue by Outboarder** [stoermelder/vcvrack-packone#178]
+T Does not show saved presets after patch load you have to long press again to recall.
Here is screen capture of the problem :
https://drive.google.com/file/d/1Vm0UypA9dpH4SeHh3tG8fnCghHTm86-c/view?usp=sharing

**Comment by stoermelder** [comment]
Please post the image directly here on GitHub, I don’t have a Google Drive account.
Following your description I cannot reproduce the problem. Is the +T placed directly next to TRANSIT on the right side?

**Comment by Outboarder** [comment]
![cc env2](https://user-images.githubusercontent.com/25549725/92480855-b93b2300-f1fa-11ea-8496-06d4558bc0f2.gif)

**Comment by Outboarder** [comment]
I tested it in a more simple patch (just TRANSIT +T and VCV VCO) it works fine.
Perhaps something is wrong with that patch, Here is the faulty patch.

[TRANSIT +T faulty patch.zip](https://github.com/stoermelder/vcvrack-packone/files/5188675/TRANSIT.%2BT.faulty.patch.zip)

**Comment by Outboarder** [comment]
Ok it's not about the patch, Take a look at this simple example I opened the same file for about 10 times, It seems it has the same problem but in a more unpredictable manner. .  
![Test 2](https://user-images.githubusercontent.com/25549725/92503104-011b7380-f216-11ea-9f6b-0c5106801eb0.gif)

**Comment by stoermelder** [comment]
Ok, thanks for reporting. It is not problem with my modules, it is caused by Rack itself: It occurs if an expander is added before the master module to a patch. This is no issue in the first place but when loading such a patch the expanders aren't initialized correctly. I will open an issue on Rack for this.
I think I can't do anything about it at the moment, except for this suggestion: First add the master module to your patch, then add expanders.

**Comment by Outboarder** [comment]
I always add the master module first but problem still exist. 
Thank you for your time and efforts I hope they manage to fix this.

**Comment by stoermelder** [comment]
In this case I have to check again.

**Comment by Outboarder** [comment]
[Simple test.zip](https://github.com/stoermelder/vcvrack-packone/files/5190173/Simple.test.zip)

**Comment by stoermelder** [comment]
Thanks, it is fixed and will be available in a bugfix release!

**Comment by Outboarder** [comment]
Great, Thank you.
