### ISSUE TITLE
Raw frozen voltage issue

### ISSUE THREAD

**Issue by vcvrackideas** [stoermelder/vcvrack-packone#179]
Raw is pretty cool! But once I found it with frozen output (fully yellow one) after reopening the rack. Hope it would help

**Comment by Petervos2018** [comment]
Had the same issue, as seen here :  
https://community.vcvrack.com/t/dafx-2020/10928/9
![afbeelding](https://user-images.githubusercontent.com/46076474/92518276-5a84a200-f218-11ea-9a60-aca2421db76a.png)

**Comment by stoermelder** [comment]
Thanks for reporting. This issue is caused by the underlying algorithm and currently I won't be able to fix the cause. I will add some protection which should return the parameters to a valid state.
