### ISSUE TITLE
MIDI-CAT/8-FACE problem

### ISSUE THREAD

**Issue by ContemporaryInsanity** [stoermelder/vcvrack-packone#185]
I use 8-FACE with MIDI-CAT to switch controller mappings.

If the MIDI device name changes in MIDI-CAT, 8-FACE doesn't restore it.  This happens if the numbers following the MIDI device name change:

![image](https://user-images.githubusercontent.com/12547379/93015381-e4ce5c80-f5b0-11ea-9ffa-80b52acf260d.png)

Not a problem for one or two mappings but if I have 8 mappings I have to go through each one, select the new MIDI device name, write that into 8-FACE, rinse & repeat, which is a pain.

Perhaps have a MIDI-CAT mode where the numbers after the device name are ignored?  Could cause other issues though, esp where two identical MIDI controllers are used simultaneously?

**Comment by stoermelder** [comment]
I’m afraid I can’t do anything about it. This problem is caused by the MIDI library Rack uses. There are issues for Rack and rtmidi for this problem:
https://github.com/stoermelder/vcvrack-packone/issues/129#issuecomment-638292613

**Comment by ContemporaryInsanity** [comment]
How about a MIDI-CAT version with 8FACE functionality built in that only switches the mappings, not the devices?  Then, when the device name changes, easy quick fix to get everything working again.

**Comment by stoermelder** [comment]
Would it help if I add an option to ignore the MIDI device settings when a preset is loaded into MIDI-CAT?

**Comment by ContemporaryInsanity** [comment]
That should work, yes :)

**Comment by stoermelder** [comment]
I added an option right now. Please let me know if it works for you.

**Comment by ContemporaryInsanity** [comment]
Appears to work ok, will let you know of any issues, thank you!

**Comment by stoermelder** [comment]
Let me know of any issues and I reopen.
