### ISSUE TITLE
STRIP - Load with replace + hotkey for that

### ISSUE THREAD

**Issue by vcvrackideas** [stoermelder/vcvrack-packone#186]
Hi Ben! Could you add an option to Strip that would allow us load a new one and delete previous just automatically without adding the new one next to the previous? Now with existed load option for example I always need to cut old strip first and only then press the load command. 
Also I'd like to have a hotkey combination for that..let's say Ctrl+Shift+L for load with replace and Ctrl+L for existed load option.
Cheers!

**Comment by stoermelder** [comment]
Thanks for the suggestion, has been added.
