### ISSUE TITLE
Stroke "presets"

### ISSUE THREAD

**Issue by Petervos2018** [stoermelder/vcvrack-packone#187]
> The module's settings cannot be duplicated as it provides no use to have duplicate hotkey assignments.

Hi Ben ,
is this also preventing Stroke to load a preset ?
Made a nice "preset" as a "Default Setting" but I can't  load it back into Stroke.

Greetings Peter.

**Comment by stoermelder** [comment]
Hello Peter. Yes, it also prevents to load a preset. I removed it as it makes perfectly sense to have presets, even if duplicating the module will also duplicate the hotkey assignments. 
Unfortunately you can't have one without the other in Rack v1.
