### ISSUE TITLE
ARENA indiv. outs noise

### ISSUE THREAD

**Issue by midiguru23** [stoermelder/vcvrack-packone#190]
I didn't see anything in the docs about what the individual channel output jacks are supposed to do in ARENA. They seem to send the input out with quite a lot of added noise. I'm not sure what this would be used for. Possibly I'm not understanding something about the module, or possibly there's a DSP gremlin in there somewhere. I can grab a quick video or upload a patch if you're not able to duplicate this. I'm using 1.7.1 and the most current version of VCV.

--Jim Aikin

**Comment by stoermelder** [comment]
Thanks for reporting, I will check.

**Comment by stoermelder** [comment]
This issue has been fixed.
It is described there how these ports work: https://github.com/stoermelder/vcvrack-packone/blob/v1/docs/Arena.md#in-ports-and-out-ports
