### ISSUE TITLE
8Face bug pingpong mode

### ISSUE THREAD

**Issue by Petervos2018** [stoermelder/vcvrack-packone#191]
Hi Ben,

as long as I stop the patch with 8face going in the up(ping) direction and start the patch again, all is well, but when I stop it in the down(pong) direction it stops moving after I start the patch again.
Here is a patch : [LPG Test 16092020-3WRONG-2.zip](https://github.com/stoermelder/vcvrack-packone/files/5257248/LPG.Test.16092020-3WRONG-2.zip)
Its hard to explain , start the patch stop it when the third light is lit on 8face and start again, all is well.
Now start the patch wait until the 4th light is lit an it starts going back to the third, stop the patch, start it again, and 8face remains on step 1. (Reload the patch and it works again)
Do you understand what I mean ?

EDIT :  using version e74b752

Greetings Peter.

**Comment by stoermelder** [comment]
Thanks for reporting, Peter. Can you check if it works with d084bfae9e3bcb802b5ff3e112dee112cdc745f6?

**Comment by Petervos2018** [comment]
Thanks Ben, yes this update solves the bug.

**Comment by stoermelder** [comment]
Great, thanks for testing.
