### ISSUE TITLE
Glue on win does not affect placed labels with edits of appearance

### ISSUE THREAD

**Issue by fractalgee** [stoermelder/vcvrack-packone#192]
I have latest stoermelder plugin and Rack 1.1.6 on win10. Glue, if editing appearance of label, does not affect already placed labels, as your demo shows, only newly placed ones, so have to delete and re-add after edits to get new look.

Great modules! thanks!

**Comment by stoermelder** [comment]
This is by design. If you change the default appearance it won’t affect the existing labels. You can change every label individually though.
