### ISSUE TITLE
Module request: list generator

### ISSUE THREAD

**Issue by Eurikon** [stoermelder/vcvrack-packone#193]
Hi Ben,
Would it be possible for you to create a small utility that grabs all names of the used modules in an opened patch.

Orders the names in their respective plugin name, prints this in a small screen or with button click to a txt file next to where the VCV patch file exists.

Could be some small utility the size of 3hp or so.
Cheers,
Latif

**Comment by jatinchowdhury18** [comment]
This is funny, I actually just started working on something like this yesterday. When I make a patch, I found that I like to give credit to the developers who helped create the modules that I used, so I started on a module called "Credit" that would create a .txt file that lists the plugins, developers, and the developers' websites. This could probably be modified so users can customize what info they want saved.

**Comment by Eurikon** [comment]
Fantastic! I would be grateful to either one of you who makes it. 
Also a lot of other video creators will find this very useful.
Hope to see and be able to use it soon :)

**Comment by jatinchowdhury18** [comment]
Of course! I've got an early version working, any feedback would be great (https://github.com/jatinchowdhury18/ChowDSP-VCV).

**Comment by Eurikon** [comment]
Great thanks!, i will try it and report :)
