### ISSUE TITLE
VCV crashes when 8Face goes to next step (Mac OS 10.15.6)

### ISSUE THREAD

**Issue by driesgeusens** [stoermelder/vcvrack-packone#194]
Hi,

On MacOS 10.15.6 VCV crashes when 8Face goes to another step. Writing a step works, read causes crash when going to a written preset.

Crash report:

Process:               Rack [20949]
Path:                  /Applications/Rack.app/Contents/MacOS/Rack
Identifier:            com.vcvrack.rack
Version:               1.1.6 (1.1.6)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Rack [20949]
User ID:               501

Date/Time:             2020-09-28 17:54:17.250 +0200
OS Version:            Mac OS X 10.15.6 (19G2021)
Report Version:        12
Anonymous UUID:        D750E54F-3A8D-7C6F-4611-1D92A0818E8D

Sleep/Wake UUID:       681784F1-837C-4205-8D0E-A7356216ACCB

Time Awake Since Boot: 300000 seconds
Time Since Wake:       550 seconds

System Integrity Protection: enabled

Crashed Thread:        13

Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000001510
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0x1510:
--> 
    Kernel Alloc Once      000000000f265000-000000000f267000 [    8K] rw-/rwx SM=PRV  

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
abort() called
terminating with uncaught exception of type NSException

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff2d94cb57 __exceptionPreprocess + 250
1   libobjc.A.dylib                     0x00007fff665fa5bf objc_exception_throw + 48
2   CoreFoundation                      0x00007fff2d97534c -[NSException raise] + 9
3   AppKit                              0x00007fff2ab6f5ec -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 310
4   AppKit                              0x00007fff2ab57052 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1416
5   AppKit                              0x00007fff2ad37db5 -[NSPanel _initContent:styleMask:backing:defer:contentView:] + 50
6   AppKit                              0x00007fff2ab56ac3 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
7   AppKit                              0x00007fff2ad37d6a -[NSPanel initWithContentRect:styleMask:backing:defer:] + 64
8   AppKit                              0x00007fff2ab54aa9 -[NSWindowTemplate nibInstantiate] + 393
9   AppKit                              0x00007fff2ab1ee46 -[NSIBObjectData instantiateObject:] + 253
10  AppKit                              0x00007fff2ab1e500 -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 534
11  AppKit                              0x00007fff2ab126d1 loadNib + 401
12  AppKit                              0x00007fff2ab11c92 +[NSBundle(NSNibLoading) _loadNibFile:nameTable:options:withZone:ownerBundle:] + 693
13  AppKit                              0x00007fff2ab118e8 -[NSBundle(NSNibLoading) loadNibNamed:owner:topLevelObjects:] + 201
14  AppKit                              0x00007fff2aeda624 -[NSAlert init] + 101
15  Rack                                0x000000010f3235da osdialog_message + 106
16  Rack                                0x000000010f2be599 _ZL18fatalSignalHandleri + 505
17  libsystem_platform.dylib            0x00007fff6799b5fd _sigtramp + 29
18  ???                                 0x0000000000000000 0x0 + 0
19  Rack                                0x000000010f2a1d76 _Z22nvgluDeleteFramebufferP16NVGLUframebuffer + 38
20  Rack                                0x000000010f320b42 _ZN4rack6widget17FramebufferWidgetD2Ev + 34
21  Rack                                0x000000010f2f716e _ZN4rack3app8SvgPanelD0Ev + 14
22  plugin.dylib                        0x000000001246b5d6 _ZN8bogaudio14BGModuleWidget11updatePanelEv + 54
23  plugin.dylib                        0x0000000012469dcb _ZN8bogaudio8BGModule7setSkinENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 155
24  plugin.dylib                        0x0000000012469c6e _ZN8bogaudio8BGModule12dataFromJsonEP6json_t + 158
25  Rack                                0x000000010f317eba _ZN4rack6engine6Module8fromJsonEP6json_t + 1562
26  plugin.dylib                        0x00000000149589df _ZN9EightFace15EightFaceModuleILi8EE13workerProcessEv + 143
27  plugin.dylib                        0x000000001495a7ae _ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEMN9EightFace15EightFaceModuleILi8EEEFvvEPS9_EEEEEPvSE_ + 62
28  libsystem_pthread.dylib             0x00007fff679a7109 _pthread_start + 148
29  libsystem_pthread.dylib             0x00007fff679a2b8b thread_start + 15

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff678e6882 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff679a7425 _pthread_cond_wait + 698
2   com.vcvrack.rack              	0x000000010f39895d swapBuffersNSGL + 93
3   com.vcvrack.rack              	0x000000010f2d6333 rack::Window::run() + 1459
4   com.vcvrack.rack              	0x000000010f2bdefa main + 1434
5   com.vcvrack.rack              	0x000000010f257034 start + 52

Thread 1:
0   libsystem_kernel.dylib        	0x00007fff678e3dfa mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff678e4170 mach_msg + 60
2   com.apple.audio.midi.CoreMIDI 	0x00007fff2e728635 XServerMachPort::ReceiveMessage(int&, void*, int&) + 95
3   com.apple.audio.midi.CoreMIDI 	0x00007fff2e745fee MIDIProcess::RunMIDIInThread() + 104
4   com.apple.audio.midi.CoreMIDI 	0x00007fff2e744d5e XThread::RunHelper(void*) + 10
5   com.apple.audio.midi.CoreMIDI 	0x00007fff2e728331 CAPThread::Entry(CAPThread*) + 77
6   libsystem_pthread.dylib       	0x00007fff679a7109 _pthread_start + 148
7   libsystem_pthread.dylib       	0x00007fff679a2b8b thread_start + 15

Thread 2:
0   libsystem_kernel.dylib        	0x00007fff678e6756 __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff67869eea nanosleep + 196
2   libc++.1.dylib                	0x00007fff64aac6da std::__1::this_thread::sleep_for(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > const&) + 73
3   com.vcvrack.rack              	0x000000010f29dc60 rack::serverRun() + 528
4   com.vcvrack.rack              	0x000000010f29edd8 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)()> >(void*) + 40
5   libsystem_pthread.dylib       	0x00007fff679a7109 _pthread_start + 148
6   libsystem_pthread.dylib       	0x00007fff679a2b8b thread_start + 15

Thread 3:: AMCP Logging Spool
0   libsystem_kernel.dylib        	0x00007fff678e3e36 semaphore_wait_trap + 10
1   com.apple.audio.caulk         	0x00007fff61376b16 caulk::mach::semaphore::wait() + 16
2   com.apple.audio.caulk         	0x00007fff613769b2 caulk::semaphore::timed_wait(double) + 106
3   com.apple.audio.caulk         	0x00007fff613767c4 caulk::concurrent::details::worker_thread::run() + 30
4   com.apple.audio.caulk         	0x00007fff613761e4 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 45
5   libsystem_pthread.dylib       	0x00007fff679a7109 _pthread_start + 148
6   libsystem_pthread.dylib       	0x00007fff679a2b8b thread_start + 15

Thread 4:
0   libsystem_kernel.dylib        	0x00007fff678e3e36 semaphore_wait_trap + 10
1   com.apple.audio.caulk         	0x00007fff61376b16 caulk::mach::semaphore::wait() + 16
2   com.apple.audio.caulk         	0x00007fff613769b2 caulk::semaphore::timed_wait(double) + 106
3   com.apple.audio.caulk         	0x00007fff613767c4 caulk::concurrent::details::worker_thread::run() + 30
4   com.apple.audio.caulk         	0x00007fff613761e4 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 45
5   libsystem_pthread.dylib       	0x00007fff679a7109 _pthread_start + 148
6   libsystem_pthread.dylib       	0x00007fff679a2b8b thread_start + 15

Thread 5:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff678e3dfa mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff678e4170 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff2d8d0ef5 __CFRunLoopServiceMachPort + 247
3   com.apple.CoreFoundation      	0x00007fff2d8cf9c2 __CFRunLoopRun + 1319
4   com.apple.CoreFoundation      	0x00007fff2d8cee3e CFRunLoopRunSpecific + 462
5   com.apple.AppKit              	0x00007fff2ace2954 _NSEventThread + 132
6   libsystem_pthread.dylib       	0x00007fff679a7109 _pthread_start + 148
7   libsystem_pthread.dylib       	0x00007fff679a2b8b thread_start + 15

Thread 6:: CVDisplayLink
0   libsystem_kernel.dylib        	0x00007fff678e6882 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff679a7457 _pthread_cond_wait + 748
2   com.apple.CoreVideo           	0x00007fff2f862d2b CVDisplayLink::waitUntil(unsigned long long) + 229
3   com.apple.CoreVideo           	0x00007fff2f862238 CVDisplayLink::runIOThread() + 482
4   libsystem_pthread.dylib       	0x00007fff679a7109 _pthread_start + 148
5   libsystem_pthread.dylib       	0x00007fff679a2b8b thread_start + 15

Thread 7:
0   libsystem_kernel.dylib        	0x00007fff678e6882 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff679a7425 _pthread_cond_wait + 698
2   libc++.1.dylib                	0x00007fff64a75592 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
3   plugin.dylib                  	0x0000000013864c44 EqMaster::worker_thread() + 100
4   plugin.dylib                  	0x0000000013867eee void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (EqMaster::*)(), EqMaster*> >(void*) + 62
5   libsystem_pthread.dylib       	0x00007fff679a7109 _pthread_start + 148
6   libsystem_pthread.dylib       	0x00007fff679a2b8b thread_start + 15

Thread 8:
0   com.vcvrack.rack              	0x000000010f31641b void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, rack::engine::Engine::start()::$_0> >(void*) + 1019
1   libsystem_pthread.dylib       	0x00007fff679a7109 _pthread_start + 148
2   libsystem_pthread.dylib       	0x00007fff679a2b8b thread_start + 15

Thread 9:
0   com.vcvrack.rack              	0x000000010f315780 rack::engine::HybridBarrier::wait() + 96
1   com.vcvrack.rack              	0x000000010f3156e7 rack::engine::EngineWorker::run() + 247
2   com.vcvrack.rack              	0x000000010f316cb5 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, rack::engine::EngineWorker::start()::'lambda'()> >(void*) + 53
3   libsystem_pthread.dylib       	0x00007fff679a7109 _pthread_start + 148
4   libsystem_pthread.dylib       	0x00007fff679a2b8b thread_start + 15

Thread 10:
0   com.vcvrack.rack              	0x000000010f315782 rack::engine::HybridBarrier::wait() + 98
1   com.vcvrack.rack              	0x000000010f3156e7 rack::engine::EngineWorker::run() + 247
2   com.vcvrack.rack              	0x000000010f316cb5 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, rack::engine::EngineWorker::start()::'lambda'()> >(void*) + 53
3   libsystem_pthread.dylib       	0x00007fff679a7109 _pthread_start + 148
4   libsystem_pthread.dylib       	0x00007fff679a2b8b thread_start + 15

Thread 11:: com.apple.audio.IOThread.client
0   libsystem_kernel.dylib        	0x00007fff678e3dfa mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff678e4170 mach_msg + 60
2   com.apple.audio.CoreAudio     	0x00007fff2cfb2c75 HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int) + 111
3   com.apple.audio.CoreAudio     	0x00007fff2ceaef18 invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned int, unsigned int) + 2677
4   com.apple.audio.CoreAudio     	0x00007fff2cfe2c22 HALB_IOThread::Entry(void*) + 72
5   libsystem_pthread.dylib       	0x00007fff679a7109 _pthread_start + 148
6   libsystem_pthread.dylib       	0x00007fff679a2b8b thread_start + 15

Thread 12:
0   libsystem_pthread.dylib       	0x00007fff679a2b68 start_wqthread + 0

Thread 13 Crashed:
0   libsystem_kernel.dylib        	0x00007fff678ea33a __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff679a6e60 pthread_kill + 430
2   libsystem_c.dylib             	0x00007fff67871808 abort + 120
3   libc++abi.dylib               	0x00007fff64ad0458 abort_message + 231
4   libc++abi.dylib               	0x00007fff64ac18bf demangling_terminate_handler() + 262
5   libobjc.A.dylib               	0x00007fff665fc5a9 _objc_terminate() + 96
6   libc++abi.dylib               	0x00007fff64acf887 std::__terminate(void (*)()) + 8
7   libc++abi.dylib               	0x00007fff64acf829 std::terminate() + 41
8   com.vcvrack.rack              	0x000000010f2f716e rack::app::SvgPanel::~SvgPanel() + 14
9   plugin.dylib                  	0x000000001246b5d6 bogaudio::BGModuleWidget::updatePanel() + 54
10  plugin.dylib                  	0x0000000012469dcb bogaudio::BGModule::setSkin(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) + 155
11  plugin.dylib                  	0x0000000012469c6e bogaudio::BGModule::dataFromJson(json_t*) + 158
12  com.vcvrack.rack              	0x000000010f317eba rack::engine::Module::fromJson(json_t*) + 1562
13  plugin.dylib                  	0x00000000149589df EightFace::EightFaceModule<8>::workerProcess() + 143
14  plugin.dylib                  	0x000000001495a7ae void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (EightFace::EightFaceModule<8>::*)(), EightFace::EightFaceModule<8>*> >(void*) + 62
15  libsystem_pthread.dylib       	0x00007fff679a7109 _pthread_start + 148
16  libsystem_pthread.dylib       	0x00007fff679a2b8b thread_start + 15

Thread 14:
0   libsystem_pthread.dylib       	0x00007fff679a2b68 start_wqthread + 0

Thread 13 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x000070000de30000  rcx: 0x000070000de2f6d8  rdx: 0x0000000000000000
  rdi: 0x0000000000008193  rsi: 0x0000000000000006  rbp: 0x000070000de2f700  rsp: 0x000070000de2f6d8
   r8: 0x000070000de2f5a0   r9: 0x000070000de2f770  r10: 0x000070000de30000  r11: 0x0000000000000246
  r12: 0x0000000000008193  r13: 0x0000003000000008  r14: 0x0000000000000006  r15: 0x0000000000000016
  rip: 0x00007fff678ea33a  rfl: 0x0000000000000246  cr2: 0x00007fff8e07a600
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133

**Comment by stoermelder** [comment]
Thanks for reporting. According to the log you used 8FACE on a Bogaudio module. This is a known issue in the Bogaudio plugin.
https://github.com/stoermelder/vcvrack-packone/issues/188

**Comment by driesgeusens** [comment]
Ok thanks! Wasn’t aware of that.

Regards, Dries

--
Dries Geusens
Nordmann // CC# // Molten Penguin // Rapidman
 geusens.dries@gmail.com // +32 486 754 815
