### ISSUE TITLE
Stroke -- Problems with Rack MIDI Computer Keyboard driver

### ISSUE THREAD

**Issue by xandramax** [stoermelder/vcvrack-packone#196]
I'm finding that in the following scenario, Stroke causes MIDI driver gates to stay high until forced MIDI panic:

1. Shift-C is assigned to Parameter Copy in Stroke. Shift-V is assigned to Parameter Paste, and Shift-R to Parameter Randomize
2. C, V, or R is pressed (without holding shift) while using the QWERTY Computer Keyboard driver for gate output in MIDI-CV

Here is an example patch:
[stroke_midi_bug.zip](https://github.com/stoermelder/vcvrack-packone/files/5330048/stroke_midi_bug.zip)

**Comment by stoermelder** [comment]
I know there are some issues when using combinations which are occupied by other components of Rack. Not sure what to do about it except hoping for diligent users...
