### ISSUE TITLE
Stroke - cable opacity resets to zero

### ISSUE THREAD

**Issue by nnbveh** [stoermelder/vcvrack-packone#197]
I have Stroke as a part of my template, i'm using a shortcut to to hide and show the cables, but since i want the connection points still to be visible for color ID, i've bound the shortcut to opacity instead of visibility. The issue is, even if opacity is set to let's say 60%, and i am able to switch between 60% and 0%, every time i close VCV Rack with the 'off' state, when i re-open my patch, or just start new one, the opacity resets to 0%, so i'm effectively switching between 0% and 0%, which results in shortcut doing nothing.

Macbook pro 16 / Mac os 10.5.5 / Rack 1.1.6. / Pack 1 1.7.1.

**Comment by stoermelder** [comment]
Thanks for reporting. Cable opacity will be preserved across restarts in the preset-data of STROKE.
