### ISSUE TITLE
MIDI-CAT MEM enhancement.

### ISSUE THREAD

**Issue by ContemporaryInsanity** [stoermelder/vcvrack-packone#200]
The ability for MIDI-CAT MEM to scan through the modules in a patch and when it finds one it has mappings for, maps it.
This would enable many patches to be controlled exclusively via midi controllers with no need for mouse or keyboard.

Three potential ways of doing this:

1) A single button that scans forwards from left to right, top to bottom, from the currently mapped module or top left if no currently mapped module.
2) Two buttons, as above plus one that scans backwards.
3) Four buttons, as above plus two buttons that scan to nearest map-able module above or below.

**Comment by stoermelder** [comment]
Thanks for the suggestion. I've implemented your second option as I find it easy to understand (and it is not much more work than the first one). It is not fully tested yet but feel free to give it a try.

**Comment by ContemporaryInsanity** [comment]
Thank you so much Ben, this is great.  No problems encountered so far.
