### ISSUE TITLE
MIDI-CAT keyboard key not working after being mapped

### ISSUE THREAD

**Issue by nnbveh** [stoermelder/vcvrack-packone#201]
I'm mapping lower row of keys on my macbook pro keyboard to the solo buttons on mixmaster jr, but while most of the keys work fine, the C key is not doing anything, while the solo button itself stays in 'on' mode all the time...
This happens constantly among all my patches. Couple of time it happened with X key instead, i think i've started mapping from the other key those times...

**Comment by stoermelder** [comment]
Thanks for reporting. Please provide a patch as example.
