### ISSUE TITLE
8FACE - slot sequencing getting stuck when combined with manual switch 

### ISSUE THREAD

**Issue by ROGAVKA** [stoermelder/vcvrack-packone#203]
I was having fun combining slot-driven sequencing in ping-pong mode with manual choice at the same time and norticed that sometimes sequencer gets stuck (stop reacting to triggers). I think I nailed the exact condition for this: this happens when sequencer wants to advance a step, but was manually moved to the extreme position so now the step should be made in the opposite direction.

Example: I have 3 slots active and it goes (with SLOT triggers) 1->2->3->2 and at this moment I click on 1 manually. So now it thinks that it should move up, but it's actually down and so it's stuck until I click 2 or 3, then it proceeds normally. 

Hope my explanation is not too messy :)

**Comment by Petervos2018** [comment]
could be related to #191 ( also with a messy explanation ;)

**Comment by ROGAVKA** [comment]
Yeah, I should've definitely looked better in open issues, this looks like a similar one.

**Comment by stoermelder** [comment]
Thanks for reporting. Should be fixed now.
