### ISSUE TITLE
TRANSIT - broken snapshots on save after mapped modules have been deleted

### ISSUE THREAD

**Issue by stoermelder** [stoermelder/vcvrack-packone#205]
I don't know if it is simply modules of the same name or not. In the example shown Poly Manual CV and Luci Control Freq always return a value of zero volts from any patch I save. On the other hand Unless Modules Towers returns what appear to be random values. Saving the same patch into more than one slot will return the same random values (so maybe they are not so random). This is with Nightly Build v1.8 d084bfa. 
![TYPHON VCV](https://user-images.githubusercontent.com/55559146/97403837-09765d80-18ed-11eb-87b4-a687e9280ea8.JPG)

_Originally posted by @Telerex in https://github.com/stoermelder/vcvrack-packone/issues/150#issuecomment-717750007_

**Comment by stoermelder** [comment]
Thanks again for reporting. It is fixed now but there can't be done anything about you patch. I'm afraid the snapshots in TRANSIT are broken.

**Comment by Telerex** [comment]
That's ok. The snapshots in the patch were just a test and very easy to do again with Transit. You were so quick with the fix. Well done. Now I will add patch memory to ever synth I have laid out in VCV. Thanks.
