### ISSUE TITLE
SAIL-controlled parameters are not recorded to the undo history

### ISSUE THREAD

**Issue by nnbveh** [stoermelder/vcvrack-packone#208]
When i change a parameter by hovering it with mouse and using a midi controller, and then trying to undo that change, nothing happens, so it seems like those changes are somehow excluded from the whatever mechanism is responsible for the actions history or whatever it's called...

I'm on mac os if that's important.

**Comment by stoermelder** [comment]
That it correct and by design. Changes on parameters controlled by VCV MIDI-MAP are not available in the undo history, too.

**Comment by nnbveh** [comment]
Yes, but vcv midi map is actually attaches midi controller to the
parameters, and SAIL is basically emulates mouse, how is that by design to
ignore changes by mouse? Makes no sense really...In fact, if there's
anything, changes by moving the midi controller while hovering something
wrong with mouse should be traced so if you didn't see where your
mouse pointer was at the moment you could revert the changes...
