### ISSUE TITLE
Transit

### ISSUE THREAD

**Issue by z-plane** [stoermelder/vcvrack-packone#209]
I'm using transit in a patch which I bound to a module (atelier) manually, however it won't let me write any new presets after reloading the patch. It just comes out as the wrong parameters when interpolating in read mode...

**Comment by stoermelder** [comment]
Most probably fixed in #205. Otherwise please provide a patch file.

**Comment by z-plane** [comment]
I figured it was prob some kind of corruption in the binding of params so I just deleted and remade it, but yea it looks very similar to that one. I'm guessing 205 hasn't been pushed out yet?

**Comment by stoermelder** [comment]
No, not yet. I'll submit an update request to the VCV Library within the next week.
