### ISSUE TITLE
8FACE: not working when arming a slot two times in a row?

### ISSUE THREAD

**Issue by ROGAVKA** [stoermelder/vcvrack-packone#212]
Steps to reproduce:
- Attach 8FACE to the module X
- Write current preset in first slot
- Select ARM mode and attach clock to SLOT
- Tweak parameters of X
- Click on first slot - everything resets to saved state just fine
- Tweak parameters of X again
- Click on first slot again - now the port turns PINK instead of yellow and nothing happens on clock signals (see screenshot attached)
![screenshot](https://user-images.githubusercontent.com/44550443/99078342-4b7eef00-25cf-11eb-8c55-a2f7b256b4fe.jpg)
- For switching between two different presets alternately the problem doesn't seem to occur
Am I doing something wrong?

**Comment by stoermelder** [comment]
Thanks for asking. I never considered this use-case but this does work now.

**Comment by ROGAVKA** [comment]
Sorry, I just downloaded Stoermelder-P1-1.8.01018f5-win-20201113.zip and now it seems more broken, not less :(
Now even first attempt to switch in ARMED mode doesn't work, the button just stays yellow.
