### ISSUE TITLE
MIDI-MON doesn't display midi CC's

### ISSUE THREAD

**Issue by VegaDeftwing** [stoermelder/vcvrack-packone#213]
Sorta self evident in the title. Seems to respond to midi note and pitchbend fine, including the higher res of pitchbend. I didn't test mod wheel.

**Comment by stoermelder** [comment]
Disabled by default.
![image](https://user-images.githubusercontent.com/47640667/99102353-3e1d3100-25de-11eb-8559-bd8790a2b80e.png)
