### ISSUE TITLE
RAW still has some instability.

### ISSUE THREAD

**Issue by VegaDeftwing** [stoermelder/vcvrack-packone#214]
I'd love to be able to give you better feedback (pun not intended) on what's going on and the cause, but it seems some cases can still cause RAW to balloon in value and lock up. It seemed to be fairly rare and I don't think it will happen unless the knobs are actually being modified or swung quickly. It could be that just doing a bit of internal slew to the input knobs would prevent it (not sure if you already are- I haven't looked at the code). RAW is far from the only module exhibiting this behavior, and it does seem to be quite rare which is why it's hard for me to provide a better issue description, so it may not be worth fixing.

**Comment by stoermelder** [comment]
I re-enabled a very basic limiter I had already in place for this situation. It won't prevent the output going out of range but the module should at least recover itself.
