### ISSUE TITLE
STRIP presets option to load with replace 

### ISSUE THREAD

**Issue by vcvrackideas** [stoermelder/vcvrack-packone#215]
Hi Ben! Thanks for adding presets folder and load with replace! How about to combine it? I mean some tick option below regarding loading from presets menu. So for example load with replace would be enable by default. This might be useful if I'd like to revising my saved strips to take a faster look on them, just replacing from internal menu ignoring mac or windows finder

**Comment by stoermelder** [comment]
Thanks for the suggestion, Artem. Added.
