### ISSUE TITLE
Hive Ratchet Hangs on Stop

### ISSUE THREAD

**Issue by midiguru23** [stoermelder/vcvrack-packone#216]
I like Hive -- not too different from Maze, but it's fun. When the clock inputs stop, if one of the players is on a ratchet cell, the output will sometimes hang, repeating the ratchet endlessly. This video shows what happens. Thanks for the great modules!

--Jim Aikin

[hive_stop_bug.zip](https://github.com/stoermelder/vcvrack-packone/files/5550291/hive_stop_bug.zip)

**Comment by stoermelder** [comment]
Thanks for reporting, Jim. Fixed for HIVE and MAZE.
