### ISSUE TITLE
CV-MAP "mouse active on mapped button"

### ISSUE THREAD

**Issue by matthleg** [stoermelder/vcvrack-packone#218]
Hello,
with midi-cat, when a knob or a button is mapped you can still use it with the mouse.

It would be really nice if it would be the same with midi-map ( but maybe it isn't possible...)

Please think about it,
      Have a nice day.
Matthieu

**Comment by stoermelder** [comment]
This is an option in the context menu called „Parameter changes“ which is „Locked“ by default.
