### ISSUE TITLE
MB module confusion

### ISSUE THREAD

**Issue by nnbveh** [stoermelder/vcvrack-packone#219]
Hi, since it was moved to the packone my rack complains that it can not be found if i have your other pack installed as well(sorry forgot its name). I have it in my template so every time i start a new patch i get a complain...not a huge issue but slightly annoying.

I'm on mac.

**Comment by stoermelder** [comment]
I'm citing the project page here:

> Modules of PackTau (aka "Test") are purely experimental and might stop working at any update for VCV Rack as they make heavy usage of unstable API. **Also, please expect breaking changes at any time.**

Please update your template.

**Comment by nnbveh** [comment]
But that's the thing, i'm talking about the MB module which is NOT part of
the pack tau anymore...and the module itself works just fine. BUT, if i
install pack tau, rack start to think that MB is a part of TAU, not ONE,
trying to look for it there, can't find it...

So my template is just fine, all of your modules work as expected, there's
just some slight 'logistics' problem, so i thought maybe it's something
which is easy for you to fix...

If not, fine, i'll just remove the TAU pack.

Thanks anyways.

**Comment by Petervos2018** [comment]
When I saw Ben added the MB to packone, and removed it from Tau, I thought "can this be done without problems, when loading an"old" patch ? ", and indeed it can't.
For now I have an "old" tau installed so I don't get the error message.
But once I update tau I will know that the first thing I have to do is to add the packone MB to the "old" patch and save it.
AFAIK Ben can not do anything about this because the slug of the MB module is changed, and vcv cannot find it any more.

**Comment by stoermelder** [comment]
The easiest would be replacing the plugin slug in the patch file with a text editor.
Another hint: If you update PackTau to the latest build MB is not needed anymore, the modified module browser is integrated in the menu bar.

**Comment by Petervos2018** [comment]
> 
> 
> the modified module browser is integrated in the menu bar.

HAHA, I read that last time and had no idea what you meant.
Now I see the "EXTRA" in the menubar and think...."why did I not notice this before?"
Oh you fantastic beast, thanks for all you modules and extremely usable add ons.

Greetings Peter.

**Comment by nnbveh** [comment]
Perfect! I'll just get rid of the module then...i was actually wondering
how come the browser looks 0.6 when the MB is not in the patch...
