### ISSUE TITLE
STRIP - exclude some parameters from randomization

### ISSUE THREAD

**Issue by stoermelder** [stoermelder/vcvrack-packone#22]
Suggested by an user:
```
Would it be possible that we exclude some module parameters from randomization?
Example:
when I use Strip to randomize ADDR-SEQ, I would like to exclude the Steps and Select parameters from randomization. Or if I use a filter, maybe I would like to exclude the cutoff rome randomization.
```

**Comment by ContemporaryInsanity** [comment]
You can do this now.  If you use CV-MAP to map a voltage to a control (or controls) STRIP will not randomise them.

**Comment by stoermelder** [comment]
I know, I proposed this trick myself 👍

**Comment by Coirt** [comment]
You used to be able to hold down a parameter with the mouse in previous versions of Rack and press CTRL+R, the held parameter would stay hidden from Randomise, very useful bug. Nice to know Mappings exclude! Will definitely use that trick.

**Comment by stoermelder** [comment]
Implemented in e334684878311772e6efadccf3234a3de095a9a5.
Short press button EX, LED turns red: learn excluded parameter.
Long press button EX: clear all excluded parameters.
LED green: At least one parameter is exlcuded.
Manual update is pending.

**Comment by stoermelder** [comment]
Completed with 21cb54066f75a9533fc49d57277405662b5bb6a5.

**Comment by stoermelder** [comment]
I reopen this issue because I'm reverting the implementation. I'm very unhappy how I've done it and the ugly workarounds I needed to get it work.
I will think about it and hopefully find an elegant solution at a later point.

**Comment by FMTolstoevsky** [comment]
Please don't frighten me, Ben! I sincerely hope that you will preserve that wonderful feature in your future releases. For me it works very good so far ;)

**Comment by stoermelder** [comment]
I think this feature is indeed useful and it will come back, just my implementation sucked. 
It worked nicely most of the time, but changing the modules of a strip with excluded parameters caused some problems. I was able to work around them with even worse code. 
I have to think a bit longer over it to find a solution  that not only works but will be maintainable in future versions of the module,

**Comment by stoermelder** [comment]
Back again in 377671d. 
Works now nicely with proper thread-handling.

**Comment by FMTolstoevsky** [comment]
Very excited to read this :) Will check new beta soon
