### ISSUE TITLE
cv-map small problem with "parameter changes" lock/unlock

### ISSUE THREAD

**Issue by matthleg** [stoermelder/vcvrack-packone#221]
![Screenshot (20)](https://user-images.githubusercontent.com/36376831/101996193-76dd2280-3cd0-11eb-8bc1-ca9a18ba2aa5.png)
Hello,
 in this patch, with parameter changes **unlock** (in cv-map) I can switch on the buttons of intermix but I can not switch them off (using stroke). 
I would like to use both: stroke or the mouse
I think it's a small bug?
Thanks for all your fantastic work .
All the best.

**Comment by stoermelder** [comment]
Thanks for reporting, fixed.
Also notice there is some sort of matrix-mapping mode for INTERMIX which allows controlling all 64 pads using 16 keys or controls. Unfortunately INTERMIX isn't documented at the moment, but it is mentioned here: https://github.com/stoermelder/vcvrack-packone/issues/80#issuecomment-570357921
