### ISSUE TITLE
MB only show category, not brand

### ISSUE THREAD

**Issue by joopvdl** [stoermelder/vcvrack-packone#223]
Would it be possible to have an option to hide the "Brands" part in the left side column in MB? So you can choose Favorites, and have the categories all shown, instead of having to scroll.

I find one of the most important things when working in a studio is the ability to find your stuff quickly. Having to remember all the names of the modules I like to use is quite a task.
In Cubase, I spent a lot of time categorizing my plugins, and sorting them in a useful way. In Rack, that's only possible in MB (for now). But still I find it quite hard to reach the categories that I have to scroll to. 
So this would be my little enhancement suggestion. Knowing that, once Rack2 drops (if it ever will :), things might be different.
Thank you, Joop

**Comment by stoermelder** [comment]
Thanks for the suggestion, added.

**Comment by joopvdl** [comment]
That's pretty fast :) So apologies for re-opening, but as I was playing around with the idea, I wondered if it would be possible to hide the empty categories, thus even more simplifying the overview.

**Comment by stoermelder** [comment]
I don't think I want to do this as it will change the list while searching or a brand is selected. But feel free to do your own custom build, it needs only replacing `item->disabled` by `item->visible` in https://github.com/stoermelder/vcvrack-packone/blob/827e32a30a37d4372fb88094d372f54aec4ee16c/src/mb/Mb_v1.cpp#L940

**Comment by joopvdl** [comment]
That's fine, thanks anyway. Your stuff is extremely useful.
