### ISSUE TITLE
8faces possibility to give names to the 8 buttons

### ISSUE THREAD

**Issue by matthleg** [stoermelder/vcvrack-packone#224]
Hello,
It would be really nice if when the mouse goes on one of the button:
 to see a name we can assign (with the right menu) and not only slot1, slot 2... as it is now.
Please think about it,
Have a nice day,
Matthieu

**Comment by stoermelder** [comment]
Thanks for the suggestion. I won't add it to 8FACE but it will be available in 8FACE mk2.
