### ISSUE TITLE
add toggle to CC input slots in Midi-Cat

### ISSUE THREAD

**Issue by rbreckenridge** [stoermelder/vcvrack-packone#225]
I have an Akai Midimix and the `mute` and `RecArm` buttons output a CC value. 

I would like to map the buttons to the mute/solo buttons on MixMaster, but currently, they only act as momentary toggles, muting while the button is being pressed and then unmuting on release. 

I can get this functionality with VCV's Midi-CC, patching the outputs from the buttons into a merge, into the `Poly Mute Solo CV`, so I suppose that's OK, but I think it would be a lot cooler if I could manage all of my controller mappings in one place (possibly more of a psychological upgrade than a technical one).

**Comment by stoermelder** [comment]
Thanks for the suggestion, added.
