### ISSUE TITLE
Bookmark module

### ISSUE THREAD

**Issue by taji** [stoermelder/vcvrack-packone#227]
Simple panel with two configuration parameters:

- Name: (this will appear on the panel).
- Link: the url to navigate in your browser when the panel is clicked. 
- Image (Optional):  A PNG icon to display. 

When clicking on the Link (Or Image), this will open a new tab in the system's default browser to the link specified (should work across all OS platforms).

Motivation: I'm not a big fan of any of the Notes modules available.  But documentation is a subjective thing, so let the patch author decide the experience.  Could be the author's website, a discord channel, a pdf, a youtube video, etc.

You could call it Bookmark or maybe Hyper?

Thanks :-)

**Comment by stoermelder** [comment]
While this is a valid suggestion I most probably won't do it, for security reasons: Someone could use it to link to a website spreading malicious software or some other harmful content.

**Comment by taji** [comment]
Good point, no worries.
