### ISSUE TITLE
possibility to use 8face with strip...

### ISSUE THREAD

**Issue by matthleg** [stoermelder/vcvrack-packone#229]
Hello, 
sorry it's me again... ( I use a lot your modules in every patch and I use a lot vcv).

I am saving few small strips (one module + teleport in/out from little utils)  and the opposite teleport in/out is outside of the strip so, in strip when I "load with replace" I have my new strip already plug.

So I was thinking to use this with 8 face but it doesn't work... I suppose that in the preset of strip doesn't appear the "loaded strip".
in other word I would like that for each button of 8face strip remember what was the loaded strip...
Do you think it would be possible?
Thanks again,
                      Matthieu.
![Screenshot (93)](https://user-images.githubusercontent.com/36376831/107858508-c527b280-6e34-11eb-9086-5af17e0ca291.png)

**Comment by stoermelder** [comment]
STRIP does not have an internal memory, it exports and imports a set of modules only.
I don’t see an use-case of what you are trying to do which can’t be done with a sequential switch instead?

**Comment by matthleg** [comment]
I am often doing really big patches so it is a way to switch between
modules but without have them all open in the patch and save cpu.

**Comment by stoermelder** [comment]
Ok, I see. Still, adding and removing modules is something that should be sequenced as these operations interrupt the audio thread (the same is true for adding or removing cables).
Did you try STRIP's disable? It should give you a similiar result CPU-wise.
