### ISSUE TITLE
Strip internal presets folder - subcategory in right click menu by adding a folder into the presets folder

### ISSUE THREAD

**Issue by vcvrackideas** [stoermelder/vcvrack-packone#230]
Hi Ben, long time no writing requests ;-) So here is the deal - I found recently a concept of internal folder of Strip quite useful. And then I tried to make for example KICK folder inside it. Of course I had no luck without because there is no support for such categories defined by folders yet. So if you will find this idea useful could you add please then? Cheers!

**Comment by stoermelder** [comment]
Thanks for the suggestion, added.
