### ISSUE TITLE
Midi-cat: trig to start mapping

### ISSUE THREAD

**Issue by joopvdl** [stoermelder/vcvrack-packone#232]
to me, midi-cat is one of the most useful (and used) utilities in Rack. I even bought some midi control surfaces so I can use rack with a hardware feel.
My patches are usually quite big, so I need to do a lot of scrolling and zooming to get around.
Therefore it's sometimes quite a search to locate the midi-cat module, so I can map midi to whatever I'm working on at that time.
I would love to be able to create a dedicated shortcut key. I could use stroke for that (another crazy useful tool), so if Midi cat had a trig input, I coult do this.

Joop

**Comment by stoermelder** [comment]
I'm thinking about creating another expander for MIDI-CAT which provides this option and integrate MIDI-CAT in the context menu of every parameter to allow a faster mapping workflow (currently only available when already mapped).

![image](https://user-images.githubusercontent.com/47640667/114307640-d6add380-9ae0-11eb-8189-c9c49070025a.png)

**Comment by vcvrackideas** [comment]
WOW! really nice. It would be way faster and intuitive than before

**Comment by stoermelder** [comment]
A new expander is available in latest build.

![image](https://user-images.githubusercontent.com/47640667/114858654-09f6a800-9dea-11eb-8d89-efda78a1301f.png)
