### ISSUE TITLE
enhancement: add labelling to utility module buttons

### ISSUE THREAD

**Issue by flyingLowSounds** [stoermelder/vcvrack-packone#233]
When using modules like 8Face, Transit, etc. it would be useful to know what functionality a button has without needing to press the button to find out. 

Would it be possible to add a labelling feature per button so that the label appears as part of the tooltip when hovering on button?

So, for exampe, for 8Face, the first button currently reads "Preset slot 1: 0". It would be great if I could add a label so it read "Preset slot 1: Car Horn" or "Car Horn\Preset slot 1: 0" or similar.

**Comment by stoermelder** [comment]
This has been added in the development branch some time ago. 
Alternatively you can use my GLUE module which works for every module in Rack.
