### ISSUE TITLE
MIDI-CAT + Mindmeld Mixmaster - Map Module Left Crashes.

### ISSUE THREAD

**Issue by Chaircrusher** [stoermelder/vcvrack-packone#234]
This is what I think of as a GOOD crash because it crashes on an assert, and you can look at the source in Rack to see where it's happening and why.

1. Put an instance of MIDI-CAT to the right of a MindMeld MixMaster.
2. Use the context menu to select "Map module left->Clear first'
3. KABLAMMO

This could be a Stoermelder bug or a Rack bug, or an Mindmelder Mixmaster bug. But it's reproducable.
 
[midi-cat-crash.txt](https://github.com/stoermelder/vcvrack-packone/files/6230787/midi-cat-crash.txt)

**Comment by stoermelder** [comment]
Thanks for reporting, Kent. Fixed.
