### ISSUE TITLE
Midi-cat Resending MIDI feedback

### ISSUE THREAD

**Issue by Castled00r** [stoermelder/vcvrack-packone#236]
The Feedback function of Midi-cat is brilliant. It makes vcv super intuitive with controllers like the BCR 

I am not sure weather this issue is a bug or an idea. But whenever I skip presets in the beheringer BCR the feedback function doesnt go along, and the bcr buttons of presets 2 and up doesnt "listen" to the knob position in vcv. 

I can confirm that Behringer BCR/BCF controllers are not “aware” of what’s in those other presets, and will just ignore incoming messages for CCs assigned on the other presets. 

What could be good is if you could map a CC or Note On to “Re-Send MIDI Feedback”. That way, you could change to another preset, and push an assigned button to update the LEDs/Faders.

NewHansen

**Comment by stoermelder** [comment]
I understand your request but I'm not sure if it brings something new to MIDI-CAT: Did you try enabling the "Periodically" option for "Re-send MIDI feedback"? I suspect it will work for your scenario.

**Comment by Castled00r** [comment]
Yes, whenever Periodically is enabled, the Led's ''listen'' to VCV and jum to to their proper position. 
This indeed works for this scenario, but because of the 16 midichannels, and 16 Midi-Cat instances, every time a VCV patch is loaded, you need to turn on manually the 'Periodically' function 16 times :)

On the VCV forums tomfug came with the idea to CC the 'Periodically' button. The reason for this is to write this CC in the BCR-factory-settting. Every time the preset button on the bcr is toggled, the CC is send directly to VCV and the LED buttons align.  

I am aware this is something quite specific, and BCR related, but I also feel like a lot of VCV users are using this device to control vcv. I believe that if the Led buttons jump to the original place on every preset, it will become ultimately intuitive to control VCVrack. Thanks for reading my rambling ;)

**Comment by stoermelder** [comment]
> Yes, whenever Periodically is enabled, the Led's ''listen'' to VCV and jum to to their proper position.
> This indeed works for this scenario, but because of the 16 midichannels, and 16 Midi-Cat instances, every time a VCV patch is loaded, you need to turn on manually the 'Periodically' function 16 times :)

Can you explain what you mean by that? Why do need to set the option manually every time a patch is loaded?

**Comment by Castled00r** [comment]
Just noticed that the toggle option 'periodically' will stay on if you save a patch! And so now the LED's turn back to their original positions! Can't believe I needed a week to figure this out. Sorry for the ignorance, but i am glad this is solved. Will post in the VCV forums. Thanks for the support Ben!

**Comment by stoermelder** [comment]
I’m glad you got this sorted out because I could really follow your issue 👍 
Besides that, these older Behringer controllers behave a bit strange in this matter, in my opinion.
