### ISSUE TITLE
Improve documentation on changing sequence length in Transit

### ISSUE THREAD

**Issue by terrytheplatypus** [stoermelder/vcvrack-packone#237]
I was able to figure this out when i saw the gif on the doc page where the mouse button is held down, but I used this module for several months without realizing this was an option. It would be helpful if something was added to the documentation page simply stating that sequence length can be changed in this way

**Comment by stoermelder** [comment]
Can you elaborate this? It is mentioned right at the beginning of the "Sequencing" passage:
https://github.com/stoermelder/vcvrack-packone/blob/v1/docs/Transit.md#sequencing-and-selecting-snapshots

**Comment by terrytheplatypus** [comment]
Sorry, I missed that because i was searching for "length". That's my mistake because i didn't read the doc thoroughly enough, but i think it would be slightly better to rephrase it with the "length" keyword there as well. For example: "You can adjust the number of active slots (i.e. sequence length) by long-pressing a snapshot-button while in read-mode.

**Comment by terrytheplatypus** [comment]
I submitted a pull request for the minor documentation change.
