### ISSUE TITLE
SAIL - some modules causes VCV crash

### ISSUE THREAD

**Issue by vcvrackideas** [stoermelder/vcvrack-packone#241]
Hi Ben! Yesterday I noticed weird thing when used Sail on Frozen Wasteland QAR - it just crashes VCV on every knob. The thing on this module - it doesn't expect anything that stepped values mean integral, that's why imo it causes a crash. With basic midi mapping it works fine btw so I asked Eric first about this and he doesn't see any troubles in his module.

**Comment by stoermelder** [comment]
Thanks for reporting, there was indeed a bug (caused by long parameter names in the overlay and ability for multiline display which in not implemented right now).
