### ISSUE TITLE
CV-MAP - context menu as midi-cat mapping

### ISSUE THREAD

**Issue by vcvrackideas** [stoermelder/vcvrack-packone#243]
Hi Ben! It seems your first module cvmap not so popular because of map micro. But what if it can get everything that midicat has right now (context menu mapping expander included)? I mean it would be easier and fast to setup it in template and map needed knob via context menu than adding map micro each time and so on. I have noticed also that map micro also has a context menu settings on a blinded parameter which is pretty cool and it could be used too for cvmap. But if it requires a huge amount of work just ignore it. Would like to hear also your vision on ideal way of super faster internal mapping in VCV too! Idea with context menu binding is way too awesome! Thanks for this.

**Comment by stoermelder** [comment]
I actually started implementing this for CV-MAP some time ago but never finished it. Maybe I'll need to revisit it.

**Comment by stoermelder** [comment]
Added.

**Comment by vcvrackideas** [comment]
Thank you very much for adding that! Already love more low and high range controls than offset and scale, more intuitive. Just curious is this possible to add context menu to the mapped parameter as you did for uMap? If not it's not a big deal. Will be useful only when have a lot of mappings around the patch. Cheers!

**Comment by stoermelder** [comment]
Sure!
