### ISSUE TITLE
Can't save or open vcvss

### ISSUE THREAD

**Issue by gillesdanger** [stoermelder/vcvrack-packone#244]
hello,
this is what I'm doing:
After "saving as" in the "strip" section, what I get is a .vcv file.
So I read on som thread to change the extension for a .vcvss
But unfortunately It's not working. I get "could not load file……… test.vcv "
So it means that the operation of changing for .vcvss is not taking.
Have you some advices?
OSX 10.15
Best.
g.

**Comment by stoermelder** [comment]
Please provide a file you did save before.

**Comment by gillesdanger** [comment]
Hello Ben,
Thank you so much for your help,
I hope that it is something that I not doing as it should
Today, when I change the extension, finally, I can’t open at all the vcvss file…
weird…
I made you a video to see how I did.
g.




ps: test.vcvss.cv , is the file you saw me saving then I changed the extension. Looks like it’s not good at all
I add another file which is save without renaming:

**Comment by stoermelder** [comment]
I’m sorry but I can’t see any file nor video?

**Comment by gillesdanger** [comment]
and with the link to a wetransfert?
https://we.tl/t-cc3cIakNB3 <https://we.tl/t-cc3cIakNB3>

**Comment by stoermelder** [comment]
Thanks, but to be honest I have no idea what's going on. I'm a Windows user so I can't test but no one ever had similar issues on Mac OS :-(

**Comment by gillesdanger** [comment]
Thank you Ben.
I will un-gohst my mac one day :)

**Comment by stoermelder** [comment]
I'm closing this for now.
