### ISSUE TITLE
MIDI-KEY

### ISSUE THREAD

**Issue by stoermelder** [stoermelder/vcvrack-packone#245]
https://community.vcvrack.com/t/stoermelders-idea-und-development-thread/10515/316

**Comment by vcvrackideas** [comment]
Hi Ben! Very cool module indeed. Do you plan to add something additional commands like in Stroke (add module, randomize value) to it? By now I can do that by having one instance of Stroke aside and it actually duplicating keyboard action so maybe it was your intention to made MIDI-KEY as helper for Stroke in this way?

**Comment by stoermelder** [comment]
I don't think I'll add these commands to MIDI-KEY. Technically there is no limitation to do so but I don't like duplicating the same functionality on different modules. I guess these two are nice "partner" modules and work well toghether.
Maybe I add an "expander" channel which gets active if placing MIDI-KEY next to STROKE but I won't bet on it at the moment :-)
