### ISSUE TITLE
Off function for Transit and 8face on the front panel or by hotkey

### ISSUE THREAD

**Issue by vcvrackideas** [stoermelder/vcvrack-packone#249]
Hi Ben! I really dig phase morphing via transit these days but sometimes I just want temporarily stop movements for whatever reasons and need to dive in menu and press off each time. Maybe you could apply some micro button for both modules near trigger input or just hot key? Cheers!

**Comment by stoermelder** [comment]
Added SHIFT+Q hotkey for 8FACE, 8FACE mk2 and TRANSIT.

**Comment by vcvrackideas** [comment]
Thanks, it's working! However could this hotkey be a toogle one to the previously playing mode back again? By now it's only deactivating (nice to see blinking yellow LED on transit, really good indication) but to activate triggering again still needed to get to menu diving

**Comment by stoermelder** [comment]
Toogling has been added without further notice, so closing 😁
