### ISSUE TITLE
MIDI-CAT - kind of Re-learn mode in context menu

### ISSUE THREAD

**Issue by vcvrackideas** [stoermelder/vcvrack-packone#250]
Hi Ben! I found it's good to have midi cat and midi map (due to context menu mapping on parameter) for just locking temporarily to one knob and then switch to the another when neede, so just one encoder for that. My current workaround is like that - right click on already mapped knob - learn midi - click on  the next needed knob - and turn the encoder. Bingo - encoder has been rewired to the next knob. Pretty working solution already but the only disadvantage is it removes all parameters inside CC mapping like slew and etc. The ideal workaround to me is smth like that - right click on currently mapped knob - relearn (or change destination) - click on the next needed knob and that's it (would be cool to have auto escape mode from mapping).
The reason I'm asking for that is simple - imitate hardware two hands wiggling. For example when I bind the knob via the way described above I can stick one encoder to it and then move mouse to another one and use MIDI-STEP and SAIL to it and find the best interaction between knobs like in hardware. Or another way for your new and awesome context menu for CV-MAP - bind knob to the LFO speed and simultaneously adjust the range via mouse in context menu. 

I think there are can be restrictions in MIDI-map algorithm in VCV itself to mangling with destinations while keeping CCs but who knows. Cheers! If you need some video for desirable workaround  just say

**Comment by stoermelder** [comment]
I added a "Remap" context menu option. Please let me know if this works for you.

**Comment by vcvrackideas** [comment]
Thanks Ben! I can't find Remap but I see MIDI CC ## on the new knob, is this it? If yes it kind of works but it doesn't activate midi feedback and even with endless encoder it creates jump in parameter when start turning the knob

**Comment by stoermelder** [comment]
I re-ordered the context menu items in the meantime, CV-MAP and MIDI-CAT work almost the same now.
![image](https://user-images.githubusercontent.com/47640667/120067703-4e2dc700-c07d-11eb-8aca-b75af1739da3.png)

**Comment by vcvrackideas** [comment]
> I re-ordered the context menu items in the meantime, CV-MAP and MIDI-CAT work almost the same now.
> ![image](https://user-images.githubusercontent.com/47640667/120067703-4e2dc700-c07d-11eb-8aca-b75af1739da3.png)

Yeah, thanks, those MIDI-CC are exactly what I was looked for. The only issue is encoder position doesn't resetting properly when use these MAPS in right click menu. Or maybe it's an issue on my side?

**Comment by stoermelder** [comment]
You mean the encoder on your MIDI controller? I did not test it on a controller, I just checked a MIDI message for feedback is sent out. I will do a test later.

**Comment by vcvrackideas** [comment]
Exactly. Ok, just let me know if you need some video from me to show up an issue.

**Comment by vcvrackideas** [comment]
> You mean the encoder on your MIDI controller? I did not test it on a controller, I just checked a MIDI message for feedback is sent out. I will do a test later.

Sorry for confusing you! Choosen output channel was wrong to get proper midi feedback. Everything works perfect now
EDIT: Oh, find a weird thing. When slew has been activated on CC get weird behavior when relearn this CC - it looks like fast rise and fall to the current position and then works correctly. Seems like slew doesn't get right with midi feedback if I'm not missing something.

**Comment by stoermelder** [comment]
I made some minor adjustments on that. Not sure I can follow you on slew and MIDI feedback; these work independently and slew is never applied to MIDI feedback.
