### ISSUE TITLE
8FACE - "auto" mode besides "read" and "write"

### ISSUE THREAD

**Issue by Stubs42** [stoermelder/vcvrack-packone#251]
Hi,

I want to propose to add a third mode beside read/write. I call it auto mode. In this mode, 8FACE would write the current state of the module it controls into current selected slot whenever the slot is changed before restoring the state of the new selected slot to the module.

Think about a sequencer sequencing patterns for a sequencer like a trigger sequencer with 16 steps to handle 32 Step patterns by switching from slot 1 to slot 2 and vice versa on every bar. The requested auto mode would allow for editing while the sequence is running which vital for me in a modular environment. As an example, when bar 2 is running (slot 2 selected) and I enable a step in the trigger sequencer, this change will be automatically stored in slot 2 before slot 1 is selected to play bar 1 again.

Hope I managed to explain my request and why I think it is important.

Regards
Dieter

**Comment by stoermelder** [comment]
Hi Dieter, thanks for this suggestion. I will think about it but it sounds useful indeed.

**Comment by Stubs42** [comment]
Hi,

thanks for taking the implementation into account.

Really hope you will do it. Would like to use it in my Sequencer Template to use pattern functionality on sequencers not supporting patterns, which is not really possible with the current Implementaion of 8FACE because any changes to a running sequence would be lost when switching to another pattern.

Regards
Dieter

**Comment by stoermelder** [comment]
I added "Auto"-mode to 8FACE in the development build.
It will be added to 8FACE mk2 later as this is a bigger change and needs more testing. I guess it would be useful for TRANSIT, too.

**Comment by Stubs42** [comment]
This is great news. Haven't used transit yet but auto mode for 8FACE is great news.
Thank you!

**Comment by vcvrackideas** [comment]
Thanks Dieter for the idea and of course Ben for implementing it! By the way is there any plan to new fashioned 8facemk2? ;-)
I'd like also say that auto mode is pretty musical thing having intention to make your decision as the next trigger will be ;-)

**Comment by Stubs42** [comment]
I stumbled over the problem using 8face to switch pattern of sequencers themselves not providing patterns. Doing this it is not possible to edit while playing which is totally unacceptable for me in a modular environment. Auto mode should read and store the changed pattern before switching. Thus any edits of current pattern playing gets preserved.

**Comment by stoermelder** [comment]
> By the way is there any plan to new fashioned 8facemk2? ;-)

It is already halfway done but implementation is a bit more complicated on 8FACE mk2. TRANSIT just got this mode a few moments ago, see #269.
