### ISSUE TITLE
Add module command of Stroke does nothing on windows

### ISSUE THREAD

**Issue by vcvrackideas** [stoermelder/vcvrack-packone#254]
Hi Ben! Can't get it working Windows. What is the exaclty workaround of this function by the way? :-)

**Comment by stoermelder** [comment]
Did you „learn“ a module first? Essentially it grabs the preset of a specified module and adds it afterwards using the hotkey, whenever you like.

**Comment by Petervos2018** [comment]
There is a way to make this crash rack, don't learn a key but choose module commands-> add module.
Then right click that button again go to module commands and hover over add module, rack will crash.

**Comment by stoermelder** [comment]
Thank you, fixed.

**Comment by Petervos2018** [comment]
It works, and now I also understand what it does...thank you.
