### ISSUE TITLE
CV input expander for STROKE to achieve access from midi (or cv) to special commands 

### ISSUE THREAD

**Issue by vcvrackideas** [stoermelder/vcvrack-packone#255]
Hi Ben! There is no alternative to get an access to such unique commands as you implemented in STROKE like zoom, randomize, copy or add module from midi controllers (or crazy from CV gates, but personally I probably have no interest in automating zoom for example haha). I thought to offer you separate module at first but expander seems be a bit easy to do for you of course if you have any interest in this. Cheers!

**Comment by stoermelder** [comment]
Sorry, this won't happen. We can talk about MIDI mapping but CV inputs will cause more problems than use.

**Comment by vcvrackideas** [comment]
ok, just midi would be fine. One of my favorite idea was use midi button for randomize parameter command and once I find good position I can tweak it just for a moment with sail enabled precise tuning.

**Comment by stoermelder** [comment]
Can't you do this with STRIP already?

**Comment by vcvrackideas** [comment]
> Can't you do this with STRIP already?

No, the reason I have mentioned Random value function in STROKE was it designed to be used of one parameter, not whole strip. I just binded it to R button for example, hover mouse on parameter and tap it as many times as I like to even animate is like a temporary sample and hold and then move to the next one to explore module a way faster with mouse. That's why having button on midi controller for it can be really helpful because I can then switch to microadjust the parameter via Sail and move to the next one. 
Cheers!

**Comment by stoermelder** [comment]
I'm closing this one: MIDI-KEY #245 is in development and coming along pretty well. You can use MIDI-KEY for converting MIDI messages to keyboard events and use STROKE for these keyboard events as usual.
