### ISSUE TITLE
Context menu learning expander for CV-MAP (similar to MIDI-CAT map)

### ISSUE THREAD

**Issue by vcvrackideas** [stoermelder/vcvrack-packone#256]
Hi Ben! You did an amazing job on providing scales inside context menu of mapped parameter to CV-MAP. In my opinion to complete the quest is only learning ability via context menu would be as a finish touch. The idea is similar that you have in midi-cat map expander, so we place expander with CV-map and define the ID (if it can be longer than two letter it would be also pretty cool). 
Why I'm asking for that. Well...I often find that people are struggling with adding cables and adding and adjusting modulation is really consumption process in electronic music making process . Yeah cables is important in modular but VCV ability to do internal mapping can be very user friendly in that case. For example in starting template we can add to CV-map all modulation sources that we used usually and define the names to the expander, for example SINE LFO or Sample and hold. And the just by starting adding oscillators we can right click on a parameter and choose the destination of modulation mapping. And then right click again and get into scalling and slew limiting. So it can be very easy and user friendly for the many new users.

**Comment by stoermelder** [comment]
I thought about this myself. I think it would be a useful addition but we’ll see what happens ;-)

**Comment by stoermelder** [comment]
I’ve been thinking about this and guess I need to make arbitrary channel routings possible before this makes much sense:
Currently input channel 1 is „hard-wired“ to slot 1, channel 2 to slot 2 and so on. I’m proposing I allow every input channel mapped to each slot. This way someone could connect an LFO to channel 1, for example, and map it onto multiple parameters using multiple slots, each with its own scaling.

**Comment by vcvrackideas** [comment]
Sounds cool!

**Comment by stoermelder** [comment]
Already implemented in the commit a few minutes ago.

**Comment by stoermelder** [comment]
Ok, I added a new expander module CV-MAP CTX, also renamed MIDI-CAT's counterpart to MIDI-CAT CTX. There has been some issues in the context menu extension on the parameters but it seems to be working reliable now.

**Comment by stoermelder** [comment]
Toogling has been added without further notice, so closing 😁

**Comment by vcvrackideas** [comment]
wow! what a nice thing you've done! Very pleased with how this is working right now. 
One last thing - we can even use only one CV-MAP in a patch (for the most middle patches I guess) if you would add "custom label" menu such as done in MIDI-CAT. In this way we can bake template with properly naming all of these lfos and other modulators and just use one CV-MAP module with one expander. I mean those labels which are showing in context menu, as for now look like Input 01 - Port 1 Channel one. 

Or we can use many of desired CV-MAP but grouping them by function and naming porst like LFO 1\4, LFO 400hz in one CV-map and something different with EG short attack short decay or smth. It would be much faster to understand by user while he's in context menu to show what exactly parameter for "virtual cabling" he needs to map up. 

Otherwise I really like all the functions and workaround, it can blow up the VCV community very well ;-) Thanks for your hard work!

**Comment by stoermelder** [comment]
I think this is a very good idea but it needs to be done differently than MIDI-CAT: The custom labels need to be applied to the input channels and not to the mapping slots. Need to think how to add this in a nice way, maybe by context menu on the input ports like MACRO has them on the output ports.

**Comment by stoermelder** [comment]
So, done!

**Comment by vcvrackideas** [comment]
wow Ben, it's very cool. Sorry for be annoying but ;-) is there a possible way to type more than 2 symbols to the expander? In the way of user thinking (sorting thinking) like - RANDOM, or SYNCED and etc

**Comment by vcvrackideas** [comment]
I found possible bug or just not obvious behavior. For example we have two instances of CV-MAP with two expanders with different labels in one patch. I have already mapped parameter to expander one. But when I need to try different slot of the same module there is no this first expander in right click menu, only second is available for new mapping for already mapped parameter. Both are available only when I unmap the parameter completely.

**Comment by stoermelder** [comment]
I rotated the display for up to 8 characters. But I think this is it for now, I'm trying to finally get a new release ready, much writing manuals is still needed.

**Comment by vcvrackideas** [comment]
And this is more than enough for cable free patching. Thanks Ben!

**Comment by stoermelder** [comment]
I'm closing this for now. Feel free to open a new issue if you have more ideas.
