### ISSUE TITLE
right click context menu or trig in for glue

### ISSUE THREAD

**Issue by joopvdl** [stoermelder/vcvrack-packone#257]
Now that Midi Cat has been enhanced with a right click context menu thing, which is a great addition, could you also implement that for glue? So that you can just right click any module, and a label appears?
If that's not possible, could glue get a trigger input, so you can assign a hotkey to it?
Now, I always have to scroll back to where the glue module is, in order to press the button, and then back to the module I want labeled. Which is a bit impractical on large patches (and mine always end up large, that's why I need the labeling)
Thanks, Joop

**Comment by stoermelder** [comment]
You are aware that there is already hotkey CTRL+A for adding labels?

**Comment by joopvdl** [comment]
Ah! No, I wasn't. So that's it! Thank you for that.
