### ISSUE TITLE
8FACE with MIDI-CAT - Only overwrites mappings

### ISSUE THREAD

**Issue by AmateurExpert** [stoermelder/vcvrack-packone#259]
When using 8FACE to select presets for MIDI-CAT, it appears as if it only overwrites the mapping slots.  This means that if you have a preset loaded with 20 mappings and then select another preset with lets say 10 mappings, the first 10 mapping slots will be the newly loaded preset, but the last ten mapping slots will remain from the previous preset.

I would have expected that loading a new preset would in effect clear all mappings that MIDI-CAT has and then load the new preset resulting in a 'clean' preset not polluted with mappings from other presets.

Hopefully what I've written makes some sense :)

**Comment by stoermelder** [comment]
Well, it is "by-design", kind of. MIDI-CAT supports partial presets which is useful in some cases, but I understand it won't be the behavior you would expect in other cases. I added an additional context menu option in the latest buid.

**Comment by AmateurExpert** [comment]
Wow, the response time is impressive :)
Am I understanding correctly that a context menu item will grant me the behaviour I would expect ?
Which context menu item is that ? 
Is the latest build what is available via the library management within VCV Rack ?

Sorry for all the questions :)

**Comment by AmateurExpert** [comment]
After a little more testing, perhaps you closed this a little quickly:

1. Create a preset with 8 mappings (we'll call it p1)
This preset can be saved as a preset via the preset menu item or recorded using 8FACE.
2. Initialize MIDI-CAT
3.  Create a preset with 3 mappings (we'll call it p2)
This preset can be saved as a preset via the preset menu item or recorded using 8FACE.

Now regardless of which method you used to call the preset (via MIDI-CAT preset menu or 8FACE) load p1 then load p2.
Now the first 3 mappings are what we mapped in p2.
The fourth mapping is broken, it shows the little yellow mapping symbol on the mapped control from p1, the mapping in MIDI-CAT however has no control mapped to it.
The rest of the p1 mappings are still mapped and function.

I haven't found a context menu item that I can switch to tell MIDI-CAT to clean all mappings before loading another preset.

**Comment by stoermelder** [comment]
The menu item is called "Preset load" -> "Clear mapping slots". The development build is available here:
https://github.com/stoermelder/vcvrack-packone/releases/tag/Nightly

![image](https://user-images.githubusercontent.com/47640667/120005541-3819fb00-bfd8-11eb-80a2-c8e173e4c81b.png)

**Comment by AmateurExpert** [comment]
Just tried it out.  Works great ! :)
You just have to make sure that you set the 'Clear mapping slots' switch before you save the preset ;)

Thanks!  wicked fast :)

**Comment by AmateurExpert** [comment]
Sorry to bother once more...
After playing with it a bit, loading presets using the preset context menu, everything loads fine.  However, when using 8FACE to switch between presets, some mappings go missing.  It seems the preset mapping in 8face is intact because simply switching back and forth between presets shows different mappings disappearing, sometimes(rarely) they all show up.  The effect is worsened as the number of mappings increase.
