### ISSUE TITLE
MIDI-CAT/8FACE - unreliable mapping on preset-load

### ISSUE THREAD

**Issue by stoermelder** [stoermelder/vcvrack-packone#261]
Sorry to bother once more...
After playing with it a bit, loading presets using the preset context menu, everything loads fine.  However, when using 8FACE to switch between presets, some mappings go missing.  It seems the preset mapping in 8face is intact because simply switching back and forth between presets shows different mappings disappearing, sometimes(rarely) they all show up.  The effect is worsened as the number of mappings increase.

_Originally posted by @AmateurExpert in https://github.com/stoermelder/vcvrack-packone/issues/259#issuecomment-850536143_

**Comment by stoermelder** [comment]
I think this was reported before, by @vcvrackideas I guess?
I did a minor change, maybe this fixes it, I didn't test it though. You can try it as soon the automatic build is ready, taking longer than usual right now.

**Comment by stoermelder** [comment]
@AmateurExpert any feedback on this?

**Comment by AmateurExpert** [comment]
The presets seem to load ok now.  I cycled back and forth between two different presets more times than i care to count, and there were no missing mappings.  *thumbs up*

**Comment by stoermelder** [comment]
Thanks!
