### ISSUE TITLE
Stroke: Clicking on a non-parameter space zeros the copied value.

### ISSUE THREAD

**Issue by Chaircrusher** [stoermelder/vcvrack-packone#273]
Ran into this - it seems to be a change in behavior after the last version release.
I map 'A' to parameter copy and 'S' to parameter paste.

If I hit 'A' with the mouse cursor over a slider (or whatever) it will pick up the value, and I can hit 'S" and paste it to a different parameter.

But if I hit 'A' with the mouse cursor not over any control (on the Rack background or on a module panel not hovering over any control) then hit 'S' on a control, it 'pastes' a value of zero.

Is this intentional?

EDIT: clicking "Parameter Paste" not on any control does the same thing: sets the copied value to zero.

**Comment by stoermelder** [comment]
No, not an intentional change, caused by re-write of the internals to support "multi-step" commands.
It should now work as expected again.

**Comment by Chaircrusher** [comment]
thanks!
