### ISSUE TITLE
CTRL

### ISSUE THREAD

**Issue by stoermelder** [stoermelder/vcvrack-packone#279]
https://community.vcvrack.com/t/stoermelders-idea-und-development-thread/10515/320
Collecting ideas for a "flexible control surface module". 
No promises it will ever be implemented but thinking about its concept won't hurt.

**Comment by stoermelder** [comment]
A few thoughts.
- _Controls_ should not be "standard" parameters but custom widgets. This allows any number of controls, in contrast all module's parameters must be known at the moment the module is added to the patch.
- _Controls_ do have a "target", could be
  - Parameter mapping: modifies a parameter within the patch, scaling-options like CV-MAP will be handy.
  - MIDI: the device is selected and configured by an expander module, multiple MIDI targets should be possible. Scaling etc. like MIDI-CAT will be useful.
  - CV: output ports can be added by an expander.
- Basic _Controls_ needed: trimpot, knob, big knob, switch, button, fader.
- _Labels_ for labeling _Controls_, something like GLUE's labels.

On the other hand, all these things can already be built with existing modules, except for the flexible surface.

**Comment by DaveBenham** [comment]
I would love to have such a module. I have been independently thinking about the need for such a thing!

**Comment by stoermelder** [comment]
I'm closing this as there is now a module for this:
https://community.vcvrack.com/t/introducing-mindmeld-patchmaster-and-routemasters/18812
