### ISSUE TITLE
Apply MIDI-CAT MEM settings via mouse hover and MIDI CC

### ISSUE THREAD

**Issue by marcaddeo** [stoermelder/vcvrack-packone#281]
Is it possible to apply memory settings to MIDI-CAT by hovering over a module and pressing a MIDI button on my controller?

For example, I'd like to create mappings for each module and store them to memory. Then I'd like to be able to hover over a module (kind of like SAIL) and hit a MIDI button and have it apply that modules MIDI mappings.

Not sure if it's currently possible with the current set of PackOne plugins, but would love to see it added.

Thanks

**Comment by stoermelder** [comment]
This is already possible: You can map the "Apply" button to a MIDI control (with a second MIDI-CAT) and apply a preset to the hovered module.
