### ISSUE TITLE
Orbit - Level Control

### ISSUE THREAD

**Issue by omricohenmusic** [stoermelder/vcvrack-packone#286]
Hi Ben!

It would be great if there could be a level control on Orbit to attenuate a bit the polyphonic signals. Poly signals are usually very hot and it's better to attenuate them already from Orbit itself for better gain staging. What do you think?

Thanks again!

**Comment by stoermelder** [comment]
Hi Omri, you mean if downmixing to a monophonic signal is enabled? Currently, the channels are simply summed after the panning and this signal can be get quite hot indeed.

**Comment by omricohenmusic** [comment]
Hi,Well, I guess that I mean a simple level control over the output gain, never mind if it's polyphonic or not. Something similar to the mockba spreader.Thanks!On Aug 7, 2021 19:25, Ben ***@***.***> wrote:
Hi Omri, you mean if downmixing to a monophonic signal is enabled? Currently, the channels are simply summed after the panning and this signal can be get quite hot indeed.

**Comment by stoermelder** [comment]
Added.
