### ISSUE TITLE
8Face controlling 8Face

### ISSUE THREAD

**Issue by Chaircrusher** [stoermelder/vcvrack-packone#29]
Obviously an infinite regress of 8Face is a chance for exponential explosion but...

I experimented with an 8Face taking snapshots of an 8 face, which in a perfect world, would be a 64Face (8 snapshots of 8 snapshots of the adjacent module).

It doesn't seem to work, at least when I played with it controlling a Skylights Alan Turing sequencer.

It seems like the leftmost 8Face doesn't change presets when the  8Face to its right changes it. 

One suggestion: If the preset changes for an 8face, it should propogate a preset change to the module it's controlling.

**Comment by stoermelder** [comment]
Hi Kent,
yes, that's right, 8FACE does not apply presets on loading, because you could have made manual changes on the controlled module and I don't want overwrite them without asking. I could add an option "Apply preset on load", but which preset should be loaded? The first slot?

**Comment by Chaircrusher** [comment]
I see the issue, so yeah propogating through preset changes might be a terrible idea.

My simplest possible patch to verify 8face controlling 8face appears to work, with the Specific Value module. Patch [attached.](url
[8face-FMVoices.vcv.zip](https://github.com/stoermelder/vcvrack-packone/files/3418331/8face-FMVoices.vcv.zip)

)

Changing presets in Skylights Turing Machine might not really be as easy to 'hear' or see that the change is working.

**Comment by stoermelder** [comment]
Yes, using Turing Machine is not the best module the verify it's working as expected :-) I used VCV 8vert as controlled module and it seems ok, 8FACE storing presets of 8FACE.
Is it ok then or do you think an option for "autoloading" presets could be useful?

**Comment by Chaircrusher** [comment]
I think it's a good idea as an option but probably not as a default behavior.

**Comment by stoermelder** [comment]
Added an Option to autoload the first preset slot on load. Should be enough for now.
Feel free to comment on this and I reopen if necessary.

**Comment by mosesve** [comment]
Hi Ben,

sorry to reopen this issue, but I think "Autoload first preset" does not work.
Additionally even when the first preset is triggered afterwards by setting the slot mode to "random" the preset will not load.
See attached Strip, the trigger switches the first 8face forward and the second one randomly with a delay - that works with preset 2-4 (12,13,14 and 22,23,24 on the submarine TD-202) but not with the first one (11, 21) if it is randomly selected.

[8facedBug.zip](https://github.com/stoermelder/vcvrack-packone/files/6285790/8facedBug.zip)

**Comment by stoermelder** [comment]
Thanks for reporting, "Autoload first preset" was indeed broken. I think it will also work with "random mode" now, can you confirm?

**Comment by mosesve** [comment]
"Autoload first preset" is working now. Thanks for the quick fix. 
But you may want to revisit the behavior when an 8Face is loaded without autoload activated. 
It always lights up the preset slot that was active when saving the preset without activating it. When an incoming trigger switches the preset to random or next, that will activate it, but not if it is the lit preset and there is at the moment no option to activate the saved active preset.
Maybe you could add another option "Autoload saved active preset"?

**Comment by stoermelder** [comment]
I added such an option a few moments ago as it was an easy change. 
I'm not sure what you are trying to achieve but maybe you want to take a look at 8FACE mk2 whose number of preset slots can be extended with multiple "+8" modules.

**Comment by mosesve** [comment]
Brilliant! Thanks a lot.
I am essentially rebuilding Harmonaig, but for scale quantisation. Kind of like a "chord and scale suggestion apparatus". I don't need more presets, but a multiplication of presets, so I use four 8face in a row (1st 8face² -> Modal Selection / 2nd 8face² -> Root Note / 3rd 8face -> Chord Type / 4th 8face -> possible scales programmed into quantum). I will release the patch to my forum-posting when finished, that should explain it a lot better ;-) Thanks again!
