### ISSUE TITLE
8Face Mk2 select controlled modules like MIDI-CAT

### ISSUE THREAD

**Issue by Chaircrusher** [stoermelder/vcvrack-packone#291]
When you want to map a bunch of keys in MIDI-CAT you click 'map' in the module and then you can keep clicking controls and MIDI notes/controllers until you click outside a module.  In other words, you can click 'map' and map your entire midi keyboard if you want.

So MIDI-CAT you click 'Map' once, and map multiple controls.
8Face Mk2 you choose 'Bind Module (select) but you can't select multiple modules.

With 8Face Mk2 It would be great if when you right click and choose "Bind Module (select)" if you could select more than one module at a time.

**Comment by stoermelder** [comment]
I added a new context menu item "Bind module (select multiple)" for this.
