### ISSUE TITLE
v2-dev - 8Face mk2 builds but doesn't appear to work at all.

### ISSUE THREAD

**Issue by Chaircrusher** [stoermelder/vcvrack-packone#293]
Subject line says it all. I grabbed the source, checked out V2 branch, built and installed it, and tried to use 8face mk2 to control two JW-Modules NoteSeqFu modules. These work perfectly with 8Face Mk2 in 1.0

Windows 11
Build from source Rack 219bbaf137d5dc70c96bd4206c3f8aad5524a81b
packone git SHA commit 4b4e6f98b9545c1607303c535e61e3621c44fd11 (HEAD -> v2-dev, origin/v2-dev)

**Comment by SteveRussell33** [comment]
Do you have an example patch?

**Comment by Chaircrusher** [comment]
Yes. 
https://cornwarning.com/xfer/VCV/2021-11-12.vcv

**Comment by stoermelder** [comment]
Fixed in 05de80494e57fa22ed9aec37cba9178a7c8e60c5.
