### ISSUE TITLE
Strip doesn't work with very last Rack2 sdk

### ISSUE THREAD

**Issue by vcvrackideas** [stoermelder/vcvrack-packone#295]
Hi Ben! It seems doesn't react on open folder command and also when loading previously saved strip rack is crashing.
I wrote you previosly about midi mapping and saving selections and you told me that saving mapping in selection wouldn't be possible because adressing is lost while saving selections in Rack2. So now I'm trying to use Strip for that purpose but it doesn't work yet

**Comment by ThePython10110** [comment]
I know I'm not Ben, but I'm just looking at this and have some questions:
When you say that Strip "doesn't work yet," what do you mean? Is it not building? Is there a missing button? 

Are you on the v2-dev branch?
Does the version number in plugin.json start with 2?
Does your Rack version match your SDK version?

If the answer is no, the problem has been found (hopefully)...

**Comment by stoermelder** [comment]
I think this issue is obsolete in the meantime.
