### ISSUE TITLE
Enhancement: using 8FACE to switch GLUE labels

### ISSUE THREAD

**Issue by coax75ohm** [stoermelder/vcvrack-packone#298]
It would be nice if you could use 8FACE to switch GLUE labels along with other settings.

I managed to work around it by toggling the GLUE hide switches since I only needed two sets of labels currently. This works aside from STRIP not saving the 8FACE settings, but that only takes a second to redo.

![Screenshot 1](https://user-images.githubusercontent.com/577587/143657402-f2583a15-7ee1-4be1-80a1-40ffc440c23d.png)
![Screenshot 2](https://user-images.githubusercontent.com/577587/143657404-4b235af3-c1e4-4bbe-9650-82422c58ba8b.png)

**Comment by stoermelder** [comment]
This is working with the current build. The problem was I prevented loading presets into GLUE for some reason, but this restriction was removed some time ago.
