### ISSUE TITLE
Quantized Midi-Cat

### ISSUE THREAD

**Issue by thorinside** [stoermelder/vcvrack-packone#299]
I have a midi controller with a bunch of buttons that light up when they are pressed. So I thought it'd be cool to use them for mutes, but quantizing the mutes to a clock. So, pushing a button, would arm a sample and hold, which would send a gate or trigger for the armed channels when the clock fires.

The module Mesoglea from ExtraTone almost does this. However I have to use it when MidiCat is in 'Momentary' mode. And then my midi controller doesn't light up. This lighting up is important to me because I want to be able to perform a patch and know which channels are muted without having to look at my screen.

Omri and I have been chatting about this, and I've found a few solutions, but I guess he thought I should talk to you and see if there's a way to accomplish something like this with your modules?

One idea might be: If Midi-Cat had a mode that was a cross between momentary and toggle, something that would send a trigger but also give midi feedback to the controller as if it was toggling, so that the light would stay on, then I could use Mesoglea and my lights would behave as I want.

Another idea might be: Make an extender for Midi-Cat that would have a sample and hold, so it would only pass the signals to connected modules when the trigger happens. Basically a buffer that would arm, and only send the actual signal when there is a clock. Though, to be honest, I'm not sure how this would solve my lights issue. Maybe it could send midi feedback, for example flash the light (itermittently send back the note) while the channel is armed, and then send a constant Note ON when the note is sent because of the S/H trigger.

Really, all I'd like to do is start a discussion about this with you, because it seems that supporting something like this for some of these midi controllers that only light up when they receive NOTE ON back seems like it'd be useful. And often we want to have things happen on clock triggers instead of immediately. Any ideas you might be able to give me? Am I making any sense?

For some background info, here's a couple of videos showing what I'm up against:

1) https://share.descript.com/view/ie1IoeafdXw
2) https://share.descript.com/view/bce9uq30wrC

**Comment by stoermelder** [comment]
Are you still interested in this?  
I thought about it and an expander for clock-input(s) used for sample and hold could be useful. I see two simple modes at the moment:
- Arm with immediate MIDI feedback, apply the value on the parameter on the next clock
- Arm with deferred MIDI feedback, apply the value on the parameter on the next clock and then send MIDI feedback
There are potentially more options, like blinking or sending some other MIDI message for e.g. different colors, depending of the controller. But I'd like to have these later.

**Comment by thorinside** [comment]
Very much still interested. I use a Xone-K2 and would love to have either
of these or both. Happy to help test.

**Comment by stoermelder** [comment]
I added a new expander MIDI-CAT CLK for that purpose. It is not fully tested but it seems to work quite ok for the moment.

![image](https://user-images.githubusercontent.com/47640667/205181771-dedf1bd6-8c5f-4ee0-a6d5-3103922f5e4c.png)

**Comment by thorinside** [comment]
Wow, amazing. I'll have a look.

**Comment by thorinside** [comment]
I've had a look and it works great for me. Thanks so much for adding such a useful feature!
