### ISSUE TITLE
NYSTHI 4MIX - 16MIX mixers

### ISSUE THREAD

**Issue by BoscoRemus** [stoermelder/vcvrack-packone#3]
Can not map the color faders or color pans in the NYSTHI 4MIX - 16MIX mixers..

**Comment by stoermelder** [comment]
Hm, I think Antonio of NYSTHI implemented his own faders that aren't exposed as parameters to Rack. I tried VCV MIDI-MAP and it doesn't work either.

Edit: Saw you issue. I can't do anything about it when a module uses its own logic. Sorry...
https://github.com/nysthi/nysthi/issues/195
