### ISSUE TITLE
Not building....

### ISSUE THREAD

**Issue by ThePython10110** [stoermelder/vcvrack-packone#300]
I am on Windows 10, trying to build this for Rack v2.beta.1. I managed to fix some of the errors, but not this one. It seems that `rack::string::fuzzyScore` has been removed. After searching through the API, I haven't found an obvious replacement, meaning that this happens:
```
src/mb/Mb_v1.cpp:47:31: error: 'fuzzyScore' is not a member of 'rack::string'
   47 |         float score = string::fuzzyScore(string::lowercase(s), string::lowercase(search));
      |                               ^~~~~~~~~~
make: *** [C:\msys64\home\Nolan\Rack-SDK/compile.mk:72: build/src/mb/Mb_v1.cpp.o] Error 1
```

**Comment by stoermelder** [comment]
Thanks, I close this.
