### ISSUE TITLE
v2: Reference to custom fonts stored across frames

### ISSUE THREAD

**Issue by cschol** [stoermelder/vcvrack-packone#303]
**I know this is a work in progress, but we have had issues with plugins crashing the VST and I wanted to point this out early.**

Your plugin stores references to custom fonts across frames. This leads to crashes in the VST when reloading a project.

For example (but there might be others):
```
LabelDrawWidget() {
    font[0] = APP->window->loadFont(asset::system("res/fonts/ShareTechMono-Regular.ttf"));
    font[1] = APP->window->loadFont(asset::plugin(pluginInstance, "res/fonts/RedkostComic.otf"));
}
```

Please see the following link on how to resolve this issue and re-submit to the Library:
https://vcvrack.com/manual/Migrate2#2-1-Don-t-store-Font-and-Image-references-across-multiple-frames

**Comment by stoermelder** [comment]
Thanks.
