### ISSUE TITLE
MIDI-CAT v2 bug

### ISSUE THREAD

**Issue by ContemporaryInsanity** [stoermelder/vcvrack-packone#304]
MIDI-CAT appears to work fine on v2 unless you re-initialise it which crashes rack instantly, attempting to restart rack thereafter also crashes instantly.

[19918:19918:0100/000000.669378:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
terminate called after throwing an instance of 'rack::Exception'
  what():  pthread_rwlock_wrlock failed
Aborted (core dumped)

[3085.267 fatal adapters/standalone.cpp:60 fatalSignalHandler] Fatal signal 6 SIGABORTED. Stack trace:
20: ./Rack() [0x403ccf]
19: /lib/x86_64-linux-gnu/libc.so.6(+0x3f040) [0x7f5e729c5040]
18: /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7) [0x7f5e729c4fb7]
17: /lib/x86_64-linux-gnu/libc.so.6(abort+0x141) [0x7f5e729c6921]
16: ./libRack.so(+0x288fbe) [0x7f5e7339dfbe]
15: ./libRack.so(_ZN10__cxxabiv111__terminateEPFvvE+0x6) [0x7f5e738b92c6]
14: ./libRack.so(+0x7a4331) [0x7f5e738b9331]
13: ./libRack.so(+0x7a4484) [0x7f5e738b9484]
12: ./libRack.so(+0x28667a) [0x7f5e7339b67a]
11: /home/ewen/.Rack2/plugins/Stoermelder-P1/plugin.so(_ZN18StoermelderPackOne7MidiCat13MidiCatModule7onResetEv+0x11a) [0x7f5e423d942a]
10: ./libRack.so(_ZN4rack6engine6Engine11resetModuleEPNS0_6ModuleE+0x3b) [0x7f5e734d960b]
9: ./libRack.so(_ZN4rack3app12ModuleWidget11resetActionEv+0xac) [0x7f5e7349efdc]
8: ./libRack.so(_ZZN4rack14createMenuItemINS_2ui8MenuItemEEEPT_NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESA_St8functionIFvvEEbbEN4Item8onActionERKNS_6widget6Widget11ActionEventE+0x23) [0x7f5e73448f53]
7: ./libRack.so(_ZN4rack2ui8MenuItem8doActionEb+0x5b) [0x7f5e7344e67b]
6: ./libRack.so(_ZN4rack6widget10EventState12handleButtonENS_4math3VecEiii+0x2f6) [0x7f5e734d6e66]
5: ./libRack.so(_glfwPlatformPollEvents+0xd2a) [0x7f5e735275da]
4: ./libRack.so(_ZN4rack6window6Window4stepEv+0x4f) [0x7f5e734774bf]
3: ./libRack.so(_ZN4rack6window6Window3runEv+0x18) [0x7f5e73477e08]
2: ./Rack(main+0xa78) [0x4037a8]
1: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f5e729a7bf7]
0: ./Rack() [0x403aa9]

**Comment by stoermelder** [comment]
Closing, reported on a fork not maintained by me and can’t be reproduced on my code.
