### ISSUE TITLE
Midi-Cat - broke "pick-up jump" with snapped parameters

### ISSUE THREAD

**Issue by matthleg** [stoermelder/vcvrack-packone#308]
Hi,
I found a specific bug (in v2) and I am not sure it is from you or from Nysthi...
When I map the octave knobs of musical box with midi-cat ( in mode pick-up jump) it doesn't work...
But it is working for all the other knobs, and it is working if it isn't with pick-up jump...
Strange.
I am using win11.
Have a nice day
and thanks again for your amazing collection.
Matthieu

**Comment by matthleg** [comment]
Hi, I found that the bug is with all the knobs going by step (and not smoothly) like the octave knob of evenvco or the knob for  number of step of sequential switch... 
Matthieu

**Comment by stoermelder** [comment]
Thanks for reporting, this should be working now.

**Comment by matthleg** [comment]
Hi Ben, happy to see  that you are still here, I was afraid that  you abandon your work with vcv... And your module are for me essential to work with vcv!!! So thank you so much for your work.
