### ISSUE TITLE
module Suggestion for 8Face

### ISSUE THREAD

**Issue by GenCode00** [stoermelder/vcvrack-packone#310]
8Face would benefit greatly if there was plugin/module that could connect into 8Face's slot input and would have same amount of variation buttons as 8Face , 8 currently . purpose of this plug in wold be to trigger exactly variation number you'd want on multiple 8Faces . lets say after variation 2 you  want to select variation 8 or 3 etc on multiple devices at the same time.
i haven't yet looked into other  plugins of yours which look very useful to me but i'm glad that i discovered Stoermelder. 
will definitely become contributor . hope your modules will be available for rack 2

**Comment by stoermelder** [comment]
This is already possible with 8FACE mk2.
https://github.com/stoermelder/vcvrack-packone/blob/v1/docs/EightFaceMk2.md
