### ISSUE TITLE
can't find/install any plugins/modules from the VCV library

### ISSUE THREAD

**Issue by alefnull** [stoermelder/vcvrack-packone#313]
starting to wonder if i'm just going crazy or doing something wrong, but i cannot find any of these modules in the VCV library.

**Comment by stoermelder** [comment]
https://community.vcvrack.com/t/stoermelders-idea-und-development-thread/10515/401

**Comment by alefnull** [comment]
my mistake. thank you for the link.

**Comment by stoermelder** [comment]
It is on the way and will arrive soon.
https://github.com/VCVRack/library/issues/560#issuecomment-1321237385
