### ISSUE TITLE
Remove .Rack 2.0.4 vst Phase extremely hi CPU Usage

### ISSUE THREAD

**Issue by GenCode00** [stoermelder/vcvrack-packone#315]
if i use phase input it maxes out cpu to freeze completely with nothing else but 1 osc  and mixer in a project . nothing else in a DAW
running ,. no effect or other vsts . its working fine in Rack v1  1% usage . stand alone Rack 2.0.4 its not working at all . can't even engage record button .

**Comment by GenCode00** [comment]
its on Mac . forgot to mention

**Comment by stoermelder** [comment]
Duplicate of #306.
