### ISSUE TITLE
Crashes opening patches using Transit or 8face

### ISSUE THREAD

**Issue by W4too** [stoermelder/vcvrack-packone#316]
Hi Ben

I get crashes opening patches with 8face or Transit with the slot ports linked (to a MIDI-CV module or an internal CV sequencer like BogAudio AADR for instance).
The crash probability gets bigger as the number of modules connected to 8face or transit grows.

For now the only way i found to get around this issue is to deactivate the audio-module before saving, but it clearly seems related to these modules (if i remove PackOne from the library, i can reopen the faulty patches).

I could reproduce this issue on two different computers (a laptop and a desktop [ryzen 9 5950x]).

I still can reopen this one : 
![8_face](https://user-images.githubusercontent.com/100092785/154860633-388713f4-6467-4398-83bb-9db4051612dd.jpg)

But with 2 Palettes more, i get automatically a crash :
![8_face_pos3](https://user-images.githubusercontent.com/100092785/154860604-f3727739-ca2a-4ebe-87e5-d762ea6b7a0d.jpg)

Here's the log file related to the faulty patch
[log.txt](https://github.com/stoermelder/vcvrack-packone/files/8104799/log.txt)

And two patches (one working and one faulty) : 
[test1.zip](https://github.com/stoermelder/vcvrack-packone/files/8104805/test1.zip)

Thanks

**Comment by stoermelder** [comment]
Thanks for reporting. Can you try it with the latest build if your patch loads without crash?

**Comment by W4too** [comment]
Hi,

It seems to work very well now with this new build.
Thank you very much for the quick fix.

Cheers.

----- Mail original -----
De: "Ben" ***@***.***>
À: "stoermelder/vcvrack-packone" ***@***.***>
Cc: "W4too" ***@***.***>, "Author" ***@***.***>
Envoyé: Mardi 22 Février 2022 07:26:40
Objet: Re: [stoermelder/vcvrack-packone] Crashes opening patches using Transit or 8face (Issue #316)





Thanks for reporting. Can you try it with the latest build if your patch loads without crash? 

— 
Reply to this email directly, view it on GitHub , or unsubscribe . 
Triage notifications on the go with GitHub Mobile for iOS or Android .
