### ISSUE TITLE
I'm dumb.... how do you install these?

### ISSUE THREAD

**Issue by loiteringsloth** [stoermelder/vcvrack-packone#318]
I've tried just adding from the VCV library page, tried just subscribing from the same page, tried manually adding the folder to \Documents\Rack2\Plugins.

No matter what I do none of them show up in VCVrack. Using 2.06, free version on Windows 10

Thanks,
-Brian

**Comment by Petervos2018** [comment]
go here https://github.com/stoermelder/vcvrack-packone/releases/tag/Nightly 

download the right one : 

![afbeelding](https://user-images.githubusercontent.com/46076474/160203132-2415e0c5-c878-444a-9e92-6984c80ba2d9.png)

And put it in the right folder \Documents\Rack2\Plugins.

Start VCV rack.

**Comment by loiteringsloth** [comment]
Working now, I guess I downloaded the wrong file. Thank you!

**Comment by stoermelder** [comment]
It is on the way and will arrive soon.
https://github.com/VCVRack/library/issues/560#issuecomment-1321237385
