### ISSUE TITLE
8Face => "presetCount": 8 <=, gets changed to another number in the patch.json "autosave"

### ISSUE THREAD

**Issue by jaynothin** [stoermelder/vcvrack-packone#319]
I cannot reproduce this issue at will, but it randomly occurs often enough to be annoying as I am performing LIVE.
It happened in the very first minute of setting up and using it, (example below), as well as well within a few hours of performing.
And even after applying the "fix", it bugged again later on. So it really looks random to me. 

8Face "presetCount": 8, gets changed to another number in the patch.json "autosave" - bug

Windows 10 21H2
VCV 2.1.0
Stoermelder-P1-2.0.281202a-win-20220222.vcvplugin

I'm using my MIDI controller's 8 pads, (Oxygen61 from M-Audio), to go thru and change the 8Face presets.

Nothing fancy here as pads are only note numbers sent thru MIDI channel 10.
![M-Audio Pads-small](https://user-images.githubusercontent.com/74117050/163684986-7cd0e48d-d1ac-465a-9836-47e645c50e28.jpg)

I'm setting up MIDI-CAT to map the pads to the 8Face, (same thing is happening with 8FaceMKII).

The unused presets are a healthy dark green ready to be "assigned". 
![MIDI-CAT-to-8Face-small](https://user-images.githubusercontent.com/74117050/163685354-e35052aa-cdc9-4367-937c-f8ea824f063e.png)

So far so good, I can now perform and change 8Face presets hitting my controller's pads.

But then, randomly it would seem, this happens:
Some presets become unavailable and nothing I do seems to re-enable them. They become unresponsive and useless.
It's weird because it's not even a feature, to the best of my knowledge,? 🤔

In the image below you can see that the presets are now dark/black.
![8Face-bug-medium](https://user-images.githubusercontent.com/74117050/163685430-5f7e9ba0-aa16-4e7c-ab4a-696c356762ea.png)

So I did some digging, and opened up the autosaved patch.json, and I found that the string "presetCount": 8, compare to another 8Face in the patch, has been changed to another number.

In this case 2, but it's a different number on other occasions.
![presetCount-bug](https://user-images.githubusercontent.com/74117050/163685765-f9562638-85d1-451c-b03e-951d16aedc1c.png)

So I can fix it, temporarily, by changing "presetCount": back to 8, save the patch.json, then reopen VCV and it's back to normal, and the presets aren't lost. 

I didn't test this with VCV MIDI-MAP, so I can't say if it's MIDI-CAT specific or if it's something else. 🤷
But every time I get this "bug", MIDI-CAT was present and mapped to 8FACE.

Sorry if this is too long for reporting an issue ;) I'll try and get better next time :P

**Comment by stoermelder** [comment]
This is a feature that you are most probably not aware of: Long-pressing one of the buttons sets the number of active presets. If it "happens" you can long-press on the 8th preset button which will enable all preset slots.
Let me know if this clears things up...

**Comment by jaynothin** [comment]
Ohhhhhhhhh
Now I feel like a total fool 🤦 

I just tried and held a pad, and I saw it change before my eyes. 🤯 

I guess, if possible, we should delete my post? Seriously.

Thank you so much :D

**Comment by stoermelder** [comment]
No problem, let's just close the issue ;-)
I'm glad I could help!
