### ISSUE TITLE
Add MIDI tag to MIDI-CAT

### ISSUE THREAD

**Issue by dheles** [stoermelder/vcvrack-packone#32]
Testing out your very useful MIDI-CAT module from the current nightly build, I noticed it doesn't yet have the MIDI tag, so it doesn't show up in the plugin browser when I'm filtering for them.

**Comment by stoermelder** [comment]
Please be aware that this module is not finished yet.

**Comment by stoermelder** [comment]
Fixed in b52912d7dc25dc9b4d42e2330970a20af0315172.
