### ISSUE TITLE
Suggestion: Add back to VCV Rack Library

### ISSUE THREAD

**Issue by ThePython10110** [stoermelder/vcvrack-packone#320]
I'm only really suggesting this because it makes it easy to install and update, not because I personally need it.
I just think it would be nice.

**Comment by stoermelder** [comment]
The plugin and modules have not been removed from the VCV Library, but there is no version for Rack v2 available yet.

**Comment by stoermelder** [comment]
It is on the way and will arrive soon.
https://github.com/VCVRack/library/issues/560#issuecomment-1321237385
