### ISSUE TITLE
Installed nightly release but just get Glue

### ISSUE THREAD

**Issue by flcc** [stoermelder/vcvrack-packone#321]
Hi
Hope it's the right place.
I've intalled the plugin from the nightly build page.
OSX version.
It work since I get Glue. But I just get Glue. No others modules.

An idea ?

Cheers

**Comment by Petervos2018** [comment]
Ok try this :  

Go here https://library.vcvrack.com/plugins

Scroll down until you see this : 

![afbeelding](https://user-images.githubusercontent.com/46076474/167271961-d3be99e9-a197-4a5a-b76c-ccc04213c6ea.png)

Choose Remove all, and also remove the stoermelder pack1 folder from your hdd.
Start Rack,
Close rack

In the Library choose "Subscribe" for the stoermelder plug-in.

Put your downloaded nightly build in the Rack2 plug-in folder as you did before.

Restart rack, and they should all be there.

**Comment by flcc** [comment]
Superb, it works
In fact I wanted to try this solution, but I couldn't find any stoermeleder, CV-Map, Glue etc...
Why ?
Because when the PackOne section is closed, neither the site search nor the firefox search find them. I didn't think to look for PackOne. I deduced that this brand was no longer listed.
It's dumb, isn't it ?
Anyway thank you very much for you help
And double thanks for the speed of your reply
