### ISSUE TITLE
License change to GPL-3.0-or-later

### ISSUE THREAD

**Issue by offthesky** [stoermelder/vcvrack-packone#322]
i think it's safe to say the stoermelder modules are some of the best modules there ever were! i teach private classes - intro to modular/advanced patching using the great free cardinal vcv platform ( https://github.com/DISTRHO/Cardinal ).  but cardinal has strict guidelines for adding in new sets of modules, in that the licenses need to be "GPL-3.0-or-later" to future proof.  is there any chance that this could be possible to get the license updated for stoermelder?  would especially love to have the glue module to create notes all over patches; priceless in patches when teaching (not to mention umap, remove, strip 8face.. et al. absolutely priceless additions regardless !). hope this message in a bottle finds you. tia!!!

and srsly, thanks again for creating all these in the first place w all the fun and interesting sounds they provided :]

**Comment by subderground** [comment]
Yes, your Glue module is a must have... We can't have it in Cardinal rack. If you don't want to modify the Licence, maybe could you check the projet and perhaps add a labels/stickers module/possibilty to Cardinal rack ? That would be cool !  
Have a great day. :-)  T.

**Comment by stoermelder** [comment]
As far as I am aware of all contributors to this repository must agree with a licence change.
@xandramax @kant @jatinchowdhury18 @nateallen-wk, if you don't agree please let me know.

**Comment by jatinchowdhury18** [comment]
I will happily agree with whatever decision you and the other contributors make regarding license changes!

**Comment by xandramax** [comment]
You have my approval.

**Comment by offthesky** [comment]
almost half way there :] super great/exciting. thank you all for taking the time to consider this one!! <3

**Comment by stoermelder** [comment]
As there was no objection during the last two month, I proceed with the licence change...

**Comment by kant** [comment]
You have my approval!
