### ISSUE TITLE
Limited number of modules loaded on Linux

### ISSUE THREAD

**Issue by Donmanouche** [stoermelder/vcvrack-packone#325]
Hi,
Only two modules are loaded in Vcvrack 2 on Linux: Midi-step and Glue. The other other do not show in the list of available modules. Normal?
Thank you.

**Comment by Petervos2018** [comment]
https://github.com/stoermelder/vcvrack-packone/issues/321#issuecomment-1120292951

**Comment by Donmanouche** [comment]
Many thanks @Petervos2018 ! It works now.
