### ISSUE TITLE
Macro module CV outputs crash rack when Macro's knob is turned

### ISSUE THREAD

**Issue by Torinbob** [stoermelder/vcvrack-packone#327]
The Macro module CV outputs crash rack when Macro's knob is turned.

To reproduce the issue, connect either CV output on Macro to any CV input on another module.

Then turn the knob on Macro > Rack crashes

Rack standalone 2.1.2 - Mac OS Monterey 12.4

**Comment by stoermelder** [comment]
Thanks for reporting, fixed.
