### ISSUE TITLE
ARENA does not save some settings

### ISSUE THREAD

**Issue by Petervos2018** [stoermelder/vcvrack-packone#331]
Hi Ben,

When you first add ARENA to a patch the proximity lines are missing. When you reduce the number of ins and outs the white and yellow circles stay in view ( they used to vanish). When reloading a patch with ARENA in it all the radius settings are back to 50%. And the radius is not visible at all when changing it.

Some screenshots :  

![afbeelding](https://user-images.githubusercontent.com/46076474/189639114-cbf54ef8-aa8c-4d57-9e0d-46352acea641.png)
![afbeelding](https://user-images.githubusercontent.com/46076474/189639185-c6df1aac-4864-4325-8c66-2956074e1d81.png)

This problem of NOT recalling the settings of the radius was already present in V1

![afbeelding](https://user-images.githubusercontent.com/46076474/189639492-8711721d-460c-486d-ab72-f06ed8ea2838.png)

It went to 0%, but at least you can see the radius and proximity lines in v1

![afbeelding](https://user-images.githubusercontent.com/46076474/189639848-6a256c61-5e5e-4841-b44a-e1b5f9b2d306.png)

Thanks for all your modules, and if you have any questions please ask,

Greetings Peter.

**Comment by stoermelder** [comment]
Thanks Peter for reporting, much appreciated. I completely messed up the screen drawing while trying out some fancy things with room brightness...

**Comment by Petervos2018** [comment]
And 30 minutes later it's solved, you really are incredible, thank you 😃 looking at the balls and the lines and the radius...lovely.
![afbeelding](https://user-images.githubusercontent.com/46076474/189741964-689d2f90-67f9-41e9-aa9a-f2acc9ebc466.png)

Thanks Peter.
(you can close this now or should I do it ?)

**Comment by stoermelder** [comment]
Yes, let's close this one :-)
