### ISSUE TITLE
Can Glue be made to work with VCV Selections?

### ISSUE THREAD

**Issue by DaveBenham** [stoermelder/vcvrack-packone#332]
Scenario setup - I patch a set of modules that includes Glue with labels, and then save the construct as a VCV selection

If I import the selection, the Glue labels are gone.

I realize Strip handles this functionality just fine. Just curious if it could be made to work with VCV selections.

**Comment by stoermelder** [comment]
Duplicate of #326

**Comment by stoermelder** [comment]
Just to let you know: I added module S++ which adds options to paste or import Rack selections while preserving GLUE's labels.
146d3d366a5e91ec5c4518e486d7c54b05175990
