### ISSUE TITLE
Audio64 - inputs / outputs issue

### ISSUE THREAD

**Issue by W4too** [stoermelder/vcvrack-packone#334]
Hi,

When  i select my audio interface ASIO driver in audio64 module, inputs and outputs don't seem to match correctly.

![audio64](https://user-images.githubusercontent.com/100092785/190221861-ddc78fcc-2b83-4492-a7fd-1d1205b25bf8.jpg)

Thanks

**Comment by stoermelder** [comment]
Thanks for reporting, I fixed the issue, but also deprecated the module as multiple Audio-16 can be used for the same purpose.
