### ISSUE TITLE
Transit Expander not lighting up

### ISSUE THREAD

**Issue by rasavell** [stoermelder/vcvrack-packone#335]
Expander seems to work, but no visual feedback

**Comment by stoermelder** [comment]
The manual explains how to adjust the sequence length/number of actives snapshots.
https://github.com/stoermelder/vcvrack-packone/blob/v1/docs/Transit.md#sequencing-and-selecting-snapshots

**Comment by rasavell** [comment]
Apologies! Forgot to try this, as I was working mostly with 12 snapshots- default in the main module.
Best,
Rob
