### ISSUE TITLE
8 / 16 face not recognizing modules

### ISSUE THREAD

**Issue by W4too** [stoermelder/vcvrack-packone#338]
Hi,
I sometimes get an error with the 8face or 16face not recognizing attached modules.
All is working fine when i build my patch but once saved and re-opening it, i get this issue.

Thanks

[16_face.zip](https://github.com/stoermelder/vcvrack-packone/files/10007520/16_face.zip)

**Comment by stoermelder** [comment]
Thanks for reporting, fixed.
