### ISSUE TITLE
I miss stoermelder modules in Rack 2

### ISSUE THREAD

**Issue by ghost** [stoermelder/vcvrack-packone#339]
I know it's probably a lot of work to migrate them but just know that it would be appreciated.

Especially Glue!

**Comment by higaru2** [comment]
Max:
this will make you very happy:) Ben already did that.
https://github.com/stoermelder/vcvrack-packone/releases/tag/Nightly

**Comment by stoermelder** [comment]
It is on the way and will arrive soon.  
https://github.com/VCVRack/library/issues/560#issuecomment-1321237385
