### ISSUE TITLE
Request for module: CV recorder

### ISSUE THREAD

**Issue by Coirt** [stoermelder/vcvrack-packone#34]
I thought there was a way to record CV with remove maybe it was just when I tried it in beta or I'm mistaken. But anyway... 

Input CV signals and record what is played. Accept a clock signal to get timing and set recording to  #pulses to record the CV signal, playback then plays based on the clock signal, number of pulse and time (samples) of recording. Changing clock speeds will keep the recorded CV in sync. Possible the signal can then be offset/scaled like how uMap offsets/scales.

**Comment by stoermelder** [comment]
ReMOVE Lite can record incoming CV instead of parameter automation, just use the IN-port.
If you need really high accuary it's maybe easier to use any sampler in Rack which can record. Something like Simpliciter by NYSTHI.

**Comment by Coirt** [comment]
Ah okay I remember now it has to be mapped to record!
