### ISSUE TITLE
GOTO crashes multiple DAWs when running as VST

### ISSUE THREAD

**Issue by agentf64** [stoermelder/vcvrack-packone#342]
Tested in both Reaper and Studio One.
Steps to reproduce - simply add the module and close the project. When you re-open the project the program crashes. 
Reaper had crashes, S1 locks up and needs to be killed via task manager. I can provide logs is necessary. I could also test in other DAWs if requested (Ableton, Cubase, or Bitwig). 
I did confirm that it only crashes when running as a VST.
Rack Pro version 2.2.0
S1 5 and latest Reaper version.

**Comment by stoermelder** [comment]
Thanks for reporting. Please try the latest development build if it works now as expected: 
https://github.com/stoermelder/vcvrack-packone/releases/tag/Nightly

**Comment by agentf64** [comment]
Yes. That fixed it. Cheers.
