### ISSUE TITLE
MIDI-KEY suggestion

### ISSUE THREAD

**Issue by vcvrackideas** [stoermelder/vcvrack-packone#344]
Hi Ben, glad to see you back on track with all of new modules and whole beta for the library! :-)
MIDI-KEY is a long waited dream to throw a keyboard for vcv rack and replace this by small controller together to connect Sail or so features. So you have implemented ctrl, alt and shift buttons for separate button on midi controller. But why if you can add a whole combination, let's say CTRL+D, for just one button on controller included modificator in it.

**Comment by stoermelder** [comment]
I added options for that, but the modifiers must be manually enabled and can't be learned, for the moment.
