### ISSUE TITLE
STROKE new commands suggestion

### ISSUE THREAD

**Issue by vcvrackideas** [stoermelder/vcvrack-packone#345]
Module - Add random module (my current workflow is quite long on it - open browser, check Random sorting, press backspace and then only choose a random module)
Presets - Save default preset (sometimes find some cool starting point but always forgot to save it due to some menu diving and lack built-in rack command)
Presets - toggle next user preset (same thing but more on the choosing between some nice starting points)

**Comment by stoermelder** [comment]
I have no good idea how to toggle the user presets: The module has no knowledge that an user preset has been loaded, so I can't determine which the next preset should be. I could track the loaded user preset for each module but I don't think it would be very intuitive.

**Comment by stoermelder** [comment]
I think this modules implements it in a nicer way as anything would bei possible in STROKE.
https://library.vcvrack.com/dbRackSequencer/Preset
