### ISSUE TITLE
MIDI-Plug: Loopback namecrash with Rack 2.2.0 loopback

### ISSUE THREAD

**Issue by jpnielsen** [stoermelder/vcvrack-packone#346]
Running Pack one in Rack 2.2.0 free.

Latest Rack has a built -in loopback driver - 16 loopbacks with each 16 midi channels.

If I enable "midi loopback" in stoermelder midi-plug, it tells me that
the midi-loopback will be enabled after I restart rack. 

After restarting I have two identically named midi loopback entries in
the midi modules.

Not really a problem it seems - perhaps disable the PackOne loopbacks, now that Rack comes with it.

I first emailed support@vcvrack.com - they asked me to send it to you.

best,
Jens Peter Nielsen

<img width="949" alt="loopbacks" src="https://user-images.githubusercontent.com/27916597/204465728-fa9bb715-e3d3-400c-950b-a20905b3060a.png">

**Comment by stoermelder** [comment]
Well, technically I added the Loopback driver much time ahead of VCV, but well...  
See the changelog of the latest release, which is waiting in the integration pipeline.  
https://github.com/stoermelder/vcvrack-packone/releases/tag/v2.0.beta2

**Comment by pgatt** [comment]
Hi Ben, I am following this conversation - I wasn't aware that it was due to you already having Loopback, I thought it was your module duplicating two instances of Loopback.

**Comment by pgatt** [comment]
Thanks, seems like that's a reasonable fix. Apologies for any confusion.
