### ISSUE TITLE
8FACEmk2 in "forward mode" jumps to 2nd slot/snapshot when applying a "reset"

### ISSUE THREAD

**Issue by jaynothin** [stoermelder/vcvrack-packone#347]
This issue happens also with: 8FACE, 8FACEx2, 8FACEmkII and TRANSIT. 

I'm always performing LIVE and I use an "auto reset", (e.g. every DIV64 or DIV128) to make sure everything is always in sync, so that I don't have to manually send a sync that would just break "tempo" in a middle of a musical phrasing, if this makes any sense. 🙂 

I've been using more and more 8FACEmk2, and of course I connect my "auto reset thingy" to its reset. 😉 

But I've noticed that when a click and a reset are received at the same time (I use click-forward) the result is that it jumps on the 2nd slot/snapshot. I've also tested other modules as above mentioned and they have the same behavior/issue.

I'm including a [zipped .vcv file](https://github.com/stoermelder/vcvrack-packone/files/10125385/Stoermelder-Reset-Trigger-2ndslot-issue.zip) so it's quick to open and see what is going on. (same as image preview)

I hope I make sense and that this can help 😄 
Thank you

  
![image](https://user-images.githubusercontent.com/74117050/204850686-92fd8489-d4cf-4a37-a71c-607f169a0dc3.png)

**Comment by jaynothin** [comment]
Ok, I did some more tests.

So I sent a "real" reset signal from the clock (and also SEQ3 reset out, and others, etc...), instead of testing with a pulse/gate 🤦‍♂️from the clock. 

Now, everything reset to slot 1, of course. 😮‍💨 

So the issue isn't really an issue. I guess because it needs a very small trigger, smaller than what the clock PW knob could give me when tuned all the way down.

So maybe this can be an enhancement proposal? 🤷 
For some cases, sometimes, having the reset behave the same way if it receives a longer trigger/gate could be an enhancement? If this is even a thing.

So this issue is SOLVED but not solved for all cases, while the enhancement is whatever you wanna make of it 😄.

Hope those posts weren't a waste of time. 😱 

-jay

**Comment by Petervos2018** [comment]
I think that delaying the reset pulse (does not have to be a trigger) by 1 sample solves all your problems ?

![afbeelding](https://user-images.githubusercontent.com/46076474/204898979-be895e53-c9b5-4b46-a3ca-93423fe29049.png)

I use the sum module to introduce 1 sample delay.

And the clocked needs some attention : 

![afbeelding](https://user-images.githubusercontent.com/46076474/204899789-fa6fb1a6-62cc-4ed5-b5e7-fa1364f7aaeb.png)

Turn off "Output high on reset when not running" and check reset pulse on start.

**Comment by stoermelder** [comment]
Thanks for reporting, various problems here:
- I handled a reset trigger as a clock trigger, what made the actual clock trigger forward to slot 2
- In "Trigger reverse" reset moved to slot 1 instead of the last slot
- "Trigger alternating" and "Trigger shuffle" had no reset-handling at all

**Comment by jaynothin** [comment]
Indeed the 1 sample delay solves the problem

thank you

**Comment by jaynothin** [comment]
> Thanks for reporting, various problems here:
> 
> * I handled a reset trigger as a clock trigger, what made the actual clock trigger forward to slot 2
> * In "Trigger reverse" reset moved to slot 1 instead of the last slot
> * "Trigger alternating" and "Trigger shuffle" had no reset-handling at all

Does this mean it won't need a sample delay in a future update?

**Comment by stoermelder** [comment]
> Indeed the 1 sample delay solves the problem

Yes, as the reset trigger arrives after the clock trigger it resets to slot 1 (after clock advanced to the next slot), but this is not how it should work.

> Does this mean it won't need a sample delay in a future update?

Yes, I fixed it in the latest commit and the automatic development build will be ready in a few minutes. The fix will be included in v2.0.beta3 in the VCV Library.

**Comment by stoermelder** [comment]
An additional note: ce54e67b0a767916a55b7f807da19b2de0d4a8f6 changes the reset-behavior. A trigger to reset now "arms" the reset and will we executed on the next clock trigger. I guess in most cases this won't make a difference but with no clock running the reset won't load slot 1.

**Comment by stoermelder** [comment]
Sorry about the confusion. I fixed my fix, now it should work as expected.
