### ISSUE TITLE
MB crash Rack

### ISSUE THREAD

**Issue by Petervos2018** [stoermelder/vcvrack-packone#352]
Hi Ben,

Try this : make a patch any patch, close Rack, open Rack nothing wrong. Now add MB, close Rack, start Rack (crash)

![afbeelding](https://user-images.githubusercontent.com/46076474/207431836-47c3d693-1f43-4db3-8426-85063dc57347.png)

Choose NO and it will reload the patch without any problems, and even after that, you can open and close Rack without any problems.

But it will always crash the first time you open a patch after you added MB.

Windows 10 Rack 2.2.1 (older versions also crashed)

Greetings Peter.

**Comment by stoermelder** [comment]
Thanks for reporting, fixed.

**Comment by higaru2** [comment]
Ben:
thank you!
where is this updated
because here I cant find it...
https://github.com/stoermelder/vcvrack-packone/releases/tag/Nightly

**Comment by stoermelder** [comment]
The automatic build takes 10-15 minutes, you'll find it there in a few minutes.

**Comment by higaru2** [comment]
AH!:)
I'll be patient.
have a good warm xmas there Ben:)
