### ISSUE TITLE
Enhancement: Enable/disable long-press - 8FACE, 8FACEmk2, 8FACEx2, Transit

### ISSUE THREAD

**Issue by jaynothin** [stoermelder/vcvrack-packone#354]
Enhancement: Enable/disable long-press for 8FACE mk2 (should also be applied to 8FACE, 8FACEmk2, 8FACEx2, Transit, ...) 

I had already reported an [issue](https://github.com/stoermelder/vcvrack-packone/issues/319) almost identical to this one, but it was a misunderstanding, on my part :man_facepalming:, of the long-press function. :wink: Unfortunately (for me), under certain circumstances, I've found it can become a problem while performing in a live jam session. :cry:  

- **Setup used:** [(see image)](https://user-images.githubusercontent.com/74117050/208736363-78452409-c6ba-4a86-a840-293faf29ea60.png)  
I mostly use 8FACE mk2 to cycle drum patterns.  
8FACE mk2 slots are triggered by 8 pads of an external MIDI controller.  
Everything mapped with MIDI-CAT.  

- **Case scenario:**  
When I perform LIVE, using the [pads of the MIDI keyboard controller, I inadvertently leave my finger(s) on the pad(s) for more than a second](https://user-images.githubusercontent.com/74117050/208730616-554ad839-93a8-4f92-bddd-0b125ea586d8.png), therefor triggering the "long-press" function and changing the number of "enabled" slots.  
This affects the performance as I only realize after a while that the slots/patterns aren't triggering/changing anymore. :scream: 

- **Requested enhancement:**  
Perhaps make a context menu option to enable/disable "long-press" action?  

I know I might be the only one that need to disable long-press, but something like this would definitely fix my problem. :+1:  

Thank you :smile:  

jay

**Comment by stoermelder** [comment]
Added.
