### ISSUE TITLE
MIDI-CAT MEM buttons not responsive to mapping modules

### ISSUE THREAD

**Issue by HikoriHawky** [stoermelder/vcvrack-packone#356]
Hello!

I suppose this is a follow-up to #281, mapping modules such as another instance of MIDI-CAT or MIDI Map causes the buttons to be visibly pressed, but nothing happens. Here's a video showcasing this issue. Oddly enough, the buttons may be visibly "stuck" as well.

[https://www.youtube.com/watch?v=bL5fjBAwXzU](https://www.youtube.com/watch?v=bL5fjBAwXzU)

The test in the video was done with note input, but I have tried with midi cc (both in midi-cat and midi map) as well and that has the same issue.

I have a suggestion that could side-step this issue, add gate inputs for the three buttons. That way, VCV's MIDI Gate/Midi CC to CV could be used to trigger module selection in a more "modular" way and bypass whatever's causing the weird interaction with the buttons. There's also the additional benefit of allowing MIDI-STEP to interact with MEM; rotating the endless encoder on my X-Touch Mini rather than repeatedly clicking a button would be really really really neat! (edit: Tried using uMAP, It didn't work)

**Comment by mysterybear** [comment]
Yeah, same!


Anything on this @stoermelder ?

Edit: FWIW I was trying to set up STROKE -> MERGE -> CV-MAP -> MIDI-CAT MEM

**Comment by stoermelder** [comment]
Thanks for reporting, fixed.
