### ISSUE TITLE
Transit shuffle mode bug or design issue?

### ISSUE THREAD

**Issue by DaveBenham** [stoermelder/vcvrack-packone#359]
Shuffle is not working to my expectations. I think I have figured out the behavior, but it is not working in a way that I would like.

If I am in forward, or reverse, or ping pong, or alternating - any other mode that has a definite cycle begin and end point, then when I reset Transit it immediately resets to the first slot of the cycle and the cycle begins. This works great for performing a song so I can reset as I start, and get a reproducible result. I typically have a clock that resets a sequencer upon startup of the clock, and the sequencer triggers the Transit at the start of each sequence cycle.

But with Transit in shuffle mode the cycle does not begin with a reset, but rather upon the first trigger ***after*** the reset. This is a little problematic for me because I want to reset at the beginning of a song and play all of the slots exactly once in some random order. As expected, simultaneous reset and trigger does not start a new cycle because the trigger is ignored in that case. So if I have 4 slots for example, and my clock fires reset upon startup, then I end up having to play through 5 slots to play all 4 with one repeat.

I'm hoping you can modify the behavior such that a reset immediately starts a cycle, without changing the current slot. I suppose it would work as well if a reset immediately selected a new slot at random to start the cycle. But in my case I sometimes know what slot I would like to start with, but then don't care about the order after that.

My current workaround is to manually issue a Transit reset prior to starting my clock, but that means my Transit reset has to be separate from all the other resets for sequencers, etc. - I cannot share the same reset source. It also means I lose control of the initial start slot. This is not the end of the world, but it is definitely not convenient.

I'm also curious about the intended behavior of shuffle mode when the mode is first selected, or when the number of slots changes. I would expect all of the following to immediately begin a new cycle:
- reset trigger
- initial selection of shuffle mode
- change the number of active slots

One other point - at the start of a new cycle, Transit randomly might start the new cycle with the same slot as the end of the prior cycle. It would be nice if it was forbidden to start a new cycle with the same slot.

As always, thanks for making great modules. I am so glad to have them back in the library for rack 2, even if it is officially a beta release.

**Comment by stoermelder** [comment]
Might be related to #347, needs further review.

**Comment by DaveBenham** [comment]
Perhaps there is some interaction between the two issues. But I am pretty sure my issue is its own thing.

My issue only concerns the shuffle mode. It seems like a fairly complicated design issue.

**Comment by stoermelder** [comment]
I had some reset-code for shuffle added to 8FACE and 8FACE mk2 some time ago, but I noticed a few moments ago that I did not commit my local change of the reset-code for shuffle in TRANSIT :-(
I would not be suprised if this fixes your issue...
