### ISSUE TITLE
MIDI-CAT - „Locate and indicate“ triggered by midi input

### ISSUE THREAD

**Issue by stoermelder** [stoermelder/vcvrack-packone#36]
Jump to mapped parameter on incoming midi message.
Inspired by https://github.com/VCVRack/Rack/issues/1513.

**Comment by matthieuroche** [comment]
Hi Ben,

I am glad that you found the enhancement I raised interesting :) Does it mean that I can compile the current version of PackOne ad test the feature?

Thanks in advance!

Best
Matthieu

**Comment by stoermelder** [comment]
Hi Matthieu, yes, you can compile it yourself or you can download an automatic build from the latest commit here:
https://github.com/stoermelder/vcvrack-packone/releases/tag/Nightly
Please be aware, the module is not yet released and future builds could be incompatible.

**Comment by stoermelder** [comment]
Some quick instructions how this works:
The module can switch between normal operating mode and "locate and indicate" mode on the context menu. When activating the last, any midi message for a mapped parameter will be discarded, instead the mapping indicator of the parameter will blink for a few seconds and module is centered on the screen.

**Comment by matthieuroche** [comment]
Hi Ben,

this is very handy! Is the fact that MIDI Messages are killed in locate
mode a necessary step?

An idea that I had in mind when submitting the request on Github was that
maybe the tooltip that shows up when you approach the mouse (for example)
could show up when the knob receives a MIDI message, maybe with a
background color that would make it easy to see.

Thanks again for working this out so fast!

Cheers

Matthieu

**Comment by stoermelder** [comment]
>  Is the fact that MIDI Messages are killed in locate
mode a necessary step?

No, it isn't. I thought it would be good to be able to play around without changing any parameter. But I can change that. What do you think?

**Comment by matthieuroche** [comment]
Hi Ben,

Maybe there is a way in-between. I am not à développer so my description
may be unclear. Is it  feasible to buffer the first few milliseconds during
which the knob is turned, focus the parameter that is under control, and
start sending data?

Also, as I suggested in my previous email, do you think that tooltips could
be displayed on knob movement? It may be more usable than module focus.

Thanks again.

Matthieu
