### ISSUE TITLE
Grip completely dysfunctional

### ISSUE THREAD

**Issue by DaveBenham** [stoermelder/vcvrack-packone#360]
I cannot get Grip to lock any parameters on my Win 10 machine running VCV v2.2.3 and PackOne v2.0.beta3

The button activates the light, and I can select a parameter just fine (although sometimes the mapped indicator does not show, and when it does the color is inconsistent). The "locked" parameter(s) show properly in the context menu, but I can freely manipulate the parameters, and they do not restore to the "locked" position.

I don't know when this bug first appeared. I've used Grip quite a bit in the past. But I cannot remember if I have seen it work in v2

**Comment by stoermelder** [comment]
Thanks for reporting, fixed.
