### ISSUE TITLE
MIDI-STEP - Support for Hercules DJControl Starlight

### ISSUE THREAD

**Issue by IndianaGeorge** [stoermelder/vcvrack-packone#361]
Hi, great work on MIDI-STEP!
I have a controller that behaves in a different way (and is, in fact, often unsupported): the Hercules DJControl Startlight.
It has two jogs (infinite/incremental) using ch2 and ch3 respectively that send two different CCs depending on how you hold them: CC10 from the top and CC9 from the side. This is all already covered by MIDI-STEP already!
The problem is: each one decrements or increments by sending 0 or 127 respectively on that same CC, and since MIDI-STEP has a single output per CC, I can't hook it up to increment or decrement on PILE nor use it as a "speed" CV either.

Could such a controller be supported? or should I write my own very-specific module?
Thanks!

**Comment by stoermelder** [comment]
MIDI-STEP has two outputs for each CC, one for triggers on decrements and one for triggers on increments. As MIDI-STEP has 8 ouputs for each decrements and increments, only eight CC selection slots are active by default (the lower the rows are only available when using a polyphonic cable for output).  

I'm not sure if I understand you correctly and I did not find a MIDI reference for this controller: All controllers I know are sending some fixed values with special meaning on the same CC for one knob. Are you sure your controller is sending value 0 for decrements? The protocol you are describing is essentially the same as Beatstep Relative 2 or NI Komplete Kontrol Relative, except these controllers are sending 1 and 127 for decrements and increments respectively.

**Comment by IndianaGeorge** [comment]
Thanks for looking into it!
I was testing using stoermelder MIDI-MON module and it shows:
Left Jog
- spin outer (clockwise/counter): ch2 cc9=1 / ch2 cc9=127
- spin inner (clockwise/counter): ch2 cc10=1 / ch2 cc10=127
- touch (on/off): ch2 note on 8 vel 127 / ch2 note on 8 vel 0
Right Jog
- spin outer (clockwise/counter): ch3 cc9=1 / ch3 cc9=127
- spin inner (clockwise/counter): ch3 cc10=1 / ch3 cc10=127
- touch (on/off): ch3 note on 8 vel 127 / ch3 note on 8 vel 0

Then I went and tested with hardwaretester.com/midi and got the same values except for an extra unlabeled id:
Left Jog
- spin outer (clockwise/counter): Chan 2 Control/Mode Change (177 9 1) / Chan 2 Control/Mode Change (177 9 127)
- spin inner (clockwise/counter): Chan 2 Control/Mode Change (177 10 1) / Chan 2 Control/Mode Change (177 10 127)
- touch (on/off): Chan 2 Note on G#-1 (145 8 127) / Chan 2 Note on G#-1 (145 8 0)
Right Jog
- spin outer (clockwise/counter): Chan 3 Control/Mode Change (178 9 1) / Chan 3 Control/Mode Change (178 9 127)
- spin inner (clockwise/counter): Chan 3 Control/Mode Change (178 10 1) / Chan 3 Control/Mode Change (178 10 127)
- touch (on/off): Chan 3 Note on G#-1 (146 8 127) / Chan 3 Note on G#-1 (146 8 0)

**Comment by IndianaGeorge** [comment]
so my mistake, it's actually sending 1 for counterclockwise, not 0.
also I had not understood that the bottom connections were for dec, I thought inc/dec would come in the same connection as +/-

I hooked it up and every protocol works. You can add Hercules DJControl Starlight to the list of supported devices.

Thanks!
