### ISSUE TITLE
Having Stoermelder MB inserted into rack stops save default from working.

### ISSUE THREAD

**Issue by pgatt** [stoermelder/vcvrack-packone#369]
Hi Ben,

If MB is in a user's patch, and then the user right-clicks a module and selects Preset > Save default then the default preset is saved correctly but then using the MB menu to insert that module doesn't insert it into rack in a way that sets the module to the saved default.

**Comment by stoermelder** [comment]
Thanks for letting me know, added.

**Comment by pgatt** [comment]
Thanks Ben, appreciate it!
