### ISSUE TITLE
MIDI-CAT - pickup-mode for mapped CCs

### ISSUE THREAD

**Issue by stoermelder** [stoermelder/vcvrack-packone#37]
https://github.com/VCVRack/Rack/issues/1424

**Comment by stoermelder** [comment]
@MaZe6K Please check if it's working nicely for you. I'm not quite sure.

**Comment by MaZe6K** [comment]
It doesn't seem to work yet, when activating "Locate and indicate" it seems to react the same way as "Operating." If I move a midi knob that is at a different position than the controlled knob on the module, it causes it to jump to that position. It should do nothing until the midi knob reaches the same position as the knob on the module and then go on from there.
I would recommend to call the two modes something more obvious, like "immediate" and "pickup mode," because I wouldn't know what to expect if I just found this in the right click menu with the current names.

**Comment by MaZe6K** [comment]
I just found a small bug: The channel filter does not seem to work, I have channel 1 selected, but it also reacts to the same CC's on all other channels of the same device.

**Comment by stoermelder** [comment]
> It doesn't seem to work yet, when activating "Locate and indicate" it seems to react the same way as "Operating." If I move a midi knob that is at a different position than the controlled knob on the module, it causes it to jump to that position. It should do nothing until the midi knob reaches the same position as the knob on the module and then go on from there.
> I would recommend to call the two modes something more obvious, like "immediate" and "pickup mode," because I wouldn't know what to expect if I just found this in the right click menu with the current names.

Please click on a specific slot with mapped cc. There you'll find a "Pickup" mode on the context menu.

**Comment by MaZe6K** [comment]
oh... sorry... I was on the wrong module altogether... :D now I see what Locate and indicate is... But pick up mode still doesn't seem to work.

**Comment by stoermelder** [comment]
Did you enable "pickup" mode on the slot you're testing with?

**Comment by MaZe6K** [comment]
yes, and I was really making sure this time, tested several times and even deleted the module and loaded a new instance and mapped and activated pickup mode again... the knobs still react to a new position immediately.

**Comment by stoermelder** [comment]
I have a report from another user saying "it's working great", so it must be something specific on your combination of devies. What midi controller are you using? Can you supply a patch file?

**Comment by MaZe6K** [comment]
I use a novation Launch Control XL. I have several user mappings on it and can switch the mapping. So I switch to a different preset, move the knob (it sends a different CC now), then switch back to the first preset and move the knob and it jumps immediately.
BUT now I just discovered that if I close Rack, move the knob, then start up Rack again, it works (but only the first time, switching preset and moving it again doesn't work). I hope this helps.

[pickup test.zip](https://github.com/stoermelder/vcvrack-packone/files/3462747/pickup.test.zip)

**Comment by MaZe6K** [comment]
I guess you just didn't expect my use case of having a knob change position without sending the mapped CC while the patch is running. Sorry for complicating things :)

**Comment by stoermelder** [comment]
Ah ok, I understand now. Then it behaves how designed this feature at the moment: once "picked up" by the controller it will follow all controls, even when jumping around. I thought this is a good idea for digital controllers (I tested it on the touch faders of a Maschine Jam).
Maybe I can add another mode which picks up on every jump.

**Comment by MaZe6K** [comment]
That would be great, then I could map 100's of controls and jam around without having to fear sudden jumps :)

**Comment by MaZe6K** [comment]
One more note: When moving the mapped knob with the mouse and then again moving the knob on the controller, pick up mode also works nice so far.

**Comment by stoermelder** [comment]
I added a second mode, but it is dependent how precise the midi controller works: I have to draw a line between "control jumps to a different position" and "control is moving really fast". I decided to draw this line at about +/-10% difference to the last reported position.
So, moving a knob or fader really fast will "lose" the mapped parameter.

**Comment by MaZe6K** [comment]
Nice! Thank You! Works like a charm! I couldn't move the faders fast enough to loose it, seems to work perfect this way. (edit: I can move the faders fast enough, but I wouldn't reach this speed during jamming around with it :) )
I would however prefer a global option for the whole module, could become a lot of searching and clicking this way...

**Comment by stoermelder** [comment]
I don't want an additional option, but I added in ac308316ed1a14e99cafcd711f6b7d7b7a1c5783 that learning a mapping will use the same mode as the previous slot. So, learn the first slot, change "pickup"-mode, then learn all other slots.

I'm closing this because I think the two pickup modes are working good enough for now.
