### ISSUE TITLE
SPIN - can't use middle click

### ISSUE THREAD

**Issue by a4180p** [stoermelder/vcvrack-packone#372]
As far as I understand middle click is intercepted by vcv rack itself and used to [pan rack view](https://vcvrack.com/manual/KeyCommands). So I was unable to use the middle mouse click with or without modifiers on MacOS.

Is there a way to still use SPIN's middle click functionality?

**Comment by stoermelder** [comment]
It seems that the middle mouse button is now always consumed by ScrollWidget of Rack, so middle mouse button events do not reach any contained widgets:
https://github.com/VCVRack/Rack/commit/427f490f44f2da6c98f2ac8f2641920cb15cd577
I moved SPIN's helper widget upwards in the widget hierarchy and it is working again, but I hope this does not break anything else.

**Comment by a4180p** [comment]
I've tested the latest nightly build and it works for me. Thanks!
