### ISSUE TITLE
8face mk2 - crash when receiving 10v

### ISSUE THREAD

**Issue by lionelfischer** [stoermelder/vcvrack-packone#377]
my patch crashes whenever i save it with the RCM 0-10 module sending 10v to the 8face in the upper right corner.  if i save it with a lower than 10v setting, it opens.  if i save it with 10v then i can not open the saved project without crashing immediately.  i've tried other offset modules and it doesn't affect the crash.

**Comment by stoermelder** [comment]
Thanks for reporting, fixed.

**Comment by lionelfischer** [comment]
Incredible! Thank you for such quick assistance
