### ISSUE TITLE
[Suggestion] Add gate output to Stroke

### ISSUE THREAD

**Issue by flarn2006** [stoermelder/vcvrack-packone#380]
Currently, Stroke only outputs a short trigger pulse when the key is first pressed, despite the indicator light turning on for as long as the key is held. I think it would be useful to have an output for this. The way I'd implement it is, rather than adding a bunch of new outputs, it might be good to just have a mode switch (TRIG/GATE) which determines the behavior, either one switch for each or a single switch for all of them.

**Comment by stoermelder** [comment]
I'm not sure if I understand you correctly, STROKE provides an option for gates?

![image](https://github.com/stoermelder/vcvrack-packone/assets/47640667/cd9e097e-e1c1-4480-aae2-51099a0f7cd5)

**Comment by flarn2006** [comment]
Oh I see now, if I right-click the hotkey field. Didn't notice that at first. Thank you!
