### ISSUE TITLE
Request for more presets in Transit

### ISSUE THREAD

**Issue by CarlosBoix** [stoermelder/vcvrack-packone#381]
Hello sir hope all is well, 

Many thanks for all you've done for the VCV community, your modules are excellent.

Currently using you Transit module and expanders to it's full capacity and would love to be able to add more expanders, so I can make 128 presets.  

Would this be possible, please ?

Best wishes,

**Comment by stoermelder** [comment]
I increased the maximum number of expanders to 15, allowing 12 * 16 snapshots. It will be available as [development build](https://github.com/stoermelder/vcvrack-packone/releases/tag/Nightly) (no ARM64, sorry) and hopefully in 1-2 weeks in the VCV Library.

**Comment by CarlosBoix** [comment]
Hey man wow thanks ! I downloaded and installed the new beta, but I don't seem to be able to add more expanders, I am using an M1 and installed the file in VCV plug in folder and the library picked it up to update. But no luck adding more than 7 expanders on an existing patch. AM I doing something wrong ? can't write nor long press any buttons to get them to light up

**Comment by CarlosBoix** [comment]
Ignore me, I figured it out. I had downloaded the Beta3 instead of the one at the bottom of the page

**Comment by CarlosBoix** [comment]
Heads up Ben, just had VCV crash 3 consecutive times when trying to add more modules to bond on a preexisting patch that uses 128 presets. 
I first tried bind whole module (currently transit is bonded to 14 "alikins specific value" modules which only has one knob) then i tried bind single control (or whatever is called) and lastly i tried bind several controls. On every instance it crashed upon first clicking on the first specific value module tha I wanted to add.

**Comment by stoermelder** [comment]
Sorry, I can't reproduce any crash. Please provide me your patch file, so I can investigate.

**Comment by CarlosBoix** [comment]
sent you an email to your outlook address with subject Request for more presets in Transit #381

**Comment by stoermelder** [comment]
Thanks, I can reproduce the crash now, but it has nothing to do with the additional expanders. I created a new issue.
