### ISSUE TITLE
Latest Stroke update 66080 does NOT zoom toggle

### ISSUE THREAD

**Issue by Petervos2018** [stoermelder/vcvrack-packone#382]
Hi Ben,

Zoom toggle does not work.
Zoom toggle (smooth) works !

![afbeelding](https://github.com/stoermelder/vcvrack-packone/assets/46076474/ffbd6c5f-31fd-4915-b37b-87c4fc66296b)

Test file below : 
[Zoomtoggle10022024.zip](https://github.com/stoermelder/vcvrack-packone/files/14227070/Zoomtoggle10022024.zip)

Greetings Peter.

**Comment by stoermelder** [comment]
Thanks for reporting, fixed.
