### ISSUE TITLE
Transit - crash on patch load

### ISSUE THREAD

**Issue by stoermelder** [stoermelder/vcvrack-packone#383]
Heads up Ben, just had VCV crash 3 consecutive times when trying to add more modules to bond on a preexisting patch that uses 128 presets. 
I first tried bind whole module (currently transit is bonded to 14 "alikins specific value" modules which only has one knob) then i tried bind single control (or whatever is called) and lastly i tried bind several controls. On every instance it crashed upon first clicking on the first specific value module tha I wanted to add.

_Originally posted by @CarlosBoix in https://github.com/stoermelder/vcvrack-packone/issues/381#issuecomment-1936640716_

**Comment by stoermelder** [comment]
It has nothing to do with the enhancement to 15 expanders, as the patch is inconsitent with bound modules. Further investigation is necessary.

**Comment by CarlosBoix** [comment]
Hello Ben hope all is well,

Just passing by to see if you had found out why this is happening. Today I duplicated existing transit with expanders and bound alikins modules to see if the whole thing copied and it does not. I tried to bind new copied alikins to copied transit and it crashed on the first click. 
Kind Regards

**Comment by CarlosBoix** [comment]
Does not happen if I create a new transit and add the expanders I can map the alikins without crashing but the preset I created does not spill into the expanders, only the transit module remembers which is a shame as I had stored 128 values on the expanders for all 14 alikins but only the first 8 work.

**Comment by CarlosBoix** [comment]
Hey I just tried this on a new macbook pro m3 max and binding a new module still crashes it. I'm attaching the crash report FWIW. Would love to be able to bind new modules to existing ones as otherwise I have start from scratch building 128 presets ; (
[Transit Crash report .pdf](https://github.com/user-attachments/files/16443438/Transit.Crash.report.pdf)

**Comment by stoermelder** [comment]
Can you eloberate again how to reproduce this? I'm not sure if duplicating TRANSIT will give you the result you are trying to achieve.

**Comment by CarlosBoix** [comment]
So I have a transit with expanders binded to 14 alikins modules as explained. 128 presets. I want to bind more alikins but I can't. Does that explain things ?

**Comment by CarlosBoix** [comment]
Perhaps a video would help..... I'll see if I can record one for you

**Comment by stoermelder** [comment]
Sorry, I just noticed you already sent me a patch file for this issue. I will investigate further.

**Comment by stoermelder** [comment]
Please download the latest development build. 
https://github.com/stoermelder/vcvrack-packone/releases/tag/Nightly
TRANSIT has a new context menu option "Clean invalid parameters up". Please load your patch, use that option and you will be fine.

**Comment by CarlosBoix** [comment]
Hey Thanks for the update, unfortunately the mappings are not preserved when importing selection. neither are the labels. I'm usinf strip++ too and no luck

**Comment by CarlosBoix** [comment]
It works ! thank you very much indeed !
