### ISSUE TITLE
Configurable per-instance default "Input mode for CC" in MIDI-CAT

### ISSUE THREAD

**Issue by dev-dsp** [stoermelder/vcvrack-packone#384]
My controller has 32 knobs, so it seems I'll have to click 64 additional times to configure each of the 32 CCs to use "pickup" mode :D 
It would be nice to have the ability to change the default of the "Input mode for CC" parameter.

**Comment by stoermelder** [comment]
From the manual:

> Settings of a mapping slot are copied from the previous slot: If you set up the first mapping slot and map further mapping slots afterwards, these settings are copied over. Useful for settings like "Pickup" or "14-bit CC".
https://github.com/stoermelder/vcvrack-packone/blob/v2/docs/MidiCat.md
