### ISSUE TITLE
No PackOne expander modules listed in VCVRack browser

### ISSUE THREAD

**Issue by rjsmith** [stoermelder/vcvrack-packone#389]
Hi,

I am running the latest available Stoermelder-P1-2.0.beta4-mac-x64.vcvplugin installed cleanly from the VCVRack Library on my 2021 MBPro M1 32Gb Sonoma laptop. I am running VCVRackPro  2.4.1  I cannot see any of the P1 expander modules listed in the browser:

<img width="1347" alt="image" src="https://github.com/stoermelder/vcvrack-packone/assets/678653/1decdd5b-4794-4261-920d-811eba4a692a">

The modules all seem to work OK (e.g. MIDI-CAT) but I cannot see any P1 expanders so i can add them to a patch.

I have also tried the beta 4 plugin on the arm64 app, and compiling the v2 branch locally. In all cases, I can see the main P1 modules, but none of the Expanders.   There are no specific errors printed in the VCVRack log. 

I have attached an example log.txt opening an almost empty patch and then browsing and adding a MIDI-CAT module.

[log.txt](https://github.com/stoermelder/vcvrack-packone/files/15170652/log.txt)

I can see expanders from other plugins .. just none from the P1 plugin.

I deleted the P1 folder here ```~/Documents/Rack2/plugins-mac-x64/Stoermelder-P1``` , re-started VCVRack x64 and re-installed the P1 plugin and restarted again .. but still no expanders.

I would really appreciate any pointers you could give me where they might have disappeared to.  I have tried to search the VCVRack community site and this issue backlog but cannot see anyone reporting a similar problem.

Thanks for the great utilities!

**Comment by stoermelder** [comment]
I don't think it has anything to do with my plugin, as several modules are missing on your screenshot. Try this :
Go here https://library.vcvrack.com/plugins
Scroll down until you see this :

![image](https://github.com/stoermelder/vcvrack-packone/assets/47640667/dd477924-844e-43d8-bb87-7b1d7752d9eb)

Choose "Remove all", also remove `~/Documents/Rack2/plugins-mac-x64/Stoermelder-P1` folder from your hdd.
Start Rack,
Close Rack

In the Library choose "Subscribe" for the PackOne plug-in.

**Comment by rjsmith** [comment]
Hi, thank you so much - that was the problem. I realise I hadn't subscribed to the full collection.
