### ISSUE TITLE
8FACE does not reliably switch MIDI-CAT mappings.

### ISSUE THREAD

**Issue by ContemporaryInsanity** [stoermelder/vcvrack-packone#39]
Works fine sometimes, other times it misses out mappings.  Easy to recreate, just save two states of MIDI-CAT to 8FACE and switch a few times.  VCV MIDI-MAP works reliably.

**Comment by stoermelder** [comment]
Did you try the latest build? I did some changes on this today.

**Comment by ContemporaryInsanity** [comment]
I was on the last one I grabbed this morning.  New one seems ok.
