### ISSUE TITLE
Can MIDI-CAT map pitch-wheel messages?

### ISSUE THREAD

**Issue by jimallman** [stoermelder/vcvrack-packone#390]
Wonderful module! But I'm having trouble mapping from my controller's pitch wheel. I can see its messages in a MIDI monitoring program (see attached screen-grab), but MIDI-CAT doesn't recognize pitch-wheel messages. Is this a known limitation of MIDI-CAT?
![Screenshot 2024-08-24 at 3 16 43 PM](https://github.com/user-attachments/assets/4971fde8-2fd4-413c-8ea1-dbff8e1f4308)

**Comment by Petervos2018** [comment]
As a work around ?

![afbeelding](https://github.com/user-attachments/assets/9cbfc208-855b-49b8-a3cd-78606087f2f7)

But you are right both MIDI-MAP and MIDI-CAT are unable to map the pitchwheel.

**Comment by jimallman** [comment]
Thanks! That'll do.

**Comment by stoermelder** [comment]
Yes, that is right, pitch wheel MIDI messages are their own kind and MIDI-CAT only supports note and CC messages.
