### ISSUE TITLE
ARENA position attenuverters don't invert

### ISSUE THREAD

**Issue by landgrvi** [stoermelder/vcvrack-packone#394]
Hi Ben,

ARENA is amazing! It's the best thing I've found for moving sound around to my different speakers and I've had hours of fun with it so far (with more hours to come, no doubt).

The problem I'm having is that the position attenuverters only attenuate, they won't invert. I have all the ranges set to -5V..5V, but turning an attenuverter all the way to the left (-1x) does not have the same results as inverting the signal before sending it to ARENA.

Instead, any attenuverter value of 0 or below just locks the object in the corresponding 0 position.

Another way to put it is that the attenuverters don't have sensible behaviour for the -5V..5V ranges. Setting the attenuverter at 0 is not the same as sending 0V in with the attenuverter at 1x, which is what I'd expect.

I routinely invert all the y-position signals so that positive y is 'up' on the screen (cartesian coordinates), and it would be very handy to be able to use the attenuverters instead of needing to do that in a separate module.

Thanks again for this terrific module!

**Comment by landgrvi** [comment]
Hmmm, I've read through the relevant code section and I understand better why it does what it does. I'll have a think about whether there's a reasonably non-messy way to get my desired results.

**Comment by stoermelder** [comment]
I agree with you, this is not working as one would expect. Hopefully everything is fine now.

**Comment by landgrvi** [comment]
Yes, X&Y attenuverters now work as expected; also I see that you eliminated weirdness in how the MOD inputs were interacting with their attenuverters, so that all makes more sense now too.

From my point of view, this issue is resolved. Thank you!
