### ISSUE TITLE
STRIP - add option to set default save directory

### ISSUE THREAD

**Issue by zeronoises** [stoermelder/vcvrack-packone#41]
Strip by default wants to save in the program directory on my Linux box. Unfortunately, I keep Rack itself in the /opt directory - which of course needs root access.
It's slightly tedious having to navigate to the user dir (which I keep on my home partition) - could Strip not make a note of my preference?

**Comment by stoermelder** [comment]
Dialogs open now in the `patches`-folder of the Rack-userdir.

**Comment by zeronoises** [comment]
Thank you!
