### ISSUE TITLE
MIDI-CAT filter in newest nightly build not good for pick up mode

### ISSUE THREAD

**Issue by MaZe6K** [stoermelder/vcvrack-packone#42]
Hi there!

I just downloaded the latest nightly build and wanted to tell you that it makes MIDI-CAT with pick up mode 2 pretty much unusable. I assume this is the new filtering that I read about?
With the last build I used, it worked really great, with the newest one I can not make fast enough movements without loosing the control.
Fortunately I have a backup of the previous version which I will use for now... if this is the new filter please apply it after the pick up (if that's possible) or maybe disable it for pick up mode 2 altogether. Controls are lost far too easy this way.

**Comment by stoermelder** [comment]
Thanks, I reverted the filtering for now.
