### ISSUE TITLE
8Face: pingpong not working as expected

### ISSUE THREAD

**Issue by Eurikon** [stoermelder/vcvrack-packone#43]
Hi Ben!

ping pong is not working, it is not proceeding to next step.
it stays halted at the first slot.

The other modes work perfectly.

**Comment by stoermelder** [comment]
Thanks for reporting, but I can't reproduce. Please provide a example patch.

**Comment by Eurikon** [comment]
ok , will send it

**Comment by Eurikon** [comment]
Hmmm, i could not reproduce it :-x
Sorry to have wasted your time mate. 
Anyway if it happens again in the future, i will document it better before opening an issue.

**Comment by stoermelder** [comment]
No problem, do not hesitate to respond here or open another issue if you discover something strange.
