### ISSUE TITLE
uMap - add option to invert on OUT

### ISSUE THREAD

**Issue by Eurikon** [stoermelder/vcvrack-packone#46]
Hi Ben, could you please add a invert toggle switch for the output at the bottom of the module?
This way i can invert the signal that is passed out, to control a second uMap that will do the exact same thing to a different parameter but then inverted :)

**Comment by stoermelder** [comment]
Hi Latif, you mean outputting -3.5V instead of 3.5V, for example? Yes, I can add that.

**Comment by Eurikon** [comment]
Yes please :)
thanks!
