### ISSUE TITLE
ReMOVE pass through request

### ISSUE THREAD

**Issue by ContemporaryInsanity** [stoermelder/vcvrack-packone#48]
I note that a request to route 'in' to 'out' while recording has been addressed, would it also be possible to route 'in' to whatever the module is mapped to?

For context, I attempted to use MIDI mapped Vult Knobs into ReMOVE 'in' to record movements from a hardware controller, which works fine, but I don't get to hear the result while recording, only on playback.

I may of course be going about this entirely the wrong way, I just want to use ReMOVE as usual but with a midi controller instead of using the mouse.

**Comment by stoermelder** [comment]
That sounds more than a bug instead of expected behaviour. I will look into it.
