### ISSUE TITLE
CV-PAM - MIDI Merging with MidiMap

### ISSUE THREAD

**Issue by vcvrackideas** [stoermelder/vcvrack-packone#5]
Is it possible to merge midi mapping from real controller and CV PAM from one knob? This will be awesome to connect knob wiggling to CV sending. Really useful for live situation...

**Comment by stoermelder** [comment]
I‘m not sure if I understand correctly.
Can’t you use the normal MIDI-CC module  in combination with CV-MAP? This way you have CV and the knob is controlled by MIDI.

**Comment by stoermelder** [comment]
I guess this is what the upcoming MIDI-CAT module (working title) does.
