### ISSUE TITLE
8FACE - placement on the left of module

### ISSUE THREAD

**Issue by Eurikon** [stoermelder/vcvrack-packone#50]
Is there any chance that 8Face could have an option to be placed at the left side of the module it will be controlling?
Some modules have an expander on the right side, and therefor 8Face can not "reach" the main module to be controlled.

**Comment by stoermelder** [comment]
Added. Thanks for the suggestion, Latif!

**Comment by Eurikon** [comment]
Wow seriously? @-@ that is fantastic news!! Thanks Ben!!
