### ISSUE TITLE
Module idea: Patch loader replacing missing modules with dummy ones

### ISSUE THREAD

**Issue by diimdeep** [stoermelder/vcvrack-packone#52]
Opening .vcv patch with missing modules in library presents challenge to figure out lost wire connections and repatch with existing modules.  
Missing modules could be replaced with dynamic dummy modules preserving in/out cables.

AFAIK strip is basically patch loader and this should be trivial to implement.

**Comment by stoermelder** [comment]
There is another issue suggesting this function for STRIP. I can’t do anything for loading patches in general as errors and missing modules are handled from Rack itself. 
I can definitely replace a missing module with a dummy module, the harder part is to figure out what to do with cable connections as there is no port information available if the module is missing. The only option is to store some meaningful information for the ports of a module within the STRIP-file while saving which can be used afterwards.

**Comment by stoermelder** [comment]
Also, a module provides no information on ports through the API in Rack v1 except for an integer index.
This will change if https://github.com/VCVRack/Rack/issues/1457 is added in a future version of Rack.

**Comment by stoermelder** [comment]
I close this one: 
About STRIP to handle missing modules there is already #18. About a module for general patch loading: It is not possible, I investigated this for #40 without any success.
