### ISSUE TITLE
Strip- keep original cable colors of patch

### ISSUE THREAD

**Issue by technochitlin** [stoermelder/vcvrack-packone#53]
Currently Strip seems to assign cable colors randomly when loading a patch- is there any way that the original cable colors could be kept?

Before saving-
![image](https://user-images.githubusercontent.com/737753/66485622-c0980080-ea6e-11e9-8bb0-c2e8522a7638.png)

After re-loading-
![image](https://user-images.githubusercontent.com/737753/66485551-a3633200-ea6e-11e9-9803-a21dfbe443ae.png)

**Comment by technochitlin** [comment]
Oops... I just discovered this only happens when the WM-101 Submarine Wire Manager is loaded. Otherwise load fine. My error, sorry...

**Comment by stoermelder** [comment]
Yes, STRIP saves and recalls cable coloring. Glad you sorted it out!

**Comment by technochitlin** [comment]
I realize you closed this, but I just want to add- if you SAVE while the WM-101 module is loaded, it will save ALL the colored cables, not just the 'standard 4'; if you load a preset with the WM-101 loaded you get the randomized colors, but if you load the preset with WM-101 unloaded ALL the colors you saved- even the non-standard ones- are recalled.

**Comment by stoermelder** [comment]
I’m not sure what I should do. Sounds to me like expected behavior...
