### ISSUE TITLE
Module idea: Remote control

### ISSUE THREAD

**Issue by diimdeep** [stoermelder/vcvrack-packone#55]
Like CV-MAP but in grid layout and instead of external signal show knob for each mapped parameter.
Inspired by Bitwig Remote Control 

![Screenshot 2019-10-20 at 19 01 26](https://user-images.githubusercontent.com/485713/67162458-cb0aa200-f36c-11e9-92f6-30ec4e1018de.png)

**Comment by stoermelder** [comment]
Sounds interesting. I'm no Bitwig user but I have an 8-track licence.

**Comment by stoermelder** [comment]
I'm closing this as there is now a module for this:  
https://community.vcvrack.com/t/introducing-mindmeld-patchmaster-and-routemasters/18812
