### ISSUE TITLE
Midi-Cat with Arturia Beatstep 

### ISSUE THREAD

**Issue by submitaudio** [stoermelder/vcvrack-packone#56]
Love this module!,
Is it possible to use the Arturia midi protocol for midi in and out (knob controll): They use the Relative midi mode. Like that i can use my Rotary knobs without jumping or snap.
Thanks!

**Comment by stoermelder** [comment]
I don’t own a Beatstep. Can you elaborate this request a little more?

**Comment by submitaudio** [comment]
Relative mode means that the encoders send MIDI messages that can increment or decrement a parameter without there being jumps in the values. This allows for smooth operation and allows for greater interaction in applications that support this type of MIDI data. Example:
If the encoders are set to RELATIVE 1 (using the free MIDI CONTROL CENTER software), the encoders will send a stream of MIDI messages with data values of 65-67 when turned clockwise and will send a string of MIDI message 63-61 when turned counter clockwise. The faster you turn the encoder, the higher or lower the data value. Relative 2 and Relative 3 modes
are similar in operation but send different values.

more about the midi relative protocol:
https://github.com/rsjaffe/MIDI2LR/issues/195

**Comment by stoermelder** [comment]
Ah, I remember now. someone mentioned MIDI relative mode some time ago. I will look into it!

**Comment by submitaudio** [comment]
Thank you...

**Comment by stoermelder** [comment]
Some progress has been made regarding this request:
https://github.com/stoermelder/vcvrack-packone/issues/87
If everything works out successfully MIDI relative mode will be added soon.

**Comment by submitaudio** [comment]
Cool nice ;) i just installed Midi-Step and will try it out... Thanks again

**Comment by submitaudio** [comment]
I just tested it with my Beatstep: a got a big legg when i use more then 16 Pile modules in combination with Midi Step. And i wanted to create 4 midi channels x 16 controllers= 64 Pile modules. ;)

**Comment by stoermelder** [comment]
In the latest build MIDI-STEP can output all 8 channels on using a polyphonic cables on the first port and I added a polyphonic version of PILE called POLY-PILE. Feel free to check them out.

**Comment by submitaudio** [comment]
O Woow ok....
is it version 1.5?

**Comment by submitaudio** [comment]
It's in version 1.6, ok nice.... 
please let me know when i can test it...

**Comment by submitaudio** [comment]
ThanXX you so much ;) This makes VCV like real hardware ;) working nice with 4 midi channelsx16 knobs

![image](https://user-images.githubusercontent.com/6167892/79284204-3b2c5780-7eba-11ea-9c62-d49a171638de.png)

**Comment by stoermelder** [comment]
As the Beatstep works nicely with MIDI-STEP I'm closing this issue. Adding this functionality it would make MIDI-CAT much to complicated to handle for code and user.
