### ISSUE TITLE
copy knob positions between adjacent, identical modules

### ISSUE THREAD

**Issue by glocke01** [stoermelder/vcvrack-packone#60]
Sort of a polyphony hack - is it possible to make a module that would copy knob positions from one module to another of the same module? An example use would be to get stereo functionality from non stereo modules (e.g. filters, delays, or Macro Oscillator 2 in any of the various granular modes).

**Comment by stoermelder** [comment]
You can do this right now, I showed it in a very early version of my modules.
It would require some parameter mapping, but is this what you are talking about?
https://community.vcvrack.com/t/module-cv-map-for-cv-controlling-any-knob-slider-or-switch/1914/14

**Comment by glocke01** [comment]
yes, you already solved it! thanks!!
