### ISSUE TITLE
8FACE - module grouping like STRIP

### ISSUE THREAD

**Issue by nay-seven** [stoermelder/vcvrack-packone#63]
Hello,
A quick question/suggestion, as i see Strip can act/random on several modules, is there a chance 8FACE can do the same for presets ? saving presets for a block of modules can be a cool tool ? 
I know i can add several 8FACE modules and drive them by 1 control , but group mode can be quickest an cpu friendly ?

I of course also dream of a "global " 8FACE who can save 8 (or more) presets for all the patch and with fades between each of them, but i'm a dreamer, i know ;-)

**Comment by vcvrackideas** [comment]
yep, I'm in too! Very like idea, especially when using it with arm and midi contollers together, would be very handy.

**Comment by stoermelder** [comment]
Thanks for the suggestion, I will check how much change it needs to support multiple modules.

**Comment by nay-seven** [comment]
Thanks a lot to consider it  !

**Comment by pnortnaomi** [comment]
I hope this this feature could be implemented. It would be very helpful.

**Comment by stoermelder** [comment]
I will consider this request after the source for Rack v2 is made public. 
The current implementation of 8FACE has some issues which can hopefully addressed in the next version of Rack. Adding "grouping" right now would decrease the stability of the module even more.

**Comment by nay-seven** [comment]
ok, thanks !

**Comment by stoermelder** [comment]
Added in 8FACE mk2.

**Comment by nay-seven** [comment]
Whaoo ! 
Thanks a lot Ben ! ! 
Works fine here Mac mojave/rack 1.6
