### ISSUE TITLE
8FACE - more contrast?

### ISSUE THREAD

**Issue by ContemporaryInsanity** [stoermelder/vcvrack-packone#72]
Small light blue / light green leds on a light blue background, very little contrast, difficult to see when module is small.

**Comment by ContemporaryInsanity** [comment]
Perhaps build bigger lights into bigger buttons?

**Comment by stoermelder** [comment]
Hi Ewen, maybe you want to test the latest build of my plugin :-)

**Comment by ContemporaryInsanity** [comment]
Wow!

**Comment by stoermelder** [comment]
I hope you like it better with the updated layout. A dark theme is also on my to-do list but this is going to be something for the version after next release.
