### ISSUE TITLE
MIDI-CAT loses mapping on save preset and reopen hangs Rack

### ISSUE THREAD

**Issue by fractalgee** [stoermelder/vcvrack-packone#77]
I just mapped my 2 connected Minilar controllers to MIDI-CAT (32 slots) and then went to save this as a preset. After saving the module was back to all 32 slots reporting 'Unmapped'.
Tried to reload the saved preset and it hangs Rack, has to be killed, which leaves a zomby Bridge Server background process behind.

Rack 1.6.2
Win 10
latest plugin manager Stoermelder modules.

Attached: the saved preset and useless log file 
[Stoermelder-Minilars_Mapping.zip](https://github.com/stoermelder/vcvrack-packone/files/3991625/Stoermelder-Minilars_Mapping.zip)
[log.txt](https://github.com/stoermelder/vcvrack-packone/files/3991628/log.txt)

**Comment by stoermelder** [comment]
Sorry, there is no API in Rack to keep parameter mappings across patches. You can try VCV's MIDI-MAP module which will give you most probably the same result by loosing all mappings.
The only way I know of keeping mappings within a group of modules is using my own STRIP module.

**Comment by fractalgee** [comment]
OK, hmm, that is a missing feature then, will see if an FR can be filed for
Rack to add that ability. The preset file looks a bit weird though in that
first module is 0 and second is -1.

Reason I used yours was that the VCV one can only map 16 of the
controllers, as even adding second one does not see Minilar2, so stuck :(

**Comment by stoermelder** [comment]
This is strange. VCV's MIDI-MAP supports up to 128 mappings slots and there is no limitation in using the same MIDI device in multiple MIDI modules. Maybe you can check again but this sounds more like a bug in Rack.

**Comment by fractalgee** [comment]
maybe so, but still the device names at bottom of the vcvm file look
illegal (-1) so no idea how Rack would save that unless module had it set
like that? Anyhow, will file an issue, as Midi-CC from VCV does not see
Midilar 2, only 1, yours sees both, as they are chained together . Anyhow,
for sure a FR for adding API to save MIDI mappings is in the works, but
still, device number -1 looks fishy to me, that should be 1 instead as 0 is
the first one.....

**Comment by stoermelder** [comment]
Are you sure that "Midilar 2" is not a MIDI output port? MIDI-CC won't see output ports as it is only an input module but CV-CC will see output ports.
My module is using Rack's MIDI API and I haven't implemented anything myself on that topic, my module "sees" exactly the same MIDI ports a every other module.

**Comment by fractalgee** [comment]
That is odd, the MIDI-CC sees Minilar1, which is the first 16 ports of MIDI
out that the minilars send. If I add a second I still cannot map the second
one that is actually connected straight to the first one so 32 ports as far
as I can make out. Your MIDI-CAT module clearly sees both Minilar 1 and 2
and I can happily map me all 32 ports. So if it is using same code then I
am confused, as the VCV side modules refuse to let me map the second set of
16... I wish the MIDI-CAT could also come as a module with just the 32
outs, which I could plug cables in via a split to send off to different
modules, as now I must map it to specific module and parameter. So only
half way there either way. Also choosing unmap on the module mapped will
crash Rack hard, leaving a zomby in it's wake, which can't even be force
quit (killed),, so needs minimally a logout/login to rectify and then trash
autosave to ever get Rack to boot again. I will log a Rack bug for that as
that seems to crash deep withing it's engine's MIDI interactions. Very odd
this.

So, I guess the ugly stepcchild of the MIDI-CAT with the poly outs of the
MIDI-PAM would be super swell, and problems solved :D

Thanks for nifty modules!!!!

**Comment by stoermelder** [comment]
Hm, isn't the VCV MIDI-CC module the thing you want? It outputs CV for MIDI CC, similar as CV-PAM outputs CV for parameter movements.

About the crash on "Unmap": Does it also happen with the MIDI-MAP module? If yes it could be indeed a problem in Rack's MIDI implementation. Still, I have no explaination why there should more MIDI devices visible in my module...

**Comment by fractalgee** [comment]
MIDI-CC maps MIDI messages (sent by the minilars) to CC which you can
access via plugging in cables to the different ports that are mapped....
It does work until 16 ports, then nada. I also cannot tell you why yours
sees both sides whereas the MIDI-CC just one...    My previous request was
serious for a mutant stepchild between the poly outs on MIDI-PAM and the
MDI-CAT, so I don't have to permanently map incoming to wa specific module
and have to map that everytime, but rather a output that I can split into
it's component parts via a split module, so I can use each to modulate
whatever I havven to connect to it, no mapping needed as i may have to
remap several times during working out what I want to do and which
direction to go....

**Comment by stoermelder** [comment]
I understood your suggestion but I don't think it is worth the effort: You can simply use MIDI-CAT and MIDI-CC side-by-side for the same MIDI device and the same CCs. You can also add more instances of MIDI-CC if you need more than 16 CCs and use the same MIDI device as before.

**Comment by fractalgee** [comment]
OK, understood, but the multiple MIDI-CC does not work, as I tried and
indicated above, so will have to see if I can find a way, so far not yet ;)

**Comment by stoermelder** [comment]
It does work here, tried it again just now. If it doesn't work with your MIDI controller you should report a bug on Rack's repository as multiple modules using the same MIDI device is definitively supported.

**Comment by fractalgee** [comment]
ok, weird I can't get it to work, so will keep trying or log a bug with
Andrew...

Anyhow, keep making nifty modules, they are very much unique! Btw, Maze is
also very neat, Arena I still have to get head around ;)

go well

**Comment by stoermelder** [comment]
I'm closing this one as MIDI access to hardware is handled by Rack itself and using the same MIDI device in multiple modules is definitively possible.
