### ISSUE TITLE
INTERMIX: enable/disable button for outputs

### ISSUE THREAD

**Issue by ligantx** [stoermelder/vcvrack-packone#80]
I would like to ask for a new feature that i guess its easy to implement..
As there is button for enable/disable and midi map capabilities for every input line..it would be useful to add enable/disable and midi map capabilities button to outputs (see picture).
This can help so every 8x8 connection can be enabled with any combination of 8 midi enabled inputs and 8 midi enabled outputs.

![064](https://user-images.githubusercontent.com/26394054/71658158-8d9e9980-2d4b-11ea-8295-18b91d834ffc.png)

**Comment by stoermelder** [comment]
I'm not quite sure if I understand your request correctly: The button you circled on the right side disables the first row and the first output port. There is no "disable" button for the inputs on the bottom but this seems a bit of overkill as enabling the inputs is main purpose of the matrix. Besides that you can use scenes for that :-)
At the moment there is no manual for the module. I guess it would help as not every function of the module is obvious.

**Comment by ligantx** [comment]
sorry for not being more clear..
what i want to do is: 
with two different midi messages, enable a connection..
So i was thinking, if i push my two buttons on a midi controller (that i will midi map) i would enable a specific connection..
Lets say i have two 8 button midi controllers..
I would like, if press button 3 to the first one...and 5 to the second..to do a connection at 3x5 (horizontal 3, vertical 5)..
until now i can do this like this:

![067](https://user-images.githubusercontent.com/26394054/71662001-aa8d9980-2d58-11ea-92d7-d08ce58e3279.png)
![068](https://user-images.githubusercontent.com/26394054/71662004-ab263000-2d58-11ea-824f-594f05d4e362.png)
![069](https://user-images.githubusercontent.com/26394054/71662005-ab263000-2d58-11ea-9dff-e7438663672d.png)

**Comment by stoermelder** [comment]
Ah, I see. So you don't need additional buttons, you want to enable a button of the matrix using 16 buttons on your MIDI controller, 8 for the inputs, 8 for the outputs. In current your solution with MUTE8 you can only disable one input or one output but you cannot disable a specific connection, right?

**Comment by ligantx** [comment]
Actually i need 8 extra buttons..but for the horizontal axis (the outputs)..as the arrow shows..

My current solution works fine, but i have to make a lot of extra work (to connect every mute8 out to father&son)..with INTERMIX if there were 8 extra on/off buttons to the OUTPUTS(horizontal)..it could work...

NOTICE: i should point that earlier..i want to accomplish virtual cables..SO, it supposed to be 1-per-1 connection..if i press button 3 to the first controller...and 5 to the second..ill do a connection at 3x5 (horizontal 3, vertical 5)..i will not use 3x1, 3x2, 3x3, 3x4... and 1x5, 2x5, 4x5... connections..but i dont mind..
maybe this `https://community.vcvrack.com/t/midi-controlled-cables/6972` would help (we've speaked before)

**Comment by stoermelder** [comment]
Just a note: The horizontal ports are the input ports.
Ok, I have an idea. I don't want more buttons because they won't add any more functionalty. But I can add some "widget" near the input ports on the horizontal row which allows mapping your MIDI controller. I've done something similar on my ARENA module. A connection could then be made by selection the input port and afterwards the output port through the exisiting buttons.
This should't be hard to implement, I will try it in the evening after I get home.

**Comment by ligantx** [comment]
thats sounds nice..
i guess "allowing midi mapping" you mean on/off the horizontal ports right?

**Comment by stoermelder** [comment]
No, I mean to enable every button on the matrix. It is a bit difficult to explain, I'll do a short video later.
You press and hold MIDI button for input port 3, then you press the MIDI button for output port 5, which will enable the connection in column 3, row 5.

**Comment by stoermelder** [comment]
I decided against using the existing buttons for several reasons. Instead I added small circles on the rows and columns, these parameters can only be used for MIDI-mapping. Pressing the control for column 3 and then the control for column 2 enables the pad 3 from the left and 2 from the top. Should be quite intuitive.

Feel free to try out the latest build:
https://github.com/stoermelder/vcvrack-packone/releases/tag/Nightly

![image](https://user-images.githubusercontent.com/47640667/71694348-3205f780-2daf-11ea-98e2-5be806200b2d.png)

**Comment by ligantx** [comment]
that looks perfect!..
i tried to make this work but i havent done any vcv rack stuff as developer..so i followed this `https://vcvrack.com/manual/Building#setting-up-your-development-environment` but i couldnt make this work..

Do you have any easy to follow tutorial? I tried to paste the windows zip content to `....\VCV\Rack\res\ComponentLibrary` but it doesnt work..(where i have to put the plugin.dll/plugin.json files?

**Comment by stoermelder** [comment]
Sorry for the inconvenience, you don’t need to setup a build environment.
https://vcvrack.com/manual/Installing#installing-plugins-not-available-on-the-plugin-manager

**Comment by stoermelder** [comment]
@ligantx had you chance to test the new mapping option?

**Comment by ligantx** [comment]
@stoermelder sorry for being so late, i tried it today and it looks to work but partially.. i mapped two latch button of my akai mpk mini and i can turn on and off but it isnt consistent..ill try to make a video of this later in the day..
actually is there any way to know if i pressed these small midi cc buttons of intermix?

**Comment by stoermelder** [comment]
Yes, you can enable parameter tooltips and hover over them with the mouse pointer. One thing you have to know: You need to press and hold one of the horizontal controls first, then one of the vertical controls afterwards.

**Comment by ligantx** [comment]
ill tried to replicate what i want to do:
when i press both buttons i enable the connection..when i press one of them i disable the connection,
[https://www.dropbox.com/s/u02fbvuwotp34e6/2020-01-13%2003-11-23.mp4?dl=0](url)

with INTERMIX, it is working fine to ENABLE the connection (i had to press "Full Level" button on akai mpk mini to send 0 and 1 values and not something like 0.76545), BUT i cannot disable it when i pressed any of the two buttons i assigned. 
[https://www.dropbox.com/s/w1plcjj2fddw0wk/2020-01-13%2003-15-29.mp4?dl=0](url)

-----------------------------------------------------------
EDIT: i made it work! i guess the values between 0 and 1..was ruining it..
Now..i press button 1 HOLD IT, then button 2...connection enabled..
then pressed the same..connection disabled..FINE

just a question: if i want to do in midi messages..it will be something like this (in order to simulate the holding of button1)?
`mapped MOMENTARY button1 CC, value 127` 
`mapped MOMENTARY button2 CC, value 127` 
`mapped MOMENTARY button1 CC, value 0` 
`mapped MOMENTARY button2 CC, value 0`

**Comment by stoermelder** [comment]
> just a question: if i want to do in midi messages..it will be something like this (in order to simulate the holding of button1)?
> `mapped MOMENTARY button1 CC, value 127`
> `mapped MOMENTARY button2 CC, value 127`
> `mapped MOMENTARY button1 CC, value 0`
> `mapped MOMENTARY button2 CC, value 0`

Yes, this should work.

**Comment by stoermelder** [comment]
I'm closing this issue as its request will be implemented in another (experimental) module.
