### ISSUE TITLE
MIDI-STEP

### ISSUE THREAD

**Issue by stoermelder** [stoermelder/vcvrack-packone#87]

**Comment by stoermelder** [comment]
@tokkeherfst I implemented MIDI relative protocol as a separate module. It is a quick draft and far from finished but you can try it out.
It seems that "Beatstep Relative Mode 2" is available on NI controllers called "Relative". "Beatstep Relative Mode 1" seems to support three different velocities but due to lack of controller I couldn't test it.

**Comment by tokkeherfst** [comment]
Thanks, I will give it a try tonight!

**Comment by tokkeherfst** [comment]
Couldn't wait... ;-)

Beatstep Rel2 is working fine for me, for Beatstep Rel1 mode it is only increasing the value
When turning CW I see 3x 5V triggers in a row on INC, when turning CCW I see 1x5V trigger on INC, not DEC.

I guess a dump of the midi values might help:
CW turn:
![image](https://user-images.githubusercontent.com/1422502/71958124-c75e1d00-31ef-11ea-8f23-c4995b7eb9e2.png)

CCW turn:
![image](https://user-images.githubusercontent.com/1422502/71958137-d0e78500-31ef-11ea-9da3-4b223c86d753.png)

I also tested the fine control, it seems the issue with the value calculation is fixed now. Fine mode now goes all the way in both directions!

So both my ShuttlePro (via keyboard) and Beatstep Pro (in rel2) are working great now via the INC/DEC inputs! Using a toggle button on both to access fine control.

Here's my current setup, allowing to use both of these in parallell.
![image](https://user-images.githubusercontent.com/1422502/71958577-ec06c480-31f0-11ea-91d3-bb32a03bcd4f.png)

Awesome work Ben!

**Comment by stoermelder** [comment]
Thanks for testing, Tom!
I misread your previous MIDI dump, i will fix it later today. Can you try if you get 42 or 43 (third data column) when moving the knob faster CW? It seems that the Beatstep supports three different velocities in mode 1 but I'm not sure yet how to handle these. Currently 1, 2 or 3 triggers are generated. This will need some testing and fine-tuning after I fixed mode 1...

**Comment by stoermelder** [comment]
> When turning CW I see 3x 5V triggers in a row on INC, when turning CCW I see 1x5V trigger on INC, not

Fixed in 7e5dd4219ce49f44ff501200c267c50d8025db64.

**Comment by tokkeherfst** [comment]
Tests with the latest release and Beatstep Rel1 mode: works really nice!
There is clearly a difference in feel when turning fast and slow. In fact I had to bring down the step size a bit but that's really good in fact, so FINE really becomes a very fine control ;-)

BTW here is the CC value that I am seeing on midi (hex):

Slow CW: 41
Faster CW: 43
Very fast CW: 46 or more
Slow CCW: 3F
Faster CCW: 3D
Very Fast CCW: 3A or less

Thanks!

Tom

**Comment by stoermelder** [comment]
I tuned it according your CC values in c2bc725683ae99f70c89ac543fd614e7708343d9. The changes shouldn't be that huge now, hopefully.

**Comment by tokkeherfst** [comment]
Tested it, works really smooth ;-)

Loving it, now I can just turn one computer monitor towards my desk with synth hardware, take a wireless trackpad to select the Rack modules and use one knob on the beatstep to tweak any parameter.
Awesome, can't wait for my ES-8 to be delivered to bridge the virtual and physical synth world ;-)

**Comment by JustMog** [comment]
Can confirm this works great with Ableton's push (2). No setup required on the push end,
Beatstep Relative #2 and NI Komplete both work equally well. Thanks!
