### ISSUE TITLE
MIDI-CAT - Feature request: lock

### ISSUE THREAD

**Issue by tomfug** [stoermelder/vcvrack-packone#89]
Hope it’s ok to suggest features here... love using MIDI-CAT with controllers that have visual feedback. Really added to the whole vcv rack experience. What I would love to see is a right click menu to lock the module, so that nothing can be mapped or unmapped in that state. This would prevent unmapping or mapping a controller with accidental mouse clicks in the module.

**Comment by stoermelder** [comment]
Hi @tomfug, thanks for your suggestion! Added in ecb4b33098a68564574108e53470e09e37518ff6.

**Comment by tomfug** [comment]
Thanks Ben!
