### ISSUE TITLE
MIDI-CAT: Note doesn't toggle

### ISSUE THREAD

**Issue by Boscop** [stoermelder/vcvrack-packone#90]
Hi, thanks for this great pack, I've been testing MIDI-CAT, and it seems to work well for CCs, but for notes, it doesn't work with Toggle mode. I tested it on the solo/mute buttons of the MixMaster module: The button state stays ON after being toggled on, no matter how many times I press the key (on my midi keyboard) after that.

**Comment by stoermelder** [comment]
Thanks for reporting. This is a bug in the current public release and has already been fixed in b188c38.
You can download a recent build from here https://github.com/stoermelder/vcvrack-packone/releases/tag/Nightly or wait until v1.5.0 is released to the library.

**Comment by Boscop** [comment]
Thanks for the quick response :)
