### ISSUE TITLE
STRIP: Feature request - Labeling?

### ISSUE THREAD

**Issue by tmladek** [stoermelder/vcvrack-packone#91]
Hello,
hope you don't mind me suggesting a feature:

STRIP is *incredibly* handy, but once I'm more or less done with the layout of the patch, it just sits there, doing nothing (or I delete it and then have to re-adjust the strip itself).

What would be really neat is if it also had a labelling section (maybe kind of like cf's `LBL`?), so that one could use it to delimit different parts of the patch (voices, sequencing, percussion, etc.). Then it could act as a "section header", both visually aiding the eye in busy patches, and also helping to save presets. 

It might have to be a bit wider to accomodate this, but an additional version that's maybe 2-3HP wider could allow both uses.

Thanks for considering, and for a great pack of modules!

**Comment by stoermelder** [comment]
Thanks for your suggestion but wouldn't it be easier and more flexible just to include one of the existing labeling modules within the strip?

**Comment by tmladek** [comment]
Hm, I guess you're right; I suppose I also kind of wanted to see this functionality in STRIP because cf's `LBL` crashes at the moment (: 
(Which is obviously not your responsibility by any means)

And of course, not too much space would be even saved, as any label module is also at most 2HP. Thanks for considering, anyway!
