### ISSUE TITLE
ARTIFACT

### ISSUE THREAD

**Issue by stoermelder** [stoermelder/vcvrack-packone#92]
Combination of CV-MAP and 8FACE: allows mapping of parameters and stores their current value in slots. These slots can be recalled or even morphed, manually or by CV. Provides some sort of snapshot-functionality.

**Comment by tomfug** [comment]
If this ever became a module, that would be absolutely amazing!

A good example of this is how snapshots work in Reaktor. In an ideal world it would have banks of snapshots and being able to save/load banks to/from files. Currently it's pretty much the only thing that remains to make VCV the ultimate live performance software (for me, that is).

**Comment by stoermelder** [comment]
I didn’t follow this idea anymore, as there already a module:
https://library.vcvrack.com/23volts/Morph

**Comment by tomfug** [comment]
Ah that’s a shame. It was the integration with CV-Map that was the most exciting part for me, allowing to do massive changes to a patch (50+ values) at the touch of a button. Will be interesting to see how the vst version will handle automation etc, which might make this easier to do inside a host.

**Comment by stoermelder** [comment]
I will think about it, maybe I can do some sort of expander for CV-MAP.

**Comment by tomfug** [comment]
I don't know how popular the idea is amongst others, but for me something like that would be an absolute game changer. Essentially having a fixed rack for performances and being able to have midi control over launching "songs" and sections of songs without touching the laptop. Also meaning not having to load up a new patch in vcv rack and thereby pausing sound. Being able to morph or randimize would be like an afterthought and bonus. But also appreciate you probably have more interesting ideas to spend your time on :)

**Comment by stoermelder** [comment]
Just to be clear: If I consider this it will be possible to restore values of mapped parameters on by CV-MAP and maybe morph between them. It won’t help with different patches or other module settings besides parameters.

**Comment by tomfug** [comment]
Essentially the way i would see it work was like you said, an expander to CV-MAP (or even better, MIDI-CAT) and all it would do would change the values of the mapped parameters. Changing states of unmapped parameters, cable connections etc. i would have thought would be impossible.

**Comment by stoermelder** [comment]
Closing this, the proposed functionality is available in TRANSIT.
