### ISSUE TITLE
INTERMIX - Fade times not working?

### ISSUE THREAD

**Issue by Xenakios** [stoermelder/vcvrack-packone#99]
It appears the fade in/out knobs don't do anything, the scenes switch immediately without fades applied when clicking on the buttons in the GUI. (Could be a user error/misunderstanding, though...?)

**Comment by stoermelder** [comment]
Did you set the input port for fading? The display should show FAD.

**Comment by Xenakios** [comment]
Ah right, I didn't notice the fades need to be enabled separately. Works now, thanks!
